'use client'
import SubjectPage from '../components/SubjectPage'

const scienceChapters = [
  {
    id: 'sci-1',
    title: {
      mizo: 'Chapter 1: Physics - Mechanics & Motion',
      english: 'Chapter 1: Physics - Mechanics & Motion'
    },
    notes: {
      mizo: [
        '**1. Units & Measurement**',
        '**SI Units 7 Base:** Length meter m, Mass kilogram kg, Time second s, Current ampere A, Temperature kelvin K, Amount mole mol, Luminous candela cd.',
        '**Derived:** Force newton N = kg·m/s², Pressure pascal Pa = N/m², Energy joule J = N·m, Power watt W = J/s.',
        '**Dimensional Formula:** Velocity [LT⁻¹], Acceleration [LT⁻²], Force [MLT⁻²], Work [ML²T⁻²].',
        '**Errors:** Least Count = Smallest division. Vernier 0.01cm, Screw Gauge 0.001cm.',
        '',
        '**2. Motion Laws**',
        '**Scalars:** Speed, Distance, Mass, Time, Temperature. **Vectors:** Velocity, Displacement, Force, Acceleration, Momentum.',
        '**Equations:** v = u + at, s = ut + ½at², v² = u² + 2as. Free fall g = 9.8 m/s².',
        '**Newton Laws:**',
        '   1. **1st Law Inertia:** Body rest/motion unless force. Inertia = mass.',
        '   2. **2nd Law:** F = ma. Momentum p = mv. Impulse = Ft = Δp.',
        '   3. **3rd Law:** Action = Reaction. Equal opposite. Rocket propulsion.',
        '**Friction:** Static > Sliding > Rolling. Lubricants reduce. Banking roads mv²/r.',
        '',
        '**3. Gravitation**',
        '**Universal Law:** F = Gm₁m₂/r². G = 6.67×10⁻¹¹ Nm²/kg² Cavendish.',
        '**g Variation:** Max poles 9.83, Min equator 9.78. Decrease height/depth. Zero centre earth.',
        '**Satellite:** v = √(GM/r). Geo-stationary 35,786 km. Time 24 hrs. INSAT series.',
        '**Escape Velocity:** v = √(2GM/R) = 11.2 km/s Earth. Moon 2.4 km/s.',
        '',
        '**4. Work, Energy, Power**',
        '**Work:** W = F·s·cosθ. Joule. Zero if θ=90°.',
        '**Energy:** Kinetic ½mv², Potential mgh. Conservation - total constant.',
        '**Power:** P = W/t = F·v. Watt. 1 HP = 746 W.',
        '**Simple Machines:** Lever, Pulley, Inclined plane. MA = Load/Effort.',
        '',
        '**5. Properties Matter**',
        '**Elasticity:** Hooke Law F = kx. Stress/Strain = Y Young modulus.',
        '**Pressure:** P = F/A. Liquid P = hρg. Pascal Law - brake system.',
        '**Buoyancy:** Archimedes - Upthrust = Weight displaced fluid. Law floatation.',
        '**Surface Tension:** Drops spherical. Capillarity tube rise. Detergents reduce.',
        '**Viscosity:** Fluid friction. Honey > Water. Stokes Law terminal velocity.',
        '**MPSC Point:** g = 9.8 m/s², G = 6.67×10⁻¹¹, Escape 11.2 km/s, 1 HP = 746W.'
      ],
      english: [
        '**1. Units & Measurement**',
        '**SI Units 7 Base:** Length meter m, Mass kilogram kg, Time second s, Current ampere A, Temperature kelvin K, Amount mole mol, Luminous candela cd.',
        '**Derived:** Force newton N = kg·m/s², Pressure pascal Pa = N/m², Energy joule J = N·m, Power watt W = J/s.',
        '**Dimensional Formula:** Velocity [LT⁻¹], Acceleration [LT⁻²], Force [MLT⁻²], Work [ML²T⁻²].',
        '**Errors:** Least Count = Smallest division. Vernier 0.01cm, Screw Gauge 0.001cm.',
        '',
        '**2. Motion Laws**',
        '**Scalars:** Speed, Distance, Mass, Time, Temperature. **Vectors:** Velocity, Displacement, Force, Acceleration, Momentum.',
        '**Equations:** v = u + at, s = ut + ½at², v² = u² + 2as. Free fall g = 9.8 m/s².',
        '**Newton Laws:**',
        '   1. **1st Law Inertia:** Body rest/motion unless force. Inertia = mass.',
        '   2. **2nd Law:** F = ma. Momentum p = mv. Impulse = Ft = Δp.',
        '   3. **3rd Law:** Action = Reaction. Equal opposite. Rocket propulsion.',
        '**Friction:** Static > Sliding > Rolling. Lubricants reduce. Banking roads mv²/r.',
        '',
        '**3. Gravitation**',
        '**Universal Law:** F = Gm₁m₂/r². G = 6.67×10⁻¹¹ Nm²/kg² Cavendish.',
        '**g Variation:** Max poles 9.83, Min equator 9.78. Decrease height/depth. Zero centre earth.',
        '**Satellite:** v = √(GM/r). Geo-stationary 35,786 km. Time 24 hrs. INSAT series.',
        '**Escape Velocity:** v = √(2GM/R) = 11.2 km/s Earth. Moon 2.4 km/s.',
        '',
        '**4. Work, Energy, Power**',
        '**Work:** W = F·s·cosθ. Joule. Zero if θ=90°.',
        '**Energy:** Kinetic ½mv², Potential mgh. Conservation - total constant.',
        '**Power:** P = W/t = F·v. Watt. 1 HP = 746 W.',
        '**Simple Machines:** Lever, Pulley, Inclined plane. MA = Load/Effort.',
        '',
        '**5. Properties Matter**',
        '**Elasticity:** Hooke Law F = kx. Stress/Strain = Y Young modulus.',
        '**Pressure:** P = F/A. Liquid P = hρg. Pascal Law - brake system.',
        '**Buoyancy:** Archimedes - Upthrust = Weight displaced fluid. Law floatation.',
        '**Surface Tension:** Drops spherical. Capillarity tube rise. Detergents reduce.',
        '**Viscosity:** Fluid friction. Honey > Water. Stokes Law terminal velocity.',
        '**MPSC Point:** g = 9.8 m/s², G = 6.67×10⁻¹¹, Escape 11.2 km/s, 1 HP = 746W.'
      ]
    }
  },
  {
    id: 'sci-2',
    title: {
      mizo: 'Chapter 2: Physics - Heat, Light, Sound, Electricity',
      english: 'Chapter 2: Physics - Heat, Light, Sound, Electricity'
    },
    notes: {
      mizo: [
        '**1. Heat & Thermodynamics**',
        '**Temperature:** C/5 = (F-32)/9 = (K-273)/5. Absolute zero -273°C = 0K.',
        '**Expansion:** Linear α, Area β=2α, Volume γ=3α. Bimetallic strip thermostat.',
        '**Specific Heat:** Q = mcΔT. Water 1 cal/g°C = 4200 J/kg°C highest.',
        '**Latent Heat:** Ice melt 80 cal/g, Steam 540 cal/g.',
        '**Transfer:** Conduction solids, Convection fluids, Radiation vacuum. Blackbody best absorber/emitter.',
        '**Laws:** 1st ΔQ = ΔU + ΔW. 2nd Entropy increase. Heat engine efficiency η = 1-T₂/T₁.',
        '',
        '**2. Light**',
        '**Reflection:** ∠i = ∠r. Plane mirror lateral inversion. Concave converging, Convex diverging.',
        '**Mirror Formula:** 1/f = 1/u + 1/v. Magnification m = -v/u = h₂/h₁.',
        '**Refraction:** Snell n₁sin i = n₂sin r. n = c/v. Water 1.33, Glass 1.5, Diamond 2.42.',
        '**Total Internal Reflection:** Dense to rare, i > C. Critical angle. Mirage, Optical fibre, Diamond sparkle.',
        '**Lens:** Convex converging, Concave diverging. Power P = 1/f dioptre. Human eye convex f=2.5cm.',
        '**Defects Eye:** Myopia concave, Hypermetropia convex, Presbyopia bifocal, Astigmatism cylindrical.',
        '**Dispersion:** VIBGYOR. Violet deviate max. Rainbow - refraction+dispersion+TIR.',
        '**Scattering:** Blue sky Rayleigh ∝ 1/λ⁴. Red sun rise/set. Clouds white large particles.',
        '',
        '**3. Sound**',
        '**Wave:** Longitudinal mechanical. Need medium. Speed Air 343 m/s, Water 1480, Steel 5960 m/s.',
        '**Properties:** Pitch ∝ frequency, Loudness ∝ amplitude², Quality harmonics.',
        '**Range:** Infrasonic <20Hz, Audible 20-20,000Hz, Ultrasonic >20kHz. Bat SONAR.',
        '**Echo:** Distance = (v×t)/2. Min 17m. Reverberation multiple reflections.',
        '**Doppler:** Frequency change source/observer motion. Siren pitch change.',
        '',
        '**4. Electricity**',
        '**Current:** I = Q/t ampere. Ohm Law V = IR. Resistance R = ρl/A Ω.',
        '**Combination:** Series R = R₁+R₂, Parallel 1/R = 1/R₁+1/R₂.',
        '**Power:** P = VI = I²R = V²/R watt. Commercial unit kWh. 1 kWh = 3.6×10⁶ J.',
        '**Heating:** H = I²Rt Joule Law. Fuse, Heater, Bulb.',
        '**Domestic:** 220V AC 50Hz India. Live red, Neutral black, Earth green.',
        '',
        '**5. Magnetism**',
        '**Properties:** Attract Fe, Ni, Co. Like repel, Unlike attract. North seeking.',
        '**Earth:** Magnetic South geographic North. Angle Declination, Dip.',
        '**Electromagnet:** Solenoid + Iron core. Electric bell, Crane.',
        '**Motor:** Electrical→Mechanical. Fleming Left Hand Rule.',
        '**Generator:** Mechanical→Electrical. Fleming Right Hand. AC dynamo, DC commutator.',
        '**Transformer:** AC only. Step-up V↑I↓, Step-down V↓I↑. Power grid.',
        '**MPSC Point:** Water specific heat highest, Diamond n=2.42, Sound 343 m/s air, Domestic 220V 50Hz.'
      ],
      english: [
        '**1. Heat & Thermodynamics**',
        '**Temperature:** C/5 = (F-32)/9 = (K-273)/5. Absolute zero -273°C = 0K.',
        '**Expansion:** Linear α, Area β=2α, Volume γ=3α. Bimetallic strip thermostat.',
        '**Specific Heat:** Q = mcΔT. Water 1 cal/g°C = 4200 J/kg°C highest.',
        '**Latent Heat:** Ice melt 80 cal/g, Steam 540 cal/g.',
        '**Transfer:** Conduction solids, Convection fluids, Radiation vacuum. Blackbody best absorber/emitter.',
        '**Laws:** 1st ΔQ = ΔU + ΔW. 2nd Entropy increase. Heat engine efficiency η = 1-T₂/T₁.',
        '',
        '**2. Light**',
        '**Reflection:** ∠i = ∠r. Plane mirror lateral inversion. Concave converging, Convex diverging.',
        '**Mirror Formula:** 1/f = 1/u + 1/v. Magnification m = -v/u = h₂/h₁.',
        '**Refraction:** Snell n₁sin i = n₂sin r. n = c/v. Water 1.33, Glass 1.5, Diamond 2.42.',
        '**Total Internal Reflection:** Dense to rare, i > C. Critical angle. Mirage, Optical fibre, Diamond sparkle.',
        '**Lens:** Convex converging, Concave diverging. Power P = 1/f dioptre. Human eye convex f=2.5cm.',
        '**Defects Eye:** Myopia concave, Hypermetropia convex, Presbyopia bifocal, Astigmatism cylindrical.',
        '**Dispersion:** VIBGYOR. Violet deviate max. Rainbow - refraction+dispersion+TIR.',
        '**Scattering:** Blue sky Rayleigh ∝ 1/λ⁴. Red sun rise/set. Clouds white large particles.',
        '',
        '**3. Sound**',
        '**Wave:** Longitudinal mechanical. Need medium. Speed Air 343 m/s, Water 1480, Steel 5960 m/s.',
        '**Properties:** Pitch ∝ frequency, Loudness ∝ amplitude², Quality harmonics.',
        '**Range:** Infrasonic <20Hz, Audible 20-20,000Hz, Ultrasonic >20kHz. Bat SONAR.',
        '**Echo:** Distance = (v×t)/2. Min 17m. Reverberation multiple reflections.',
        '**Doppler:** Frequency change source/observer motion. Siren pitch change.',
        '',
        '**4. Electricity**',
        '**Current:** I = Q/t ampere. Ohm Law V = IR. Resistance R = ρl/A Ω.',
        '**Combination:** Series R = R₁+R₂, Parallel 1/R = 1/R₁+1/R₂.',
        '**Power:** P = VI = I²R = V²/R watt. Commercial unit kWh. 1 kWh = 3.6×10⁶ J.',
        '**Heating:** H = I²Rt Joule Law. Fuse, Heater, Bulb.',
        '**Domestic:** 220V AC 50Hz India. Live red, Neutral black, Earth green.',
        '',
        '**5. Magnetism**',
        '**Properties:** Attract Fe, Ni, Co. Like repel, Unlike attract. North seeking.',
        '**Earth:** Magnetic South geographic North. Angle Declination, Dip.',
        '**Electromagnet:** Solenoid + Iron core. Electric bell, Crane.',
        '**Motor:** Electrical→Mechanical. Fleming Left Hand Rule.',
        '**Generator:** Mechanical→Electrical. Fleming Right Hand. AC dynamo, DC commutator.',
        '**Transformer:** AC only. Step-up V↑I↓, Step-down V↓I↑. Power grid.',
        '**MPSC Point:** Water specific heat highest, Diamond n=2.42, Sound 343 m/s air, Domestic 220V 50Hz.'
      ]
    }
  },
  {
    id: 'sci-3',
    title: {
      mizo: 'Chapter 3: Chemistry - Matter, Atomic Structure, Bonding',
      english: 'Chapter 3: Chemistry - Matter, Atomic Structure, Bonding'
    },
    notes: {
      mizo: [
        '**1. Matter & Classification**',
        '**States:** Solid fixed shape/volume, Liquid fixed volume, Gas no fixed. Plasma 4th, BEC 5th.',
        '**Change:** Melting, Boiling, Condensation, Freezing, Sublimation solid→gas.',
        '**Pure Substances:** Elements 118. 94 natural. Compounds H₂O, CO₂. Fixed ratio.',
        '**Mixtures:** Homogeneous solution, Heterogeneous suspension. Separation - Distillation, Chromatography, Centrifuge.',
        '',
        '**2. Atomic Structure**',
        '**Dalton:** Atom indivisible. **Thomson:** Plum pudding. Electron e⁻ 1897.',
        '**Rutherford 1911:** Nucleus +ve. α-scattering. Most space empty.',
        '**Bohr 1913:** Orbits fixed energy. n=1,2,3... K,L,M shells. 2n² max electrons.',
        '**Modern:** Proton p⁺ +1, 1u. Neutron n⁰ 0, 1u. Electron -1, 1/1836u. Chadwick 1932 neutron.',
        '**Atomic Number Z:** Protons. **Mass Number A:** p+n. Isotopes same Z diff A C-12,C-14. Isobars same A diff Z Ar-40,Ca-40.',
        '',
        '**3. Periodic Table**',
        '**Mendeleev 1869:** Atomic mass. 63 elements. Gaps Eka-Aluminium Ga.',
        '**Modern Moseley 1913:** Atomic number. 7 Periods rows, 18 Groups columns.',
        '**Trends:** Left→Right Size↓, IE↑, EN↑, Metallic↓. Top→Bottom Size↑, IE↓, EN↓, Metallic↑.',
        '**Blocks:** s-1,2 Alkali/Alkaline, p-13-18, d-3-12 Transition, f-Lanthanides/Actinides.',
        '**Important:** H non-metal, He inert, F most EN, Fr most metallic, C catenation.',
        '',
        '**4. Chemical Bonding**',
        '**Ionic:** Metal + Non-metal. Transfer e⁻. NaCl. High MP, Conduct molten/aq. Electrovalent.',
        '**Covalent:** Non-metal + Non-metal. Share e⁻. H₂O, CH₄. Low MP, Non-conduct. Polar H₂O, Non-polar O₂.',
        '**Metallic:** Metal atoms. Sea electrons. Conduct, Malleable, Ductile.',
        '**Coordinate:** NH₄⁺, O₃. One atom both e⁻.',
        '**Hydrogen Bond:** H-F,O,N. Water high BP. DNA base pair.',
        '',
        '**5. Mole Concept**',
        '**Mole:** 6.022×10²³ Avogadro. 1 mole atoms = Gram atomic mass. 1 mole molecules = Gram molecular mass.',
        '**STP:** 0°C 1 atm. 1 mole gas = 22.4 L. Molarity M = moles/L.',
        '**MPSC Point:** 118 elements, Avogadro 6.022×10²³, 1 mole gas 22.4L STP, F most EN.'
      ],
      english: [
        '**1. Matter & Classification**',
        '**States:** Solid fixed shape/volume, Liquid fixed volume, Gas no fixed. Plasma 4th, BEC 5th.',
        '**Change:** Melting, Boiling, Condensation, Freezing, Sublimation solid→gas.',
        '**Pure Substances:** Elements 118. 94 natural. Compounds H₂O, CO₂. Fixed ratio.',
        '**Mixtures:** Homogeneous solution, Heterogeneous suspension. Separation - Distillation, Chromatography, Centrifuge.',
        '',
        '**2. Atomic Structure**',
        '**Dalton:** Atom indivisible. **Thomson:** Plum pudding. Electron e⁻ 1897.',
        '**Rutherford 1911:** Nucleus +ve. α-scattering. Most space empty.',
        '**Bohr 1913:** Orbits fixed energy. n=1,2,3... K,L,M shells. 2n² max electrons.',
        '**Modern:** Proton p⁺ +1, 1u. Neutron n⁰ 0, 1u. Electron -1, 1/1836u. Chadwick 1932 neutron.',
        '**Atomic Number Z:** Protons. **Mass Number A:** p+n. Isotopes same Z diff A C-12,C-14. Isobars same A diff Z Ar-40,Ca-40.',
        '',
        '**3. Periodic Table**',
        '**Mendeleev 1869:** Atomic mass. 63 elements. Gaps Eka-Aluminium Ga.',
        '**Modern Moseley 1913:** Atomic number. 7 Periods rows, 18 Groups columns.',
        '**Trends:** Left→Right Size↓, IE↑, EN↑, Metallic↓. Top→Bottom Size↑, IE↓, EN↓, Metallic↑.',
        '**Blocks:** s-1,2 Alkali/Alkaline, p-13-18, d-3-12 Transition, f-Lanthanides/Actinides.',
        '**Important:** H non-metal, He inert, F most EN, Fr most metallic, C catenation.',
        '',
        '**4. Chemical Bonding**',
        '**Ionic:** Metal + Non-metal. Transfer e⁻. NaCl. High MP, Conduct molten/aq. Electrovalent.',
        '**Covalent:** Non-metal + Non-metal. Share e⁻. H₂O, CH₄. Low MP, Non-conduct. Polar H₂O, Non-polar O₂.',
        '**Metallic:** Metal atoms. Sea electrons. Conduct, Malleable, Ductile.',
        '**Coordinate:** NH₄⁺, O₃. One atom both e⁻.',
        '**Hydrogen Bond:** H-F,O,N. Water high BP. DNA base pair.',
        '',
        '**5. Mole Concept**',
        '**Mole:** 6.022×10²³ Avogadro. 1 mole atoms = Gram atomic mass. 1 mole molecules = Gram molecular mass.',
        '**STP:** 0°C 1 atm. 1 mole gas = 22.4 L. Molarity M = moles/L.',
        '**MPSC Point:** 118 elements, Avogadro 6.022×10²³, 1 mole gas 22.4L STP, F most EN.'
      ]
    }
  },
  {
    id: 'sci-4',
    title: {
      mizo: 'Chapter 4: Chemistry - Acids, Bases, Salts, Reactions, Metals',
      english: 'Chapter 4: Chemistry - Acids, Bases, Salts, Reactions, Metals'
    },
    notes: {
      mizo: [
        '**1. Acids, Bases, Salts**',
        '**Acids:** Sour, H⁺ produce. Litmus blue→red. pH < 7. HCl, H₂SO₄, HNO₃, CH₃COOH.',
        '**Bases:** Bitter, OH⁻ produce. Litmus red→blue. pH > 7. NaOH, KOH, NH₄OH, Ca(OH)₂.',
        '**pH Scale:** 0-14. 7 neutral. pH = -log[H⁺]. Stomach 1-3, Blood 7.4, Rain 5.6.',
        '**Indicators:** Litmus, Phenolphthalein colorless acid/pink base, Methyl orange red acid/yellow base.',
        '**Neutralisation:** Acid + Base → Salt + Water. HCl + NaOH → NaCl + H₂O. Heat released.',
        '**Salts:** pH - NaCl 7 neutral, Na₂CO₃ >7 basic, NH₄Cl <7 acidic. Washing soda Na₂CO₃·10H₂O, Baking soda NaHCO₃, Bleaching CaOCl₂, Plaster CaSO₄·½H₂O.',
        '',
        '**2. Chemical Reactions**',
        '**Types:** Combination 2H₂+O₂→2H₂O, Decomposition 2H₂O→2H₂+O₂, Displacement Zn+CuSO₄→ZnSO₄+Cu, Double Displacement AgNO₃+NaCl→AgCl+NaNO₃, Redox.',
        '**Oxidation:** Loss e⁻, Gain O, Loss H. **Reduction:** Gain e⁻, Loss O, Gain H. OIL RIG.',
        '**Corrosion:** Fe rusting Fe₂O₃·xH₂O. Prevention galvanisation Zn, painting, alloying.',
        '**Rancidity:** Fat oxidation. Antioxidants BHA, BHT prevent.',
        '',
        '**3. Metals & Non-metals**',
        '**Metals:** Lustrous, Malleable, Ductile, Conduct heat/electric, Sonorous. Na, K soft cut knife. Hg liquid.',
        '**Reactivity Series:** K > Na > Ca > Mg > Al > Zn > Fe > Pb > H > Cu > Hg > Ag > Au > Pt. K most reactive, Pt least.',
        '**Extraction:** Roasting S²⁻, Calcination CO₃²⁻. Reduction C/Al. Electrolysis K-Ca.',
        '**Alloys:** Brass Cu+Zn, Bronze Cu+Sn, Steel Fe+C, Stainless Fe+Cr+Ni, Solder Pb+Sn.',
        '**Non-metals:** Non-lustrous, Brittle, Non-conduct except Graphite. C, S, P, O, N, Halogens.',
        '',
        '**4. Carbon Compounds**',
        '**Catenation:** C-C long chains. Tetravalent 4 bonds. Isomers same formula diff structure.',
        '**Hydrocarbons:** Alkanes CₙH₂ₙ₊₂ single, Alkenes CₙH₂ₙ double, Alkynes CₙH₂ₙ₋₂ triple.',
        '**Functional Groups:** Alcohol -OH, Aldehyde -CHO, Ketone -CO-, Carboxylic -COOH.',
        '**Nomenclature:** Meth 1C, Eth 2C, Prop 3C, But 4C, Pent 5C. CH₄ Methane, C₂H₅OH Ethanol.',
        '**Ethanol:** Fermentation sugar. Intoxicant. CH₃CH₂OH. Oxidation → Ethanoic acid.',
        '**Ethanoic Acid:** Vinegar 5-8%. CH₃COOH. Esterification alcohol→ester fruity smell.',
        '**Soaps:** Na/K salts fatty acids. Cleans Micelle formation. Scum hard water Ca/Mg.',
        '**Detergents:** Sodium salts sulphonic acid. Work hard+soft water. Non-biodegradable pollute.',
        '',
        '**5. Periodic Classification Uses**',
        '**Hydrogen:** Fuel, Ammonia NH₃ Haber, HCl. **Carbon:** Fuel, Steel, Organic. **Nitrogen:** Fertilizer urea, NH₃, Explosives.',
        '**Oxygen:** Respiration, Combustion. **Phosphorus:** Match, Fertilizer. **Sulphur:** H₂SO₄ King Chemicals, Vulcanisation rubber.',
        '**Chlorine:** Bleaching, DDT, PVC, Water purify. **Sodium:** NaCl table salt, NaOH caustic, Na₂CO₃ washing.',
        '**MPSC Point:** pH 7 neutral, Blood 7.4, King H₂SO₄, Washing Na₂CO₃·10H₂O, Baking NaHCO₃.'
      ],
      english: [
        '**1. Acids, Bases, Salts**',
        '**Acids:** Sour, H⁺ produce. Litmus blue→red. pH < 7. HCl, H₂SO₄, HNO₃, CH₃COOH.',
        '**Bases:** Bitter, OH⁻ produce. Litmus red→blue. pH > 7. NaOH, KOH, NH₄OH, Ca(OH)₂.',
        '**pH Scale:** 0-14. 7 neutral. pH = -log[H⁺]. Stomach 1-3, Blood 7.4, Rain 5.6.',
        '**Indicators:** Litmus, Phenolphthalein colorless acid/pink base, Methyl orange red acid/yellow base.',
        '**Neutralisation:** Acid + Base → Salt + Water. HCl + NaOH → NaCl + H₂O. Heat released.',
        '**Salts:** pH - NaCl 7 neutral, Na₂CO₃ >7 basic, NH₄Cl <7 acidic. Washing soda Na₂CO₃·10H₂O, Baking soda NaHCO₃, Bleaching CaOCl₂, Plaster CaSO₄·½H₂O.',
        '',
        '**2. Chemical Reactions**',
        '**Types:** Combination 2H₂+O₂→2H₂O, Decomposition 2H₂O→2H₂+O₂, Displacement Zn+CuSO₄→ZnSO₄+Cu, Double Displacement AgNO₃+NaCl→AgCl+NaNO₃, Redox.',
        '**Oxidation:** Loss e⁻, Gain O, Loss H. **Reduction:** Gain e⁻, Loss O, Gain H. OIL RIG.',
        '**Corrosion:** Fe rusting Fe₂O₃·xH₂O. Prevention galvanisation Zn, painting, alloying.',
        '**Rancidity:** Fat oxidation. Antioxidants BHA, BHT prevent.',
        '',
        '**3. Metals & Non-metals**',
        '**Metals:** Lustrous, Malleable, Ductile, Conduct heat/electric, Sonorous. Na, K soft cut knife. Hg liquid.',
        '**Reactivity Series:** K > Na > Ca > Mg > Al > Zn > Fe > Pb > H > Cu > Hg > Ag > Au > Pt. K most reactive, Pt least.',
        '**Extraction:** Roasting S²⁻, Calcination CO₃²⁻. Reduction C/Al. Electrolysis K-Ca.',
        '**Alloys:** Brass Cu+Zn, Bronze Cu+Sn, Steel Fe+C, Stainless Fe+Cr+Ni, Solder Pb+Sn.',
        '**Non-metals:** Non-lustrous, Brittle, Non-conduct except Graphite. C, S, P, O, N, Halogens.',
        '',
        '**4. Carbon Compounds**',
        '**Catenation:** C-C long chains. Tetravalent 4 bonds. Isomers same formula diff structure.',
        '**Hydrocarbons:** Alkanes CₙH₂ₙ₊₂ single, Alkenes CₙH₂ₙ double, Alkynes CₙH₂ₙ₋₂ triple.',
        '**Functional Groups:** Alcohol -OH, Aldehyde -CHO, Ketone -CO-, Carboxylic -COOH.',
        '**Nomenclature:** Meth 1C, Eth 2C, Prop 3C, But 4C, Pent 5C. CH₄ Methane, C₂H₅OH Ethanol.',
        '**Ethanol:** Fermentation sugar. Intoxicant. CH₃CH₂OH. Oxidation → Ethanoic acid.',
        '**Ethanoic Acid:** Vinegar 5-8%. CH₃COOH. Esterification alcohol→ester fruity smell.',
        '**Soaps:** Na/K salts fatty acids. Cleans Micelle formation. Scum hard water Ca/Mg.',
        '**Detergents:** Sodium salts sulphonic acid. Work hard+soft water. Non-biodegradable pollute.',
        '',
        '**5. Periodic Classification Uses**',
        '**Hydrogen:** Fuel, Ammonia NH₃ Haber, HCl. **Carbon:** Fuel, Steel, Organic. **Nitrogen:** Fertilizer urea, NH₃, Explosives.',
        '**Oxygen:** Respiration, Combustion. **Phosphorus:** Match, Fertilizer. **Sulphur:** H₂SO₄ King Chemicals, Vulcanisation rubber.',
        '**Chlorine:** Bleaching, DDT, PVC, Water purify. **Sodium:** NaCl table salt, NaOH caustic, Na₂CO₃ washing.',
        '**MPSC Point:** pH 7 neutral, Blood 7.4, King H₂SO₄, Washing Na₂CO₃·10H₂O, Baking NaHCO₃.'
      ]
    }
  },
  {
    id: 'sci-5',
    title: {
      mizo: 'Chapter 5: Biology - Cell, Tissues, Life Processes',
      english: 'Chapter 5: Biology - Cell, Tissues, Life Processes'
    },
    notes: {
      mizo: [
        '**1. Cell - Life Unit**',
        '**Discovery:** Robert Hooke 1665 cork. Cell Theory Schleiden & Schwann 1838-39.',
        '**Prokaryote:** No nucleus. Bacteria. **Eukaryote:** Nucleus. Plant, Animal.',
        '**Plant Cell:** Cell wall cellulose, Chloroplast, Large vacuole. **Animal:** No wall, No chloroplast, Small vacuole.',
        '**Organelles:** Nucleus brain DNA, Mitochondria powerhouse ATP, Ribosome protein 70S/80S, ER transport, Golgi packaging, Lysosome suicide bag, Chloroplast photosynthesis.',
        '**Division:** Mitosis 2n→2n growth, Meiosis 2n→n gametes. 4 stages PMAT.',
        '',
        '**2. Tissues**',
        '**Plant:** Meristematic dividing, Permanent - Parenchyma storage, Collenchyma flexible, Sclerenchyma hard. Complex Xylem water↑, Phloem food↓.',
        '**Animal:** Epithelial cover, Connective blood/bone/cartilage, Muscular striated/unstriated/cardiac, Nervous neuron.',
        '**Blood:** RBC no nucleus O₂ carry Hb, WBC immunity, Platelets clot. Plasma 55%.',
        '',
        '**3. Life Processes**',
        '**Nutrition:** Autotrophic plants 6CO₂+6H₂O→C₆H₁₂O₆+6O₂ chlorophyll. Heterotrophic - Holozoic man, Saprophytic fungi, Parasitic cuscuta.',
        '**Human Digestive:** Mouth amylase, Stomach HCl+pepsin protein, Small intestine bile+pancreatic juice+intestinal, Villi absorb. Large intestine water absorb.',
        '**Respiration:** C₆H₁₂O₆+6O₂→6CO₂+6H₂O+38ATP. Glycolysis cytoplasm, Krebs mitochondria, ETC 34 ATP. Anaerobic yeast 2 ATP.',
        '**Human Respiratory:** Nose→Trachea→Bronchi→Alveoli. Hb O₂ oxyhaemoglobin. CO₂ bicarbonates.',
        '**Circulation:** Heart 4 chambered. Double circulation. Artery away heart, Vein to heart. Pulmonary, Systemic. BP 120/80 mmHg. SA node pacemaker.',
        '**Excretion:** Kidney nephron unit. Filtration→Reabsorption→Secretion. Urine urea. Dialysis artificial. Plants - stomata, bark.',
        '',
        '**4. Control & Coordination**',
        '**Nervous:** Neuron Dendrite→Cell body→Axon. Synapse. CNS Brain+Spinal cord, PNS nerves. Reflex arc.',
        '**Brain:** Cerebrum thought, Cerebellum balance, Medulla involuntary. Meninges cover, CSF shock.',
        '**Endocrine:** Pituitary master GH, Thyroid T₃T₄ thyroxine iodine, Pancreas insulin glucagon diabetes, Adrenal adrenaline, Testes testosterone, Ovaries estrogen progesterone.',
        '**Plants:** Tropism - Photo light, Geo gravity, Hydro water, Thigmo touch. Hormones Auxin, Gibberellin, Cytokinin, ABA.',
        '**MPSC Point:** Mitochondria powerhouse, RBC no nucleus, Double circulation, Nephron unit, Pituitary master, Insulin diabetes.'
      ],
      english: [
        '**1. Cell - Life Unit**',
        '**Discovery:** Robert Hooke 1665 cork. Cell Theory Schleiden & Schwann 1838-39.',
        '**Prokaryote:** No nucleus. Bacteria. **Eukaryote:** Nucleus. Plant, Animal.',
        '**Plant Cell:** Cell wall cellulose, Chloroplast, Large vacuole. **Animal:** No wall, No chloroplast, Small vacuole.',
        '**Organelles:** Nucleus brain DNA, Mitochondria powerhouse ATP, Ribosome protein 70S/80S, ER transport, Golgi packaging, Lysosome suicide bag, Chloroplast photosynthesis.',
        '**Division:** Mitosis 2n→2n growth, Meiosis 2n→n gametes. 4 stages PMAT.',
        '',
        '**2. Tissues**',
        '**Plant:** Meristematic dividing, Permanent - Parenchyma storage, Collenchyma flexible, Sclerenchyma hard. Complex Xylem water↑, Phloem food↓.',
        '**Animal:** Epithelial cover, Connective blood/bone/cartilage, Muscular striated/unstriated/cardiac, Nervous neuron.',
        '**Blood:** RBC no nucleus O₂ carry Hb, WBC immunity, Platelets clot. Plasma 55%.',
        '',
        '**3. Life Processes**',
        '**Nutrition:** Autotrophic plants 6CO₂+6H₂O→C₆H₁₂O₆+6O₂ chlorophyll. Heterotrophic - Holozoic man, Saprophytic fungi, Parasitic cuscuta.',
        '**Human Digestive:** Mouth amylase, Stomach HCl+pepsin protein, Small intestine bile+pancreatic juice+intestinal, Villi absorb. Large intestine water absorb.',
        '**Respiration:** C₆H₁₂O₆+6O₂→6CO₂+6H₂O+38ATP. Glycolysis cytoplasm, Krebs mitochondria, ETC 34 ATP. Anaerobic yeast 2 ATP.',
        '**Human Respiratory:** Nose→Trachea→Bronchi→Alveoli. Hb O₂ oxyhaemoglobin. CO₂ bicarbonates.',
        '**Circulation:** Heart 4 chambered. Double circulation. Artery away heart, Vein to heart. Pulmonary, Systemic. BP 120/80 mmHg. SA node pacemaker.',
        '**Excretion:** Kidney nephron unit. Filtration→Reabsorption→Secretion. Urine urea. Dialysis artificial. Plants - stomata, bark.',
        '',
                '**4. Control & Coordination**',
        '**Nervous:** Neuron Dendrite→Cell body→Axon. Synapse. CNS Brain+Spinal cord, PNS nerves. Reflex arc.',
        '**Brain:** Cerebrum thought, Cerebellum balance, Medulla involuntary. Meninges cover, CSF shock.',
        '**Endocrine:** Pituitary master GH, Thyroid T₃T₄ thyroxine iodine, Pancreas insulin glucagon diabetes, Adrenal adrenaline, Testes testosterone, Ovaries estrogen progesterone.',
        '**Plants:** Tropism - Photo light, Geo gravity, Hydro water, Thigmo touch. Hormones Auxin, Gibberellin, Cytokinin, ABA.',
        '**MPSC Point:** Mitochondria powerhouse, RBC no nucleus, Double circulation, Nephron unit, Pituitary master, Insulin diabetes.'
      ],
    }
  },
  {
    id: 'sci-6',
    title: {
      mizo: 'Chapter 6: Biology - Reproduction, Heredity, Evolution',
      english: 'Chapter 6: Biology - Reproduction, Heredity, Evolution'
    },
    notes: {
      mizo: [
        '**1. Reproduction**',
        '**Asexual:** Single parent. Fission Amoeba, Budding Hydra, Fragmentation Spirogyra, Spore Rhizopus, Vegetative Potato eye, Bryophyllum leaf.',
        '**Sexual Flower:** Stamen anther pollen male, Carpel stigma+style+ovary female. Pollination - Self, Cross wind/insect/water. Fertilization pollen tube ovule→zygote→embryo. Ovary→fruit, Ovule→seed. Double fertilization - 1 male+egg→zygote, 1 male+2polar→endosperm 3n.',
        '**Human Male:** Testes sperm + testosterone, Vas deferens, Seminal vesicle, Prostate, Penis.',
        '**Human Female:** Ovaries egg + estrogen, Oviduct fertilization site, Uterus implantation, Vagina. Menstruation 28 days. Ovulation 14th day.',
        '**Fertilization:** Sperm+Ovum→Zygote fallopian tube. Implantation uterus wall. Placenta exchange. Gestation 280 days 9 months.',
        '**Contraception:** Barrier condom, Chemical pills, IUCD Copper-T, Surgical vasectomy/tubectomy.',
        '',
        '**2. Heredity**',
        '**Mendel 1865:** Father Genetics. Pea plant 7 traits. 3 Laws:',
        '   1. **Dominance:** TT × tt → F₁ all Tt tall. T dominant.',
        '   2. **Segregation:** Tt → T,t gametes. Alleles separate.',
        '   3. **Independent Assortment:** Dihybrid RRYY × rryy. Genes separate.',
        '**Monohybrid Ratio:** F₂ 3:1 phenotype, 1:2:1 genotype. **Dihybrid:** 9:3:3:1.',
        '**DNA:** Double helix Watson-Crick 1953. A=T, G≡C. Gene segment DNA. Chromosomes 23 pairs human. 22 Autosomes, 1 Sex XY male, XX female.',
        '**Sex Determination:** Male XY sperm X or Y. Female XX egg X only. Father determines.',
        '**Variation:** Sexual reproduction, Mutation. Acquired not inherit.',
        '',
        '**3. Evolution**',
        '**Evidences:** Fossils Archaeopteryx reptile-bird, Homologous same origin diff function forelimb, Analogous diff origin same function wing, Vestigial appendix.',
        '**Theories:** Lamarck Inheritance acquired, Darwin Natural Selection 1859 Origin Species, Survival fittest.',
        '**Human Evolution:** Dryopithecus, Ramapithecus, Australopithecus, Homo habilis tool, Homo erectus fire, Neanderthal, Homo sapiens 300,000 yrs.',
        '**MPSC Point:** Mendel laws, DNA double helix, 23 pairs chromosomes, Sex father determine, Archaeopteryx link.'
      ],
      english: [
        '**1. Reproduction**',
        '**Asexual:** Single parent. Fission Amoeba, Budding Hydra, Fragmentation Spirogyra, Spore Rhizopus, Vegetative Potato eye, Bryophyllum leaf.',
        '**Sexual Flower:** Stamen anther pollen male, Carpel stigma+style+ovary female. Pollination - Self, Cross wind/insect/water. Fertilization pollen tube ovule→zygote→embryo. Ovary→fruit, Ovule→seed. Double fertilization - 1 male+egg→zygote, 1 male+2polar→endosperm 3n.',
        '**Human Male:** Testes sperm + testosterone, Vas deferens, Seminal vesicle, Prostate, Penis.',
        '**Human Female:** Ovaries egg + estrogen, Oviduct fertilization site, Uterus implantation, Vagina. Menstruation 28 days. Ovulation 14th day.',
        '**Fertilization:** Sperm+Ovum→Zygote fallopian tube. Implantation uterus wall. Placenta exchange. Gestation 280 days 9 months.',
        '**Contraception:** Barrier condom, Chemical pills, IUCD Copper-T, Surgical vasectomy/tubectomy.',
        '',
        '**2. Heredity**',
        '**Mendel 1865:** Father Genetics. Pea plant 7 traits. 3 Laws:',
        '   1. **Dominance:** TT × tt → F₁ all Tt tall. T dominant.',
        '   2. **Segregation:** Tt → T,t gametes. Alleles separate.',
        '   3. **Independent Assortment:** Dihybrid RRYY × rryy. Genes separate.',
        '**Monohybrid Ratio:** F₂ 3:1 phenotype, 1:2:1 genotype. **Dihybrid:** 9:3:3:1.',
        '**DNA:** Double helix Watson-Crick 1953. A=T, G≡C. Gene segment DNA. Chromosomes 23 pairs human. 22 Autosomes, 1 Sex XY male, XX female.',
        '**Sex Determination:** Male XY sperm X or Y. Female XX egg X only. Father determines.',
        '**Variation:** Sexual reproduction, Mutation. Acquired not inherit.',
        '',
        '**3. Evolution**',
        '**Evidences:** Fossils Archaeopteryx reptile-bird, Homologous same origin diff function forelimb, Analogous diff origin same function wing, Vestigial appendix.',
        '**Theories:** Lamarck Inheritance acquired, Darwin Natural Selection 1859 Origin Species, Survival fittest.',
        '**Human Evolution:** Dryopithecus, Ramapithecus, Australopithecus, Homo habilis tool, Homo erectus fire, Neanderthal, Homo sapiens 300,000 yrs.',
        '**MPSC Point:** Mendel laws, DNA double helix, 23 pairs chromosomes, Sex father determine, Archaeopteryx link.'
      ]
    }
  },
    {
    id: 'sci-7',
    title: {
      mizo: 'Chapter 7: Environment & Ecology',
      english: 'Chapter 7: Environment & Ecology'
    },
    notes: {
      mizo: [
        '**1. Ecosystem**',
        '**Components:** Biotic - Producers plants, Consumers herbivore/carnivore, Decomposers bacteria/fungi. Abiotic - Air, Water, Soil, Light.',
        '**Food Chain:** Grass→Deer→Tiger. Trophic levels. 10% Law - 90% energy lost each level.',
        '**Food Web:** Interconnected chains. **Pyramid:** Number, Biomass, Energy upright. Pyramid number tree inverted.',
        '**Biogeochemical:** Water cycle, Carbon cycle, Nitrogen cycle Rhizobium fix, Phosphorus cycle.',
        '',
        '**2. Environmental Issues**',
        '**Pollution:** Air SO₂,NO₂,CO, PM2.5, O₃. Taj Mahal acid rain. Water BOD, Eutrophication. Soil pesticides. Noise >85dB harmful.',
        '**Ozone:** O₃ stratosphere UV absorb. CFCs destroy. Ozone hole Antarctica. Montreal Protocol 1987.',
        '**Global Warming:** Greenhouse CO₂, CH₄, N₂O, CFC. Sea level rise, Climate change. Kyoto 1997, Paris 2015 1.5°C.',
        '**Waste:** Biodegradable compost, Non-biodegradable plastic. 3R Reduce Reuse Recycle. Vermicompost earthworm.',
        '',
        '**3. Biodiversity**',
        '**Levels:** Genetic, Species, Ecosystem. Hotspots 36 world. India 4 - Himalaya, Indo-Burma, Western Ghats, Sundaland.',
        '**Loss:** Habitat, Hunting, Alien species, Co-extinction. IUCN Red List - Extinct, Endangered, Vulnerable.',
        '**Conservation:** In-situ National Park, Sanctuary, Biosphere Reserve. Ex-situ Zoo, Botanical, Gene bank.',
        '**India:** 106 National Parks, 573 Sanctuaries, 18 Biosphere Reserves. Project Tiger 1973, Elephant 1992.',
        '**Mizoram:** Dampa Tiger Reserve, Murlen NP, Phawngpui NP, Ngengpui Sanctuary. 84.5% forest.',
        '',
        '**4. Natural Resources**',
        '**Forest:** 21.7% India. Chipko 1973, Appiko 1983. Joint Forest Management.',
        '**Water:** 2.5% fresh. Rainwater harvesting, Watershed management. Ganga Action Plan 1985.',
        '**Energy:** Renewable Solar, Wind, Hydro, Biomass, Geothermal. Non-renewable Coal, Oil, Gas. Nuclear U-235.',
        '**Sustainable:** Brundtland 1987 - meet present without compromising future. 5R Refuse, Reduce, Reuse, Repurpose, Recycle.',
        '**MPSC Point:** 10% Law, Ozone CFC, Paris 1.5°C, IUCN Red List, Project Tiger 1973, Mizoram 84.5% forest.'
      ],
      english: [
        '**1. Ecosystem**',
        '**Components:** Biotic - Producers plants, Consumers herbivore/carnivore, Decomposers bacteria/fungi. Abiotic - Air, Water, Soil, Light.',
        '**Food Chain:** Grass→Deer→Tiger. Trophic levels. 10% Law - 90% energy lost each level.',
        '**Food Web:** Interconnected chains. **Pyramid:** Number, Biomass, Energy upright. Pyramid number tree inverted.',
        '**Biogeochemical:** Water cycle, Carbon cycle, Nitrogen cycle Rhizobium fix, Phosphorus cycle.',
        '',
        '**2. Environmental Issues**',
        '**Pollution:** Air SO₂,NO₂,CO, PM2.5, O₃. Taj Mahal acid rain. Water BOD, Eutrophication. Soil pesticides. Noise >85dB harmful.',
        '**Ozone:** O₃ stratosphere UV absorb. CFCs destroy. Ozone hole Antarctica. Montreal Protocol 1987.',
        '**Global Warming:** Greenhouse CO₂, CH₄, N₂O, CFC. Sea level rise, Climate change. Kyoto 1997, Paris 2015 1.5°C.',
        '**Waste:** Biodegradable compost, Non-biodegradable plastic. 3R Reduce Reuse Recycle. Vermicompost earthworm.',
        '',
        '**3. Biodiversity**',
        '**Levels:** Genetic, Species, Ecosystem. Hotspots 36 world. India 4 - Himalaya, Indo-Burma, Western Ghats, Sundaland.',
        '**Loss:** Habitat, Hunting, Alien species, Co-extinction. IUCN Red List - Extinct, Endangered, Vulnerable.',
        '**Conservation:** In-situ National Park, Sanctuary, Biosphere Reserve. Ex-situ Zoo, Botanical, Gene bank.',
        '**India:** 106 National Parks, 573 Sanctuaries, 18 Biosphere Reserves. Project Tiger 1973, Elephant 1992.',
        '**Mizoram:** Dampa Tiger Reserve, Murlen NP, Phawngpui NP, Ngengpui Sanctuary. 84.5% forest.',
        '',
        '**4. Natural Resources**',
        '**Forest:** 21.7% India. Chipko 1973, Appiko 1983. Joint Forest Management.',
        '**Water:** 2.5% fresh. Rainwater harvesting, Watershed management. Ganga Action Plan 1985.',
        '**Energy:** Renewable Solar, Wind, Hydro, Biomass, Geothermal. Non-renewable Coal, Oil, Gas. Nuclear U-235.',
        '**Sustainable:** Brundtland 1987 - meet present without compromising future. 5R Refuse, Reduce, Reuse, Repurpose, Recycle.',
        '**MPSC Point:** 10% Law, Ozone CFC, Paris 1.5°C, IUCN Red List, Project Tiger 1973, Mizoram 84.5% forest.'
      ]
    }
  },
  {
    id: 'sci-8',
    title: {
      mizo: 'Chapter 8: Science & Technology India',
      english: 'Chapter 8: Science & Technology India'
    },
    notes: {
      mizo: [
        '**1. Space ISRO**',
        '**History:** INCOSPAR 1962. ISRO 1969 Vikram Sarabhai. 1st satellite Aryabhata 1975.',
        '**Launch Vehicles:** SLV 1980, ASLV, PSLV Polar 1994 workhorse, GSLV Geo 2001 cryogenic, LVM3 2014.',
        '**Satellites:** INSAT communication, IRS remote sensing, IRNSS/NavIC navigation 7 sats, GSAT.',
        '**Missions:** Chandrayaan-1 2008 Moon water, Mangalyaan 2014 Mars 1st attempt success, Chandrayaan-3 2023 South Pole landing Vikram+Pragyan, Aditya-L1 2023 Sun L1, Gaganyaan 2025 manned.',
        '**Centres:** VSSC Thiruvananthapuram, SDSC Sriharikota, SAC Ahmedabad, ISTRAC Bengaluru.',
        '',
        '**2. Defence DRDO**',
        '**Missiles:** Prithvi 350km, Agni I-V 700-5000km ICBM, BrahMos supersonic cruise 290km India-Russia, Akash SAM, Nag anti-tank, Astra air-air.',
        '**Nuclear:** Pokhran-I 1974 Smiling Buddha, Pokhran-II 1998 Shakti. No First Use. Triad - Land Agni, Air, Sea Arihant submarine.',
        '**Aircraft:** Tejas LCA, AMCA 5th gen, UAV Rustom. **Tank:** Arjun MBT. **Ships:** INS Vikrant 2022 1st indigenous carrier, Arihant nuclear sub.',
        '',
        '**3. Nuclear Energy**',
        '**DAE 1954:** Homi Bhabha. 3-stage - 1. PHWR Natural U, 2. FBR Pu+U-238→Pu, 3. Thorium U-233. India Thorium 25% world.',
        '**Plants:** Tarapur 1969 1st, Rawatbhata, Kaiga, Kudankulam Russia VVER. Total 22 reactors 6780 MW.',
        '**Research:** BARC Mumbai, IGCAR Kalpakkam, VECC Kolkata. Apsara 1956 1st reactor Asia.',
        '',
        '**4. Biotechnology & IT**',
        '**Biotech:** Bt Cotton 2002, Golden Rice Vit A, Insulin recombinant, PCR, DNA fingerprinting, Gene therapy, Cloning Dolly 1996.',
        '**COVID:** Covaxin Bharat Biotech, Covishield Serum. mRNA vaccine.',
        '**IT:** PARAM 8000 1991 1st supercomputer, PARAM Siddhi-AI 2020. Digital India 2015, UPI, Aadhaar 12-digit.',
        '**AI:** AIRAWAT AI supercomputer. National AI Mission.',
        '',
        '**5. Important Discoveries India**',
        '**C.V. Raman 1930 Nobel:** Raman Effect scattering. 28 Feb National Science Day.',
        '**Hargobind Khorana 1968:** Genetic code. **S. Chandrasekhar 1983:** Chandrasekhar Limit 1.4 solar mass black hole.',
        '**Venkatraman Ramakrishnan 2009:** Ribosome structure. **APJ Abdul Kalam:** Missile Man, Pokhran-II, President 2002-07.',
        '**MPSC Point:** ISRO 1969, Aryabhata 1975, Mangalyaan 2014, Chandrayaan-3 2023 South Pole, BrahMos 290km, Pokhran 1974/1998, Raman Effect 28 Feb.'
      ],
      english: [
        '**1. Space ISRO**',
        '**History:** INCOSPAR 1962. ISRO 1969 Vikram Sarabhai. 1st satellite Aryabhata 1975.',
        '**Launch Vehicles:** SLV 1980, ASLV, PSLV Polar 1994 workhorse, GSLV Geo 2001 cryogenic, LVM3 2014.',
        '**Satellites:** INSAT communication, IRS remote sensing, IRNSS/NavIC navigation 7 sats, GSAT.',
        '**Missions:** Chandrayaan-1 2008 Moon water, Mangalyaan 2014 Mars 1st attempt success, Chandrayaan-3 2023 South Pole landing Vikram+Pragyan, Aditya-L1 2023 Sun L1, Gaganyaan 2025 manned.',
        '**Centres:** VSSC Thiruvananthapuram, SDSC Sriharikota, SAC Ahmedabad, ISTRAC Bengaluru.',
        '',
        '**2. Defence DRDO**',
        '**Missiles:** Prithvi 350km, Agni I-V 700-5000km ICBM, BrahMos supersonic cruise 290km India-Russia, Akash SAM, Nag anti-tank, Astra air-air.',
        '**Nuclear:** Pokhran-I 1974 Smiling Buddha, Pokhran-II 1998 Shakti. No First Use. Triad - Land Agni, Air, Sea Arihant submarine.',
        '**Aircraft:** Tejas LCA, AMCA 5th gen, UAV Rustom. **Tank:** Arjun MBT. **Ships:** INS Vikrant 2022 1st indigenous carrier, Arihant nuclear sub.',
        '',
        '**3. Nuclear Energy**',
        '**DAE 1954:** Homi Bhabha. 3-stage - 1. PHWR Natural U, 2. FBR Pu+U-238→Pu, 3. Thorium U-233. India Thorium 25% world.',
        '**Plants:** Tarapur 1969 1st, Rawatbhata, Kaiga, Kudankulam Russia VVER. Total 22 reactors 6780 MW.',
        '**Research:** BARC Mumbai, IGCAR Kalpakkam, VECC Kolkata. Apsara 1956 1st reactor Asia.',
        '',
        '**4. Biotechnology & IT**',
        '**Biotech:** Bt Cotton 2002, Golden Rice Vit A, Insulin recombinant, PCR, DNA fingerprinting, Gene therapy, Cloning Dolly 1996.',
        '**COVID:** Covaxin Bharat Biotech, Covishield Serum. mRNA vaccine.',
        '**IT:** PARAM 8000 1991 1st supercomputer, PARAM Siddhi-AI 2020. Digital India 2015, UPI, Aadhaar 12-digit.',
        '**AI:** AIRAWAT AI supercomputer. National AI Mission.',
        '',
        '**5. Important Discoveries India**',
        '**C.V. Raman 1930 Nobel:** Raman Effect scattering. 28 Feb National Science Day.',
        '**Hargobind Khorana 1968:** Genetic code. **S. Chandrasekhar 1983:** Chandrasekhar Limit 1.4 solar mass black hole.',
        '**Venkatraman Ramakrishnan 2009:** Ribosome structure. **APJ Abdul Kalam:** Missile Man, Pokhran-II, President 2002-07.',
        '**MPSC Point:** ISRO 1969, Aryabhata 1975, Mangalyaan 2014, Chandrayaan-3 2023 South Pole, BrahMos 290km, Pokhran 1974/1998, Raman Effect 28 Feb.'
      ]
    }
  }
]

export default function SciencePage() {
  return (
    <SubjectPage 
      subjectName={{
        mizo: 'General Science',
        english: 'General Science'
      }}
      chapters={scienceChapters}
      slug="general-science"
      testId="general-science-test"
      backLink="/"
      testLink="/general-science/test"
      testTitle="General Science Mock Test"
      testDesc="MPSC General Science Chapter 1-8 atanga zawhna 50"
    />
  )
}