'use client'
import SubjectPage from '../components/SubjectPage'

const englishChapters = [
  {
    id: 'eng-1',
    title: {
      mizo: 'Grammar: Tenses',
      english: 'Grammar: Tenses'
    },
    notes: {
      mizo: [
        '**1. Present Tense**',
        '**Simple Present:** Habit, Universal truth. S + V1(s/es)',
        'Entir: He plays football. / The sun rises in the east.',
        '**Present Continuous:** Tunah thleng mek. S + is/am/are + V-ing',
        'Entir: She is reading now.',
        '**Present Perfect:** Zo tawh, effect la awm. S + has/have + V3',
        'Entir: I have finished my work.',
        '**Present Perfect Continuous:** Tun thleng la thleng. S + has/have been + V-ing',
        'Entir: He has been working since morning.',
        '',
        '**2. Past Tense**',
        '**Simple Past:** Hun kal tawh. S + V2',
        'Entir: They went to Delhi yesterday.',
        '**Past Continuous:** A kal lai. S + was/were + V-ing',
        'Entir: I was sleeping when you called.',
        '**Past Perfect:** A dang hmaa zo. S + had + V3',
        'Entir: She had left before I arrived.',
        '',
        '**3. Future Tense**',
        '**Simple Future:** S + will/shall + V1',
        'Entir: We will meet tomorrow.',
        '**Future Continuous:** S + will be + V-ing',
        'Entir: He will be studying at 8 PM.',
        '**Future Perfect:** Hun bikah zo ang. S + will have + V3',
        'Entir: I will have completed by 2027.',
        '',
        '**MPSC Trick:** Since = Perfect Continuous. For = Duration. Yesterday = Simple Past.'
      ],
      english: [
        '**1. Present Tense**',
        '**Simple Present:** Habit, Universal truth. S + V1(s/es)',
        'Ex: He plays football. / The sun rises in the east.',
        '**Present Continuous:** Happening now. S + is/am/are + V-ing',
        'Ex: She is reading now.',
        '**Present Perfect:** Completed with present effect. S + has/have + V3',
        'Ex: I have finished my work.',
        '**Present Perfect Continuous:** Started past, still continuing. S + has/have been + V-ing',
        'Ex: He has been working since morning.',
        '',
        '**2. Past Tense**',
        '**Simple Past:** Completed past. S + V2',
        'Ex: They went to Delhi yesterday.',
        '**Past Continuous:** Ongoing in past. S + was/were + V-ing',
        'Ex: I was sleeping when you called.',
        '**Past Perfect:** Completed before another past action. S + had + V3',
        'Ex: She had left before I arrived.',
        '',
        '**3. Future Tense**',
        '**Simple Future:** S + will/shall + V1',
        'Ex: We will meet tomorrow.',
        '**Future Continuous:** S + will be + V-ing',
        'Ex: He will be studying at 8 PM.',
        '**Future Perfect:** Completed by specific future time. S + will have + V3',
        'Ex: I will have completed by 2027.',
        '',
        '**MPSC Trick:** Since = Perfect Continuous. For = Duration. Yesterday = Simple Past.'
      ]
    }
  },
  {
    id: 'eng-2',
    title: {
      mizo: 'Parts of Speech',
      english: 'Parts of Speech'
    },
    notes: {
      mizo: [
        '**1. Noun - Hming**',
        '**Proper Noun:** Aizawl, India, John - hming bik. Capital letter.',
        '**Common Noun:** city, country, boy - hming tlangpui.',
        '**Collective Noun:** team, committee, jury - pawl.',
        '**Abstract Noun:** honesty, beauty - khawih theih loh.',
        'Entir: **Honesty** is the best policy.',
        '',
        '**2. Pronoun - Hming aiawh**',
        '**Personal:** I, you, he, she, it, we, they',
        '**Possessive:** mine, yours, his, hers, ours, theirs',
        '**Reflexive:** myself, yourself, himself',
        '**Relative:** who, which, that, whom, whose',
        'Entir: This is the boy **who** won the prize.',
        '',
        '**3. Verb - Thil tih**',
        '**Transitive:** Object nei. Ex: He **kicked** the ball.',
        '**Intransitive:** Object nei lo. Ex: She **sleeps**.',
        '**Auxiliary:** is, am, are, was, were, has, have, will',
        '**Modal:** can, could, may, might, shall, should, will, would, must',
        '',
        '**4. Adjective - Hming sawifiah**',
        'Quality: good, bad, beautiful',
        'Quantity: some, many, few',
        'Number: one, first, second',
        'Demonstrative: this, that, these, those',
        'Entir: She is a **beautiful** girl.',
        '',
        '**5. Adverb - Thil tih sawifiah**',
        'Manner: slowly, fast, well - engtin',
        'Place: here, there, everywhere - khawiah',
        'Time: now, then, yesterday - engtikah',
        'Frequency: always, often, never - engzat',
        'Entir: He runs **quickly**.',
        '',
        '**6. Preposition - Inkungkaihna**',
        'Time: at 5 PM, on Monday, in 2026',
        'Place: at the station, on the table, in the room',
        'Direction: to, into, towards, from',
        'Entir: The book is **on** the table.',
        '',
        '**7. Conjunction - Thu zawm**',
        'Coordinating: and, but, or, nor, for, yet, so',
        'Subordinating: because, although, if, when, while',
        'Entir: I was tired **but** I continued working.',
        '',
        '**8. Interjection - Au thut**',
        'Alas!, Hurrah!, Oh!, Wow!',
        'Entir: **Wow!** What a beautiful view!'
      ],
      english: [
        '**1. Noun**',
        '**Proper Noun:** Aizawl, India, John - specific name. Capital letter.',
        '**Common Noun:** city, country, boy - general name.',
        '**Collective Noun:** team, committee, jury - group.',
        '**Abstract Noun:** honesty, beauty - cannot touch.',
        'Ex: **Honesty** is the best policy.',
        '',
        '**2. Pronoun**',
        '**Personal:** I, you, he, she, it, we, they',
        '**Possessive:** mine, yours, his, hers, ours, theirs',
        '**Reflexive:** myself, yourself, himself',
        '**Relative:** who, which, that, whom, whose',
        'Ex: This is the boy **who** won the prize.',
        '',
        '**3. Verb**',
        '**Transitive:** Has object. Ex: He **kicked** the ball.',
        '**Intransitive:** No object. Ex: She **sleeps**.',
        '**Auxiliary:** is, am, are, was, were, has, have, will',
        '**Modal:** can, could, may, might, shall, should, will, would, must',
        '',
        '**4. Adjective**',
        'Quality: good, bad, beautiful',
        'Quantity: some, many, few',
        'Number: one, first, second',
        'Demonstrative: this, that, these, those',
        'Ex: She is a **beautiful** girl.',
        '',
        '**5. Adverb**',
        'Manner: slowly, fast, well - how',
        'Place: here, there, everywhere - where',
        'Time: now, then, yesterday - when',
        'Frequency: always, often, never - how often',
        'Ex: He runs **quickly**.',
        '',
        '**6. Preposition**',
        'Time: at 5 PM, on Monday, in 2026',
        'Place: at the station, on the table, in the room',
        'Direction: to, into, towards, from',
        'Ex: The book is **on** the table.',
        '',
        '**7. Conjunction**',
        'Coordinating: and, but, or, nor, for, yet, so',
        'Subordinating: because, although, if, when, while',
        'Ex: I was tired **but** I continued working.',
        '',
        '**8. Interjection**',
        'Alas!, Hurrah!, Oh!, Wow!',
        'Ex: **Wow!** What a beautiful view!'
      ]
    }
  },
  {
    id: 'eng-3',
    title: {
      mizo: 'Voice: Active & Passive',
      english: 'Voice: Active & Passive'
    },
    notes: {
      mizo: [
        '**1. Active Voice**',
        'Subject in thil ti. S + V + O',
        'Entir: **Ram** kicked the ball.',
        '',
        '**2. Passive Voice**',
        'Object in thil tuar. O + be + V3 + by + S',
        'Entir: The ball was kicked **by Ram**.',
        '',
        '**3. Tense wise Rules**',
        '**Simple Present:** is/am/are + V3',
        'Active: She writes a letter. → Passive: A letter **is written** by her.',
        '**Present Continuous:** is/am/are + being + V3',
        'Active: He is building a house. → Passive: A house **is being built** by him.',
        '**Present Perfect:** has/have + been + V3',
        'Active: They have done the work. → Passive: The work **has been done** by them.',
        '**Simple Past:** was/were + V3',
        'Active: She made a cake. → Passive: A cake **was made** by her.',
        '**Past Continuous:** was/were + being + V3',
        'Active: He was reading a book. → Passive: A book **was being read** by him.',
        '**Past Perfect:** had + been + V3',
        'Active: She had completed the task. → Passive: The task **had been completed** by her.',
        '**Simple Future:** will be + V3',
        'Active: I will write a letter. → Passive: A letter **will be written** by me.',
        '**Modal:** modal + be + V3',
        'Active: You must do it. → Passive: It **must be done** by you.',
        '',
        '**4. MPSC Important Rules**',
        '**Rule 1:** Intransitive verb passive theih loh. Ex: He sleeps. ❌',
        '**Rule 2:** Imperative: Let + O + be + V3. Ex: Open the door → **Let the door be opened**.',
        '**Rule 3:** Who → By whom. Ex: Who wrote this? → **By whom was this written?**',
        '**Rule 4:** What/Which → By what/which. Ex: What caused this? → **By what was this caused?**',
        '**Rule 5:** By + agent dah loh theih: Ex: People speak English → **English is spoken**.'
      ],
      english: [
        '**1. Active Voice**',
        'Subject does action. S + V + O',
        'Ex: **Ram** kicked the ball.',
        '',
        '**2. Passive Voice**',
        'Object receives action. O + be + V3 + by + S',
        'Ex: The ball was kicked **by Ram**.',
        '',
        '**3. Tense wise Rules**',
        '**Simple Present:** is/am/are + V3',
        'Active: She writes a letter. → Passive: A letter **is written** by her.',
        '**Present Continuous:** is/am/are + being + V3',
        'Active: He is building a house. → Passive: A house **is being built** by him.',
        '**Present Perfect:** has/have + been + V3',
        'Active: They have done the work. → Passive: The work **has been done** by them.',
        '**Simple Past:** was/were + V3',
        'Active: She made a cake. → Passive: A cake **was made** by her.',
        '**Past Continuous:** was/were + being + V3',
        'Active: He was reading a book. → Passive: A book **was being read** by him.',
        '**Past Perfect:** had + been + V3',
        'Active: She had completed the task. → Passive: The task **had been completed** by her.',
        '**Simple Future:** will be + V3',
        'Active: I will write a letter. → Passive: A letter **will be written** by me.',
        '**Modal:** modal + be + V3',
        'Active: You must do it. → Passive: It **must be done** by you.',
        '',
        '**4. MPSC Important Rules**',
        '**Rule 1:** Intransitive verb cannot be passive. Ex: He sleeps. ❌',
        '**Rule 2:** Imperative: Let + O + be + V3. Ex: Open the door → **Let the door be opened**.',
        '**Rule 3:** Who → By whom. Ex: Who wrote this? → **By whom was this written?**',
        '**Rule 4:** What/Which → By what/which. Ex: What caused this? → **By what was this caused?**',
        '**Rule 5:** By + agent can be omitted: Ex: People speak English → **English is spoken**.'
      ]
    }
  },
  {
    id: 'eng-4',
    title: {
      mizo: 'Direct & Indirect Speech',
      english: 'Direct & Indirect Speech'
    },
    notes: {
      mizo: [
        '**1. Direct Speech**',
        'Thu sawi ang chiah. " " chhungah.',
        'Entir: He said, **"I am busy."**',
        '',
        '**2. Indirect Speech**',
        'Thu sawi hrilh nawn. " " awm lo.',
        'Entir: He said **that he was busy**.',
        '',
        '**3. Tense Change Rules**',
        'Present → Past: am/is → was, are → were, V1 → V2',
        'Past → Past Perfect: V2 → had + V3',
        'will → would, can → could, may → might, shall → should',
        'Entir: She said, "I **am** going" → She said that she **was** going.',
        '',
        '**4. Pronoun Change**',
        'I → he/she, you → I/he/she/they, we → they',
        'my → his/her, your → my/his/her/their',
        'Entir: He said, "**I** like **my** book" → He said that **he** liked **his** book.',
        '',
        '**5. Time/Place Change**',
        'now → then, today → that day, tomorrow → the next day',
        'yesterday → the previous day, here → there, this → that',
        'Entir: She said, "I will come **tomorrow**" → She said she would come **the next day**.',
        '',
        '**6. No Tense Change**',
        'Universal Truth: He said, "The sun rises in the east" → He said **the sun rises** in the east.',
        'Past Historic Event: He said, "Gandhi was born in 1869" → No change.',
        '',
        '**7. Question**',
        'Yes/No: if/whether hmang. Ex: He said, "Are you ready?" → He asked **if I was** ready.',
        'Wh-word: wh-word vawng. Ex: He said, "Where do you live?" → He asked **where I lived**.',
        '',
        '**8. Imperative**',
        'Order: told/ordered. Ex: He said, "Sit down" → He **ordered me to sit** down.',
        'Request: requested. Ex: She said, "Please help me" → She **requested me to help** her.',
        '',
        '**MPSC Trick:** Said to → told. Said → said. Comma leh inverted comma paih.'
      ],
      english: [
        '**1. Direct Speech**',
        'Exact words spoken. Within " ".',
        'Ex: He said, **"I am busy."**',
        '',
        '**2. Indirect Speech**',
        'Reported speech. No " ".',
        'Ex: He said **that he was busy**.',
        '',
        '**3. Tense Change Rules**',
        'Present → Past: am/is → was, are → were, V1 → V2',
        'Past → Past Perfect: V2 → had + V3',
        'will → would, can → could, may → might, shall → should',
        'Ex: She said, "I **am** going" → She said that she **was** going.',
        '',
        '**4. Pronoun Change**',
        'I → he/she, you → I/he/she/they, we → they',
        'my → his/her, your → my/his/her/their',
        'Ex: He said, "**I** like **my** book" → He said that **he** liked **his** book.',
        '',
        '**5. Time/Place Change**',
        'now → then, today → that day, tomorrow → the next day',
        'yesterday → the previous day, here → there, this → that',
        'Ex: She said, "I will come **tomorrow**" → She said she would come **the next day**.',
        '',
        '**6. No Tense Change**',
        'Universal Truth: He said, "The sun rises in the east" → He said **the sun rises** in the east.',
        'Past Historic Event: He said, "Gandhi was born in 1869" → No change.',
        '',
        '**7. Question**',
        'Yes/No: use if/whether. Ex: He said, "Are you ready?" → He asked **if I was** ready.',
        'Wh-word: retain wh-word. Ex: He said, "Where do you live?" → He asked **where I lived**.',
        '',
        '**8. Imperative**',
        'Order: told/ordered. Ex: He said, "Sit down" → He **ordered me to sit** down.',
        'Request: requested. Ex: She said, "Please help me" → She **requested me to help** her.',
        '',
        '**MPSC Trick:** Said to → told. Said → said. Remove comma and inverted commas.'
      ]
    }
  },
  {
    id: 'eng-5',
    title: {
      mizo: 'Vocabulary: Synonyms & Antonyms',
      english: 'Vocabulary: Synonyms & Antonyms'
    },
    notes: {
      mizo: [
        '**1. Common Synonyms - MPSC Asked**',
        '**Abandon** = Forsake, Desert | **Abundant** = Plentiful, Ample',
        '**Brave** = Courageous, Valiant | **Brief** = Short, Concise',
        '**Candid** = Frank, Honest | **Cautious** = Careful, Wary',
        '**Defend** = Protect, Guard | **Diligent** = Hardworking, Industrious',
        '**Eager** = Keen, Enthusiastic | **Enormous** = Huge, Gigantic',
        '**Feeble** = Weak, Frail | **Frugal** = Thrifty, Economical',
        '**Generous** = Liberal, Bountiful | **Genuine** = Authentic, Real',
        '**Hostile** = Unfriendly, Antagonistic | **Humble** = Modest, Meek',
        '**Identical** = Same, Alike | **Immense** = Vast, Huge',
        '**Jealous** = Envious, Resentful | **Jubilant** = Joyful, Elated',
        '',
        '**2. Common Antonyms - MPSC Asked**',
        '**Accept** × Reject | **Ancient** × Modern',
        '**Arrival** × Departure | **Artificial** × Natural',
        '**Ascend** × Descend | **Attack** × Defend',
        '**Bitter** × Sweet | **Bless** × Curse',
        '**Brave** × Cowardly | **Bright** × Dull',
        '**Cheap** × Expensive | **Complex** × Simple',
        '**Cruel** × Kind | **Dense** × Sparse',
        '**Empty** × Full | **Enemy** × Friend',
        '**Expand** × Contract | **Failure** × Success',
        '**Guilty** × Innocent | **Happy** × Sad',
        '',
        '**3. One Word Substitution**',
        '**Autobiography** = Mihring in amah chanchin a ziah',
        '**Biography** = Mi dang chanchin ziah',
        '**Centenary** = Kum 100 cham',
        '**Democracy** = Mipui rorelna',
        '**Epidemic** = Natna darh chak',
        '**Feminist** = Hmeichhe dikna chanvo duh tu',
        '**Honorary** = Hlawh la lo',
        '**Illegible** = Chhiar theih loh',
        '**Irreparable** = Siam that theih loh',
        '**Manuscript** = Kut ziak',
        '',
        '**4. Idioms & Phrases - MPSC**',
        '**A blessing in disguise** = Thil tha lo lang si, a tawpah tha',
        '**Beat around the bush** = Thudik sawi lo, kual vak',
        '**Cry over spilt milk** = Thil thleng tawh sun vak',
        '**Hit the nail on the head** = Thudik tak sawi',
        '**Once in a blue moon** = Vang tak, khat tawkin',
        '**Piece of cake** = Thil awlsam',
        '**Spill the beans** = Thuruk puang',
        '**The ball is in your court** = Nangma kutah a awm',
        '**Under the weather** = Dam lo',
        '**When pigs fly** = Thleng ngai lo tur'
      ],
      english: [
        '**1. Common Synonyms - MPSC Asked**',
        '**Abandon** = Forsake, Desert | **Abundant** = Plentiful, Ample',
        '**Brave** = Courageous, Valiant | **Brief** = Short, Concise',
        '**Candid** = Frank, Honest | **Cautious** = Careful, Wary',
        '**Defend** = Protect, Guard | **Diligent** = Hardworking, Industrious',
        '**Eager** = Keen, Enthusiastic | **Enormous** = Huge, Gigantic',
        '**Feeble** = Weak, Frail | **Frugal** = Thrifty, Economical',
        '**Generous** = Liberal, Bountiful | **Genuine** = Authentic, Real',
        '**Hostile** = Unfriendly, Antagonistic | **Humble** = Modest, Meek',
        '**Identical** = Same, Alike | **Immense** = Vast, Huge',
        '**Jealous** = Envious, Resentful | **Jubilant** = Joyful, Elated',
        '',
        '**2. Common Antonyms - MPSC Asked**',
        '**Accept** × Reject | **Ancient** × Modern',
        '**Arrival** × Departure | **Artificial** × Natural',
        '**Ascend** × Descend | **Attack** × Defend',
        '**Bitter** × Sweet | **Bless** × Curse',
        '**Brave** × Cowardly | **Bright** × Dull',
        '**Cheap** × Expensive | **Complex** × Simple',
        '**Cruel** × Kind | **Dense** × Sparse',
        '**Empty** × Full | **Enemy** × Friend',
        '**Expand** × Contract | **Failure** × Success',
        '**Guilty** × Innocent | **Happy** × Sad',
        '',
        '**3. One Word Substitution**',
        '**Autobiography** = Life story written by oneself',
        '**Biography** = Life story written by others',
        '**Centenary** = 100th anniversary',
        '**Democracy** = Government by the people',
        '**Epidemic** = Widespread disease',
        '**Feminist** = Advocate of women\'s rights',
        '**Honorary** = Without payment',
        '**Illegible** = Not readable',
        '**Irreparable** = Cannot be repaired',
        '**Manuscript** = Handwritten document',
        '',
        '**4. Idioms & Phrases - MPSC**',
        '**A blessing in disguise** = Something good that isn\'t recognized at first',
        '**Beat around the bush** = Avoid main topic',
        '**Cry over spilt milk** = Complain about past loss',
        '**Hit the nail on the head** = Describe exactly what is causing situation',
        '**Once in a blue moon** = Very rarely',
        '**Piece of cake** = Very easy',
        '**Spill the beans** = Reveal secret',
        '**The ball is in your court** = It\'s your decision',
        '**Under the weather** = Ill',
        '**When pigs fly** = Something that will never happen'
      ]
    }
  },
  {
    id: 'eng-6',
    title: {
      mizo: 'Comprehension & Precis Writing',
      english: 'Comprehension & Precis Writing'
    },
    notes: {
      mizo: [
        '**1. Comprehension Tips - MPSC**',
        '**Step 1:** Passage chhiar vawi 2. Hmanhmawh suh.',
        '**Step 2:** Zawhna chhiar hmasa. Key word underline.',
        '**Step 3:** Passage ah answer zawng. Line number mark.',
        '**Step 4:** Own words in ziak. Passage copy suh.',
        '',
        '**2. Types of Questions**',
        '**Factual:** Direct answer passage ah awm. Ex: When was Gandhi born?',
        '**Inferential:** Ngaihtuah ngai. Ex: What does the author suggest?',
        '**Vocabulary:** Word meaning context atang. Ex: What does "elated" mean?',
        '**Main Idea:** Passage pum pui theme. Ex: What is the central idea?',
        '',
        '**3. Precis Writing Rules**',
        '**Rule 1:** 1/3 length. Passage 300 words → Precis 100 words.',
        '**Rule 2:** Own words. Copy paste suh.',
        '**Rule 3:** Third person. I, we, you hmang suh.',
        '**Rule 4:** Direct speech → Indirect.',
        '**Rule 5:** Title pe rawh. Central idea.',
        '**Rule 6:** One paragraph chauh. Points join rawh.',
        '',
        '**4. Precis Steps**',
        '1. Chhiar vawi 2-3. Theme hrethiam.',
        '2. Important points underline.',
        '3. Rough draft ziak.',
        '4. Word count. 1/3 a ni em check.',
        '5. Final draft. Grammar check.',
        '',
        '**5. MPSC Example**',
        '**Passage:** "Democracy is government of the people, by the people, for the people. It ensures liberty, equality, fraternity. India is the largest democracy. Every citizen above 18 has voting right..."',
        '**Precis Title:** Democracy in India',
        '**Precis:** Democracy means people\'s rule ensuring liberty, equality and fraternity. India, the largest democracy, grants voting rights to all citizens above 18. [33 words]'
      ],
      english: [
        '**1. Comprehension Tips - MPSC**',
        '**Step 1:** Read passage twice. Don\'t rush.',
        '**Step 2:** Read questions first. Underline key words.',
        '**Step 3:** Find answers in passage. Mark line numbers.',
        '**Step 4:** Write in own words. Don\'t copy passage.',
        '',
        '**2. Types of Questions**',
        '**Factual:** Direct answer in passage. Ex: When was Gandhi born?',
        '**Inferential:** Requires thinking. Ex: What does the author suggest?',
        '**Vocabulary:** Word meaning from context. Ex: What does "elated" mean?',
        '**Main Idea:** Overall theme of passage. Ex: What is the central idea?',
        '',
        '**3. Precis Writing Rules**',
        '**Rule 1:** 1/3 length. Passage 300 words → Precis 100 words.',
        '**Rule 2:** Own words. No copy paste.',
        '**Rule 3:** Third person. Don\'t use I, we, you.',
        '**Rule 4:** Direct speech → Indirect.',
        '**Rule 5:** Give title. Central idea.',
        '**Rule 6:** One paragraph only. Join points.',
        '',
        '**4. Precis Steps**',
        '1. Read 2-3 times. Understand theme.',
        '2. Underline important points.',
        '3. Write rough draft.',
        '4. Word count. Check if 1/3.',
        '5. Final draft. Check grammar.',
        '',
        '**5. MPSC Example**',
        '**Passage:** "Democracy is government of the people, by the people, for the people. It ensures liberty, equality, fraternity. India is the largest democracy. Every citizen above 18 has voting right..."',
        '**Precis Title:** Democracy in India',
        '**Precis:** Democracy means people\'s rule ensuring liberty, equality and fraternity. India, the largest democracy, grants voting rights to all citizens above 18. [33 words]'
      ]
    }
  },
  {
    id: 'eng-7',
    title: {
      mizo: 'Letter & Essay Writing',
      english: 'Letter & Essay Writing'
    },
    notes: {
      mizo: [
        '**1. Formal Letter Format - MPSC**',
        'Sender Address',
        'Date',
        'Receiver Address',
        'Subject: __________',
        'Sir/Madam,',
        'Body: Para 1 - Introduction',
        'Para 2 - Main point',
        'Para 3 - Conclusion/Request',
        'Yours faithfully,',
        'Signature',
        'Name',
        '',
        '**2. Letter Types**',
        '**Job Application:** Mention post, qualification, experience. CV enclose.',
        '**Complaint:** Problem sawifiah. Solution request.',
        '**Editor:** Newspaper ah. Public issue. Mizo society problem.',
        '**Permission:** Leave, transfer request.',
        '',
        '**3. Essay Writing - MPSC**',
        '**Word Limit:** 250-300 words.',
        '**Structure:** Introduction → Body 2-3 para → Conclusion',
        '**Introduction:** Topic introduce. Thesis statement.',
        '**Body:** Point 1 + Example, Point 2 + Example, Point 3 + Data',
        '**Conclusion:** Summarize + Solution/Future view',
        '',
        '**4. Important Essay Topics 2026**',
        '**1. Viksit Bharat 2047** - Vision, roadmap, youth role',
        '**2. Digital India** - UPI, Digital Rupee, AI, 6G',
        '**3. Climate Change** - Net Zero 2070, Panchamrit, LiFE',
        '**4. Women Empowerment** - 33% reservation, Nari Shakti, STEM',
        '**5. Unemployment** - Problem, causes, skill development, Startup India',
        '**6. Tourism in Mizoram** - Potential, Railway, Thainzal, Calendar 2026',
        '',
        '**5. Essay Tips**',
        'Simple language. Grammar dik.',
        'Facts, data telh. Ex: India HDI 0.685, UPI 16.99 billion.',
        'Mizoram example telh. Ex: Bairabi-Sairang rail, Rubber Mission.',
        'Positive conclusion. Solution pe rawh.'
      ],
      english: [
        '**1. Formal Letter Format - MPSC**',
        'Sender Address',
        'Date',
        'Receiver Address',
        'Subject: __________',
        'Sir/Madam,',
        'Body: Para 1 - Introduction',
        'Para 2 - Main point',
        'Para 3 - Conclusion/Request',
        'Yours faithfully,',
        'Signature',
        'Name',
        '',
        '**2. Letter Types**',
        '**Job Application:** Mention post, qualification, experience. Enclose CV.',
        '**Complaint:** Explain problem. Request solution.',
        '**Editor:** To newspaper. Public issue. Mizo society problem.',
        '**Permission:** Leave, transfer request.',
        '',
        '**3. Essay Writing - MPSC**',
        '**Word Limit:** 250-300 words.',
        '**Structure:** Introduction → Body 2-3 para → Conclusion',
        '**Introduction:** Introduce topic. Thesis statement.',
        '**Body:** Point 1 + Example, Point 2 + Example, Point 3 + Data',
        '**Conclusion:** Summarize + Solution/Future view',
        '',
        '**4. Important Essay Topics 2026**',
        '**1. Viksit Bharat 2047** - Vision, roadmap, youth role',
        '**2. Digital India** - UPI, Digital Rupee, AI, 6G',
        '**3. Climate Change** - Net Zero 2070, Panchamrit, LiFE',
        '**4. Women Empowerment** - 33% reservation, Nari Shakti, STEM',
        '**5. Unemployment** - Problem, causes, skill development, Startup India',
        '**6. Tourism in Mizoram** - Potential, Railway, Thainzal, Calendar 2026',
        '',
        '**5. Essay Tips**',
        'Simple language. Correct grammar.',
        'Include facts, data. Ex: India HDI 0.685, UPI 16.99 billion.',
        'Include Mizoram examples. Ex: Bairabi-Sairang rail, Rubber Mission.',
        'Positive conclusion. Give solutions.'
      ]
    }
  }
]

export default function EnglishPage() {
  return (
    <SubjectPage
      subjectName={{ mizo: 'English', english: 'English' }}
      chapters={englishChapters}
      backLink="/"
      testLink="/english/test"
      testTitle="English Mock Test"
      testDesc="Grammar • Vocabulary • Comprehension • Writing • MPSC Important"
      slug="english"
      testId="english-mock-1"
      showMockTest={true}
    />
  )
}