'use client'
import SubjectPage from '../components/SubjectPage'

const mizoramChapters = [
  {
    id: 'mizo-1',
    title: {
      mizo: 'Chapter 1: Mizoram History & Formation',
      english: 'Chapter 1: Mizoram History & Formation'
    },
    notes: {
      mizo: [
        '**1. Early History**',
        '**Original Name:** Lushai Hills. Mizo = Mi + Zo = Highlanders.',
        '**Migration:** 16th-18th century. Chhinlung theory - cave in China. Chin Hills Burma atangin.',
        '**Tribes:** Lusei, Ralte, Hmar, Paihte, Pawi/Lai, Mara, Thado, Gangte, Vaiphei etc.',
        '**Chieftainship:** Lal system. Village chief hereditary. Upas advisors. Thirdeng blacksmith, Puithiam priest, Tlangau crier.',
        '',
        '**2. British Period 1890-1947**',
        '**Annexation:** 1890 South Lushai Hills. 1891 North Lushai Hills. 1898 merged = Lushai Hills District Assam.',
        '**Chiefs:** 60 chiefs 1890. 312 chiefs 1940. Sailo clan dominant.',
        '**Christianity:** 1894 Rev F.W. Savidge & J.H. Lorrain Arthington Mission. Zosapthara & Sap Upa.',
        '**Education:** First school 1897 Aizawl. Mizo Alphabet 1894 Lorrain. Bible translation 1898.',
        '**WW1:** 2100 Mizos France Labour Corps 1917-18. WW2: 1942-45 Assam Regiment.',
        '',
        '**3. Post-Independence**',
        '**Lushai Hills Autonomous District 1952:** Under Sixth Schedule. District Council Aizawl.',
        '**Mautam Famine 1959:** Bamboo flowering. Rat plague. MNF famine relief.',
        '**MNF Uprising 28 Feb 1966:** Laldenga. Operation Jericho. Aizawl bombed 4-13 Mar 1966.',
        '**UT Status 21 Jan 1972:** Mizoram Union Territory. Capital Aizawl.',
        '**Peace Accord 30 June 1986:** Rajiv Gandhi-Laldenga. MNF surrender. Laldenga 1st CM.',
        '**Statehood 20 Feb 1987:** 23rd State of India. Laldenga CM 1987-88.',
        '',
        '**4. MPSC Key Dates**',
        '**1890:** British annexation South. **1891:** North. **1894:** Missionaries arrived.',
        '**1898:** Lushai Hills District. **1952:** Autonomous District. **1972:** UT.',
        '**1986:** Peace Accord. **1987:** Statehood. **20 Feb:** State Day.',
        '**Mizo Union:** 1946 first political party. Abolish chieftainship demand.'
      ],
      english: [
        '**1. Early History**',
        '**Original Name:** Lushai Hills. Mizo = Mi + Zo = Highlanders.',
        '**Migration:** 16th-18th century. Chhinlung theory - cave in China. From Chin Hills Burma.',
        '**Tribes:** Lusei, Ralte, Hmar, Paihte, Pawi/Lai, Mara, Thado, Gangte, Vaiphei etc.',
        '**Chieftainship:** Lal system. Village chief hereditary. Upas advisors. Thirdeng blacksmith, Puithiam priest, Tlangau crier.',
        '',
        '**2. British Period 1890-1947**',
        '**Annexation:** 1890 South Lushai Hills. 1891 North Lushai Hills. 1898 merged = Lushai Hills District Assam.',
        '**Chiefs:** 60 chiefs 1890. 312 chiefs 1940. Sailo clan dominant.',
        '**Christianity:** 1894 Rev F.W. Savidge & J.H. Lorrain Arthington Mission. Zosapthara & Sap Upa.',
        '**Education:** First school 1897 Aizawl. Mizo Alphabet 1894 Lorrain. Bible translation 1898.',
        '**WW1:** 2100 Mizos France Labour Corps 1917-18. WW2: 1942-45 Assam Regiment.',
        '',
        '**3. Post-Independence**',
        '**Lushai Hills Autonomous District 1952:** Under Sixth Schedule. District Council Aizawl.',
        '**Mautam Famine 1959:** Bamboo flowering. Rat plague. MNF famine relief.',
        '**MNF Uprising 28 Feb 1966:** Laldenga. Operation Jericho. Aizawl bombed 4-13 Mar 1966.',
        '**UT Status 21 Jan 1972:** Mizoram Union Territory. Capital Aizawl.',
        '**Peace Accord 30 June 1986:** Rajiv Gandhi-Laldenga. MNF surrender. Laldenga 1st CM.',
        '**Statehood 20 Feb 1987:** 23rd State of India. Laldenga CM 1987-88.',
        '',
        '**4. MPSC Key Dates**',
        '**1890:** British annexation South. **1891:** North. **1894:** Missionaries arrived.',
        '**1898:** Lushai Hills District. **1952:** Autonomous District. **1972:** UT.',
        '**1986:** Peace Accord. **1987:** Statehood. **20 Feb:** State Day.',
        '**Mizo Union:** 1946 first political party. Abolish chieftainship demand.'
      ]
    }
  },
  {
    id: 'mizo-2',
    title: {
      mizo: 'Chapter 2: Geography & Districts',
      english: 'Chapter 2: Geography & Districts'
    },
    notes: {
      mizo: [
        '**1. Location & Area**',
        '**Latitudinal:** 21°56\'N to 24°31\'N. **Longitudinal:** 92°16\'E to 93°26\'E.',
        '**Area:** 21,081 sq km. 25th largest state. 0.64% India.',
        '**Boundaries:** Assam North 123km, Tripura West 66km, Manipur Northeast 95km. International: Bangladesh West 318km, Myanmar East-South 510km.',
        '**Length:** 277 km North-South. **Width:** 121 km East-West.',
        '',
        '**2. Physiography**',
        '**Hills:** Average 1000m. Highest Phawngpui/Blue Mountain 2,157m Lawngtlai.',
        '**Ranges:** North-South. 21 major ranges. Lushai Hills main.',
        '**Rivers:** Tlawng 185km longest, Tuirial, Tuivawl, Chhimtuipui/Kolodyne largest volume, Khawthlangtuipui/Karnaphuli.',
        '**Lakes:** Palak largest Lawngtlai, Tamdil Saitual, Rih Dil Myanmar border sacred.',
        '**Climate:** Moderate. Temp 11°C-29°C. Rainfall 2540mm. June-Sept monsoon.',
        '',
        '**3. 11 Districts 2025**',
        '**Aizawl:** Capital. 1952. 3,577 sq km. Highest population 4 lakh. Durtlang, Reiek.',
        '**Lunglei:** 1972. 4,536 sq km largest. 2nd largest town. Nghasih.',
        '**Siaha/Mara:** 1998. 1,399 sq km. Palak Lake. Mara Autonomous District Council.',
        '**Champhai:** 1998. 3,185 sq km. Rice bowl. Zokhawthar border trade.',
        '**Kolasib:** 1998. 1,382 sq km. Bairabi railhead. Vairengte Counter-Insurgency School.',
        '**Serchhip:** 1998. 1,422 sq km. Thenzawl handloom. Vantawng Falls 229m highest.',
        '**Lawngtlai:** 1998. 2,557 sq km. Phawngpui. Lai Autonomous District Council.',
        '**Mamit:** 1998. 3,025 sq km. Dampa Tiger Reserve. Tuirial Dam.',
        '**Khawzawl:** 2019. 1,164 sq km. New. Biate.',
        '**Hnahthial:** 2019. 1,012 sq km. Smallest. South Vanlaiphai.',
        '**Saitual:** 2019. 1,432 sq km. Tamdil Lake. Keifang.',
        '',
        '**4. Forests & Wildlife**',
        '**Forest Cover:** 17,820 sq km 84.5% India highest. Very Dense 1,748 sq km.',
        '**Types:** Tropical wet evergreen, semi-evergreen, montane subtropical.',
        '**Wildlife Sanctuaries:** 8. Dampa Tiger Reserve 500 sq km. Ngengpui 110 sq km.',
        '**National Parks:** 2. Murlen 200 sq km, Phawngpui/Blue Mountain 50 sq km.',
        '**Biosphere:** 0. But Dampa proposed.',
        '**MPSC Point:** Phawngpui = Blue Mountain. Vantawng = highest waterfall 229m.'
      ],
      english: [
        '**1. Location & Area**',
        '**Latitudinal:** 21°56\'N to 24°31\'N. **Longitudinal:** 92°16\'E to 93°26\'E.',
        '**Area:** 21,081 sq km. 25th largest state. 0.64% India.',
        '**Boundaries:** Assam North 123km, Tripura West 66km, Manipur Northeast 95km. International: Bangladesh West 318km, Myanmar East-South 510km.',
        '**Length:** 277 km North-South. **Width:** 121 km East-West.',
        '',
        '**2. Physiography**',
        '**Hills:** Average 1000m. Highest Phawngpui/Blue Mountain 2,157m Lawngtlai.',
        '**Ranges:** North-South. 21 major ranges. Lushai Hills main.',
        '**Rivers:** Tlawng 185km longest, Tuirial, Tuivawl, Chhimtuipui/Kolodyne largest volume, Khawthlangtuipui/Karnaphuli.',
        '**Lakes:** Palak largest Lawngtlai, Tamdil Saitual, Rih Dil Myanmar border sacred.',
        '**Climate:** Moderate. Temp 11°C-29°C. Rainfall 2540mm. June-Sept monsoon.',
        '',
        '**3. 11 Districts 2025**',
        '**Aizawl:** Capital. 1952. 3,577 sq km. Highest population 4 lakh. Durtlang, Reiek.',
        '**Lunglei:** 1972. 4,536 sq km largest. 2nd largest town. Nghasih.',
        '**Siaha/Mara:** 1998. 1,399 sq km. Palak Lake. Mara Autonomous District Council.',
        '**Champhai:** 1998. 3,185 sq km. Rice bowl. Zokhawthar border trade.',
        '**Kolasib:** 1998. 1,382 sq km. Bairabi railhead. Vairengte Counter-Insurgency School.',
        '**Serchhip:** 1998. 1,422 sq km. Thenzawl handloom. Vantawng Falls 229m highest.',
        '**Lawngtlai:** 1998. 2,557 sq km. Phawngpui. Lai Autonomous District Council.',
        '**Mamit:** 1998. 3,025 sq km. Dampa Tiger Reserve. Tuirial Dam.',
        '**Khawzawl:** 2019. 1,164 sq km. New. Biate.',
        '**Hnahthial:** 2019. 1,012 sq km. Smallest. South Vanlaiphai.',
        '**Saitual:** 2019. 1,432 sq km. Tamdil Lake. Keifang.',
        '',
        '**4. Forests & Wildlife**',
        '**Forest Cover:** 17,820 sq km 84.5% India highest. Very Dense 1,748 sq km.',
        '**Types:** Tropical wet evergreen, semi-evergreen, montane subtropical.',
        '**Wildlife Sanctuaries:** 8. Dampa Tiger Reserve 500 sq km. Ngengpui 110 sq km.',
        '**National Parks:** 2. Murlen 200 sq km, Phawngpui/Blue Mountain 50 sq km.',
        '**Biosphere:** 0. But Dampa proposed.',
        '**MPSC Point:** Phawngpui = Blue Mountain. Vantawng = highest waterfall 229m.'
      ]
    }
  },
  {
    id: 'mizo-3',
    title: {
      mizo: 'Chapter 3: Polity & Administration',
      english: 'Chapter 3: Polity & Administration'
    },
    notes: {
      mizo: [
        '**1. Constitutional Status**',
        '**Article 371G:** Special provision Mizoram. Religious/social practices, customary law, administration civil/criminal justice, land ownership - State Assembly consent needed.',
        '**Sixth Schedule:** 3 Autonomous District Councils - Lai, Mara, Chakma. 1954.',
        '**Inner Line Permit:** 1873 Bengal Eastern Frontier Regulation. Non-Mizo needs ILP.',
        '',
        '**2. Executive**',
        '**Governor:** Gen Vijay Kumar Singh 2025. Raj Bhavan Aizawl.',
        '**CM:** Lalduhoma ZPM 2023. 1st CM Laldenga 1987-88.',
        '**Council Ministers:** Max 12 = 15% of 40 MLAs. 91st Amendment.',
        '',
        '**3. Legislature**',
        '**Assembly:** Unicameral. 40 MLAs. 39 ST reserved. Term 5 years.',
        '**Speaker:** Lalbiakzama 2023. 1st session 1987.',
        '**MP:** 1 Lok Sabha Aizawl, 1 Rajya Sabha. Total 2.',
        '**MLC:** 0. No Legislative Council.',
        '',
        '**4. Judiciary**',
        '**High Court:** Gauhati HC Aizawl Bench 1990. Permanent Bench 2000.',
        '**District Courts:** 8 districts. Village Courts customary law.',
        '**Lok Adalat:** Mobile courts rural areas.',
        '',
        '**5. Local Governance**',
        '**Village Councils:** 834 villages. Elected 5 years. VC President head.',
        '**Local Councils:** Aizawl, Lunglei urban areas. 19 wards Aizawl Municipal Corporation 2010.',
        '**Autonomous Councils:**',
        '   - **Lai ADC Lawngtlai 1972:** 29 members. V. Zirsanga CEM.',
        '   - **Mara ADC Siaha 1972:** 28 members. M. Laikaw CEM.',
        '   - **Chakma ADC Kamalanagar 1972:** 24 members. Buddha Lila Chakma CEM.',
        '',
        '**6. Elections 2023**',
        '**Assembly:** ZPM 27, MNF 10, BJP 2, INC 1. Lalduhoma CM.',
        '**Lok Sabha 2024:** Richard Vanlalhmangaiha ZPM.',
        '**MPSC Point:** 371G special status. ILP required. 3 ADCs under 6th Schedule.'
      ],
      english: [
        '**1. Constitutional Status**',
        '**Article 371G:** Special provision Mizoram. Religious/social practices, customary law, administration civil/criminal justice, land ownership - State Assembly consent needed.',
        '**Sixth Schedule:** 3 Autonomous District Councils - Lai, Mara, Chakma. 1954.',
        '**Inner Line Permit:** 1873 Bengal Eastern Frontier Regulation. Non-Mizo needs ILP.',
        '',
        '**2. Executive**',
        '**Governor:** Gen Vijay Kumar Singh 2025. Raj Bhavan Aizawl.',
        '**CM:** Lalduhoma ZPM 2023. 1st CM Laldenga 1987-88.',
        '**Council Ministers:** Max 12 = 15% of 40 MLAs. 91st Amendment.',
        '',
        '**3. Legislature**',
        '**Assembly:** Unicameral. 40 MLAs. 39 ST reserved. Term 5 years.',
        '**Speaker:** Lalbiakzama 2023. 1st session 1987.',
        '**MP:** 1 Lok Sabha Aizawl, 1 Rajya Sabha. Total 2.',
        '**MLC:** 0. No Legislative Council.',
        '',
        '**4. Judiciary**',
        '**High Court:** Gauhati HC Aizawl Bench 1990. Permanent Bench 2000.',
        '**District Courts:** 8 districts. Village Courts customary law.',
        '**Lok Adalat:** Mobile courts rural areas.',
        '',
        '**5. Local Governance**',
        '**Village Councils:** 834 villages. Elected 5 years. VC President head.',
        '**Local Councils:** Aizawl, Lunglei urban areas. 19 wards Aizawl Municipal Corporation 2010.',
        '**Autonomous Councils:**',
        '   - **Lai ADC Lawngtlai 1972:** 29 members. V. Zirsanga CEM.',
        '   - **Mara ADC Siaha 1972:** 28 members. M. Laikaw CEM.',
        '   - **Chakma ADC Kamalanagar 1972:** 24 members. Buddha Lila Chakma CEM.',
        '',
        '**6. Elections 2023**',
        '**Assembly:** ZPM 27, MNF 10, BJP 2, INC 1. Lalduhoma CM.',
        '**Lok Sabha 2024:** Richard Vanlalhmangaiha ZPM.',
        '**MPSC Point:** 371G special status. ILP required. 3 ADCs under 6th Schedule.'
      ]
    }
  },
  {
    id: 'mizo-4',
    title: {
      mizo: 'Chapter 4: Economy & Schemes 2024-26',
      english: 'Chapter 4: Economy & Schemes 2024-26'
    },
    notes: {
      mizo: [
        '**1. Economy Overview 2025-26**',
        '**GSDP 2025-26:** Rs 49,489 crore. Growth 11%. Per capita Rs 3.73 lakh.',
        '**Sectors:** Agriculture 20%, Industry 20%, Services 60%.',
        '**Fiscal Deficit:** 3% GSDP. Revenue surplus target.',
        '**Debt:** Rs 15,197 crore 30.7% GSDP. Within 40% limit.',
        '',
        '**2. Agriculture**',
        '**Jhum:** 40,000 families. Slash-burn. 2-3 year cycle. Govt discouraging.',
        '**WRC:** Wet Rice Cultivation 35,000 ha. Champhai, Serchhip. Rice 1.2 lakh MT.',
        '**Crops:** Rice main, maize, pulses, oilseeds, sugarcane, potato.',
        '**Horticulture:** Orange, banana, passion fruit, grape, anthurium. Mission Organic 2025.',
        '**Bamboo:** 31% area. 20 species. Mautam 2007 last. Next 2055 expected.',
        '',
        '**3. Industry & Power**',
        '**Industry:** Small scale. Handloom Thenzawl, food processing, bamboo.',
        '**Minerals:** No major. Coal, limestone, clay minor.',
        '**Power:** Installed 287 MW. Hydro Tuirial 60MW, Serlui B 12MW, Tuipang 3MW.',
        '**Requirement:** 168 MW. Deficit 40%. Import Assam, Tripura.',
        '**Solar:** 20 MW target 2030. Renewable push.',
        '',
        '**4. Transport 2025-26**',
        '**Roads:** 8,500 km. NH 1,400 km. NH-54 Aizawl-Silchar lifeline.',
        '**Railway:** Bairabi-Sairang 51.38 km. Rs 9,000 cr. Inaugurated 13 Sep 2025 PM Modi.',
        '   - **Rajdhani Express:** Delhi-Sairang June 2026 planned. Mizoram connected national network.',
        '**Airport:** Lengpui 1998. Flights Kolkata, Guwahati, Imphal. International to Myanmar planned.',
        '**Waterways:** Tlawng NW-102. Kaladan Multi-Modal Sittwe port Myanmar.',
        '',
        '**5. Major Schemes 2024-26**',
        '**Handholding Scheme/Bana Kaih:** Rs 2.5 lakh per beneficiary. Partner departments. Entrepreneurship.',
        '**Healthcare Scheme:** Rs 5 lakh cashless. Rs 9,120 cr 2025-26. SCERT textbook free.',
        '**Super Specialty Cancer Hospital:** Rs 700 cr Zemabawk. 200 beds. 2027 target.',
        '**Aizawl Peak Power:** Rs 2,400 cr. 110 MW battery storage.',
        '**Education:** SCERT textbooks free. English medium primary.',
        '**Rubber Mission:** 4.5 lakh saplings Serchhip, Hnahthial, Mamit. 17,700 ha target.',
        '',
        '**6. Demographics 2025**',
        '**Population:** 13.6 lakh estimate. Density 52/sq km 2nd lowest.',
        '**Literacy:** 91.3% 3rd India. Male 93.3%, Female 89.3%.',
        '**Sex Ratio:** 975. Child 971.',
        '**Urban:** 52% highest NE. Rural 48%.',
        '**ST:** 94.4% Mizo. SC 0.1%. Christianity 87%, Buddhism 8% Chakma, Hindu 3%.',
        '**Languages:** Mizo official, English, Hindi.',
        '**MPSC Point:** Bana Kaih Rs 2.5L, Healthcare Rs 5L, Railway 2025, Cancer Hospital Rs 700cr.'
      ],
      english: [
        '**1. Economy Overview 2025-26**',
        '**GSDP 2025-26:** Rs 49,489 crore. Growth 11%. Per capita Rs 3.73 lakh.',
        '**Sectors:** Agriculture 20%, Industry 20%, Services 60%.',
        '**Fiscal Deficit:** 3% GSDP. Revenue surplus target.',
        '**Debt:** Rs 15,197 crore 30.7% GSDP. Within 40% limit.',
        '',
        '**2. Agriculture**',
        '**Jhum:** 40,000 families. Slash-burn. 2-3 year cycle. Govt discouraging.',
        '**WRC:** Wet Rice Cultivation 35,000 ha. Champhai, Serchhip. Rice 1.2 lakh MT.',
        '**Crops:** Rice main, maize, pulses, oilseeds, sugarcane, potato.',
        '**Horticulture:** Orange, banana, passion fruit, grape, anthurium. Mission Organic 2025.',
        '**Bamboo:** 31% area. 20 species. Mautam 2007 last. Next 2055 expected.',
        '',
        '**3. Industry & Power**',
        '**Industry:** Small scale. Handloom Thenzawl, food processing, bamboo.',
        '**Minerals:** No major. Coal, limestone, clay minor.',
        '**Power:** Installed 287 MW. Hydro Tuirial 60MW, Serlui B 12MW, Tuipang 3MW.',
        '**Requirement:** 168 MW. Deficit 40%. Import Assam, Tripura.',
        '**Solar:** 20 MW target 2030. Renewable push.',
        '',
        '**4. Transport 2025-26**',
        '**Roads:** 8,500 km. NH 1,400 km. NH-54 Aizawl-Silchar lifeline.',
        '**Railway:** Bairabi-Sairang 51.38 km. Rs 9,000 cr. Inaugurated 13 Sep 2025 PM Modi.',
        '   - **Rajdhani Express:** Delhi-Sairang June 2026 planned. Mizoram connected national network.',
        '**Airport:** Lengpui 1998. Flights Kolkata, Guwahati, Imphal. International to Myanmar planned.',
        '**Waterways:** Tlawng NW-102. Kaladan Multi-Modal Sittwe port Myanmar.',
        '',
        '**5. Major Schemes 2024-26**',
        '**Handholding Scheme/Bana Kaih:** Rs 2.5 lakh per beneficiary. Partner departments. Entrepreneurship.',
        '**Healthcare Scheme:** Rs 5 lakh cashless. Rs 9,120 cr 2025-26. SCERT textbook free.',
        '**Super Specialty Cancer Hospital:** Rs 700 cr Zemabawk. 200 beds. 2027 target.',
        '**Aizawl Peak Power:** Rs 2,400 cr. 110 MW battery storage.',
        '**Education:** SCERT textbooks free. English medium primary.',
        '**Rubber Mission:** 4.5 lakh saplings Serchhip, Hnahthial, Mamit. 17,700 ha target.',
        '',
        '**6. Demographics 2025**',
        '**Population:** 13.6 lakh estimate. Density 52/sq km 2nd lowest.',
        '**Literacy:** 91.3% 3rd India. Male 93.3%, Female 89.3%.',
        '**Sex Ratio:** 975. Child 971.',
        '**Urban:** 52% highest NE. Rural 48%.',
        '**ST:** 94.4% Mizo. SC 0.1%. Christianity 87%, Buddhism 8% Chakma, Hindu 3%.',
        '**Languages:** Mizo official, English, Hindi.',
        '**MPSC Point:** Bana Kaih Rs 2.5L, Healthcare Rs 5L, Railway 2025, Cancer Hospital Rs 700cr.'
      ]
    }
  },
  {
    id: 'mizo-5',
    title: {
      mizo: 'Chapter 5: Culture, Festivals & Current Affairs 2025-26',
      english: 'Chapter 5: Culture, Festivals & Current Affairs 2025-26'
    },
    notes: {
      mizo: [
        '**1. Festivals**',
        '**Mim Kut:** Aug-Sep. Maize festival. After harvest. Lalmanga legend.',
        '**Pawl Kut:** Dec-Jan. Straw festival. Post-harvest. 2 days.',
        '**Chapchar Kut:** March. Most popular. Jhum clearing after. 7 days. State festival.',
        '**Thalfavang Kut:** Nov. Weeding completed. Youth festival.',
        '**Christmas:** 25 Dec. Biggest. Kohhran celebration. State holiday.',
        '**Anthurium Festival:** Sep Reiek. Tourism. Flower export.',
        '',
        '**2. Dances & Music**',
        '**Cheraw:** Bamboo dance. Men bamboo, women dance. Sarlamkai variant.',
        '**Khuallam:** Guest dance. Community. Cloth waving.',
        '**Chheihlam:** Squatting dance. Rice beer. Fast rhythm.',
        '**Chailam:** Mim Kut dance. Snake-like movement.',
        '**Sarlamkai:** War dance. Victory celebration.',
        '**Music:** Tingtang guitar, Dar drum, Phenglawng flute. Gospel strong.',
        '',
        '**3. Dress & Cuisine**',
        '**Dress:** Women - Puan wraparound, Kawrchei blouse. Men - coat, trousers. Tawlhlohpuan ceremonial.',
        '**Cuisine:** Bai veg stew, Sawhchiar rice-meat, Vawksa rep pork, Bamboo shoot, Sa-um fermented pork.',
        '**Beverages:** Zu rice beer traditional, now tea common.',
        '',
        '**4. Social System**',
        '**Tlawmngaihna:** Selfless service. Core Mizo ethic. Help without expectation.',
        '**Zawlbuk:** Bachelor dormitory. Abolished 1926. Moral education.',
        '**Hnatlang:** Community work. Free labour for common good.',
        '**Nula Rim:** Courtship system. Boy visits girl house evening.',
        '',
        '**5. Current Affairs 2025-26 MPSC**',
        '**Railway:** Bairabi-Sairang inaugurated 13 Sep 2025. 51.38 km. Rs 9,000 cr. Rajdhani June 2026.',
        '**Refugees:** 38,059 total. Myanmar 31,722 Chin, Bangladesh 1,769 Bawm, Manipur IDP 4,568 Kuki-Zo.',
        '**Health:** Rs 5 lakh cashless scheme launched 2025. Cancer Hospital Rs 700 cr Zemabawk.',
        '**Bana Kaih:** Rs 2.5 lakh handholding scheme. Entrepreneurship. Partner depts.',
        '**Power:** Aizawl Peak Power 110 MW battery Rs 2,400 cr. Hydro Tuirial 60MW.',
        '**Rubber:** 4.5 lakh saplings planted. 17,700 ha target Serchhip, Hnahthial, Mamit.',
        '**Literacy:** 91.3% 3rd India. 99%+ Khawzawl, Hnahthial districts.',
        '**Women:** 96.2% literacy highest India. 22% workforce. 9.6% Assembly 2023.',
        '**MPSC 2026:** 3,491 candidates. GCS 47 posts, GS 6. Prelims 20 July 2026.',
        '**Martyrs Day:** 20 Sep. MNF insurgency martyrs. State function.',
        '',
        '**6. Important Persons**',
        '**Laldenga:** MNF founder. 1st CM 1987. Peace Accord 1986.',
        '**Ch. Chhunga:** 1st CM UT 1972-77.',
        '**Lal Thanhawla:** CM 5 terms 1984-2018. Congress.',
        '**Zoramthanga:** CM 1998-2008, 2018-23. MNF.',
        '**Lalduhoma:** CM 2023. ZPM. Ex-IPS. Mizoram Security Act architect.',
        '**Brig T. Sailo:** 2nd CM 1978-84. People Conference.',
        '**MPSC Point:** Tlawmngaihna = selfless service. Chapchar Kut = March. Railway 2025. Refugees 38k.'
      ],
      english: [
        '**1. Festivals**',
        '**Mim Kut:** Aug-Sep. Maize festival. After harvest. Lalmanga legend.',
        '**Pawl Kut:** Dec-Jan. Straw festival. Post-harvest. 2 days.',
        '**Chapchar Kut:** March. Most popular. Jhum clearing after. 7 days. State festival.',
        '**Thalfavang Kut:** Nov. Weeding completed. Youth festival.',
        '**Christmas:** 25 Dec. Biggest. Church celebration. State holiday.',
        '**Anthurium Festival:** Sep Reiek. Tourism. Flower export.',
        '',
        '**2. Dances & Music**',
        '**Cheraw:** Bamboo dance. Men bamboo, women dance. Sarlamkai variant.',
        '**Khuallam:** Guest dance. Community. Cloth waving.',
        '**Chheihlam:** Squatting dance. Rice beer. Fast rhythm.',
        '**Chailam:** Mim Kut dance. Snake-like movement.',
        '**Sarlamkai:** War dance. Victory celebration.',
        '**Music:** Tingtang guitar, Dar drum, Phenglawng flute. Gospel strong.',
        '',
        '**3. Dress & Cuisine**',
        '**Dress:** Women - Puan wraparound, Kawrchei blouse. Men - coat, trousers. Tawlhlohpuan ceremonial.',
        '**Cuisine:** Bai veg stew, Sawhchiar rice-meat, Vawksa rep pork, Bamboo shoot, Sa-um fermented pork.',
        '**Beverages:** Zu rice beer traditional, now tea common.',
        '',
        '**4. Social System**',
        '**Tlawmngaihna:** Selfless service. Core Mizo ethic. Help without expectation.',
        '**Zawlbuk:** Bachelor dormitory. Abolished 1926. Moral education.',
        '**Hnatlang:** Community work. Free labour for common good.',
        '**Nula Rim:** Courtship system. Boy visits girl house evening.',
        '',
        '**5. Current Affairs 2025-26 MPSC**',
        '**Railway:** Bairabi-Sairang inaugurated 13 Sep 2025. 51.38 km. Rs 9,000 cr. Rajdhani June 2026.',
        '**Refugees:** 38,059 total. Myanmar 31,722 Chin, Bangladesh 1,769 Bawm, Manipur IDP 4,568 Kuki-Zo.',
        '**Health:** Rs 5 lakh cashless scheme launched 2025. Cancer Hospital Rs 700 cr Zemabawk.',
        '**Bana Kaih:** Rs 2.5 lakh handholding scheme. Entrepreneurship. Partner depts.',
        '**Power:** Aizawl Peak Power 110 MW battery Rs 2,400 cr. Hydro Tuirial 60MW.',
        '**Rubber:** 4.5 lakh saplings planted. 17,700 ha target Serchhip, Hnahthial, Mamit.',
        '**Literacy:** 91.3% 3rd India. 99%+ Khawzawl, Hnahthial districts.',
        '**Women:** 96.2% literacy highest India. 22% workforce. 9.6% Assembly 2023.',
        '**MPSC 2026:** 3,491 candidates. GCS 47 posts, GS 6. Prelims 20 July 2026.',
        '**Martyrs Day:** 20 Sep. MNF insurgency martyrs. State function.',
        '',
        '**6. Important Persons**',
        '**Laldenga:** MNF founder. 1st CM 1987. Peace Accord 1986.',
        '**Ch. Chhunga:** 1st CM UT 1972-77.',
        '**Lal Thanhawla:** CM 5 terms 1984-2018. Congress.',
        '**Zoramthanga:** CM 1998-2008, 2018-23. MNF.',
        '**Lalduhoma:** CM 2023. ZPM. Ex-IPS. Mizoram Security Act architect.',
        '**Brig T. Sailo:** 2nd CM 1978-84. People Conference.',
        '**MPSC Point:** Tlawmngaihna = selfless service. Chapchar Kut = March. Railway 2025. Refugees 38k.'
      ]
    }
  }
]

export default function MizoramGKPage() { 
  return (
    <SubjectPage 
      subjectName={{
        mizo: 'Mizoram GK',
        english: 'Mizoram GK'
      }}
      chapters={mizoramChapters}
      slug="mizoram-gk"
      
      backLink="/"
      testLink="/mizoram-gk/test"
      testTitle="Mizoram GK Mock Test"
      testDesc="MPSC Mizoram GK Chapter 1-5 atanga zawhna 50"
    />
  )
}