'use client'
import SubjectPage from '../components/SubjectPage'

const geographyChapters = [
  {
    id: 'geo-1',
    title: {
      mizo: 'Physical Geography: India',
      english: 'Physical Geography: India'
    },
    notes: {
      mizo: [
        '**1. India Location & Extent**',
        '**Latitudinal:** 8°4\'N to 37°6\'N. **Longitudinal:** 68°7\'E to 97°25\'E.',
        '**Area:** 32.8 lakh sq km. World 7th largest. 2.4% of world area.',
        '**Land Boundary:** 15,200 km. **Coastline:** 7,516.6 km including islands.',
        '**Tropic of Cancer:** 23°30\'N - Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, WB, Tripura, Mizoram 8 states.',
        '**IST:** 82°30\'E - Mirzapur, UP. GMT +5:30.',
        '**States:** 28. **UTs:** 8. Latest: J&K, Ladakh 2019.',
        '',
        '**2. Physiographic Divisions - 6**',
        '**A. Himalayas:** 2,400 km. Young fold mountains.',
        '   - **Himadri/Greater:** 6,000m+. Peaks: Mt Everest 8848m, Kanchenjunga 8586m, Nanga Parbat 8126m.',
        '   - **Himachal/Lesser:** 3,700-4,500m. Hill stations: Shimla, Mussoorie, Nainital.',
        '   - **Shiwalik/Outer:** 900-1,100m. Youngest. Dun valleys: Dehradun, Kotli.',
        '**B. Northern Plains:** 2,400 km length, 240-320 km width. Formed by Indus-Ganga-Brahmaputra.',
        '   - **Bhabar:** 8-16 km pebble belt. Rivers disappear.',
        '   - **Terai:** Marshy, malarial. Rice cultivation.',
        '   - **Bhangar:** Old alluvium. Kankar nodules.',
        '   - **Khadar:** New alluvium. Floodplains. Fertile.',
        '**C. Peninsular Plateau:** Oldest landmass. Gondwana land part. 16 lakh sq km.',
        '   - **Deccan Plateau:** Triangular. Black soil. Lava origin.',
        '   - **Malwa Plateau:** NW. Chambal ravines.',
        '   - **Chotanagpur:** Mineral rich. Jharkhand.',
        '**D. Indian Desert:** Thar Desert. Rajasthan. 2 lakh sq km. Luni river.',
        '**E. Coastal Plains:** East 1,100 km, West 1,500 km. East: Deltas. West: Estuaries.',
        '**F. Islands:** Andaman-Nicobar 572 islands. Lakshadweep 36 coral islands.',
        '',
        '**3. Drainage System**',
        '**Himalayan Rivers:** Perennial. Snow-fed.',
        '   - **Indus:** 2,900 km. Origin: Tibet Mansarovar. Tributaries: Jhelum, Chenab, Ravi, Beas, Sutlej.',
        '   - **Ganga:** 2,525 km. Origin: Gangotri. Tributaries: Yamuna, Ghaghara, Gandak, Kosi.',
        '   - **Brahmaputra:** 2,900 km. Origin: Tibet. Name: Tsangpo, Siang, Dihang.',
        '**Peninsular Rivers:** Seasonal. Rain-fed.',
        '   - **East Flowing:** Mahanadi 851km, Godavari 1465km (Dakshin Ganga), Krishna 1400km, Kaveri 800km.',
        '   - **West Flowing:** Narmada 1312km, Tapi 724km. Estuary. Rift valley.',
        '**MPSC Point:** Indus Water Treaty 1960 - India 20%, Pakistan 80%.',
        '',
        '**4. Climate**',
        '**Monsoon:** June-Sept. SW Monsoon. 75% rainfall.',
        '   - **Arabian Sea Branch:** Hits Kerala June 1. Heavy rain Western Ghats.',
        '   - **Bay of Bengal Branch:** Hits NE June 5. Mawsynram 11,872mm highest.',
        '**Seasons:** Winter Dec-Feb, Summer Mar-May, Monsoon June-Sept, Retreating Oct-Nov.',
        '**Jet Streams:** Westerly jet winter. Easterly jet summer. Monsoon control.',
        '**El Nino:** Pacific warm. Indian monsoon weak. Drought.',
        '**La Nina:** Pacific cool. Indian monsoon strong. Flood.',
        '',
        '**5. Soils of India**',
        '**Alluvial:** 43%. Northern Plains. NPK rich. Wheat, rice, sugarcane.',
        '**Black/Regur:** 15%. Deccan. Cotton soil. Maharashtra, Gujarat, MP.',
        '**Red:** 18%. TN, Karnataka, AP. Iron oxide. Poor fertility.',
        '**Laterite:** 3%. Western Ghats. Tea, coffee, cashew.',
        '**Desert:** Rajasthan. Sandy. Bajra.',
        '**Mountain:** J&K, HP, UK. Forest soil.',
        '',
        '**6. Natural Vegetation**',
        '**Tropical Evergreen:** 200cm+ rainfall. Western Ghats, NE. Mahogany, rosewood.',
        '**Tropical Deciduous:** 100-200cm. Monsoon forests. Sal, teak. 70% forests.',
        '**Thorn:** <50cm. Rajasthan, Gujarat. Kikar, babul.',
        '**Mangrove:** Deltas. Sundarbans largest. Royal Bengal Tiger.',
        '**Montane:** Himalayas. Pine, deodar, oak.'
      ],
      english: [
        '**1. India Location & Extent**',
        '**Latitudinal:** 8°4\'N to 37°6\'N. **Longitudinal:** 68°7\'E to 97°25\'E.',
        '**Area:** 32.8 lakh sq km. World 7th largest. 2.4% of world area.',
        '**Land Boundary:** 15,200 km. **Coastline:** 7,516.6 km including islands.',
        '**Tropic of Cancer:** 23°30\'N - Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, WB, Tripura, Mizoram 8 states.',
        '**IST:** 82°30\'E - Mirzapur, UP. GMT +5:30.',
        '**States:** 28. **UTs:** 8. Latest: J&K, Ladakh 2019.',
        '',
        '**2. Physiographic Divisions - 6**',
        '**A. Himalayas:** 2,400 km. Young fold mountains.',
        '   - **Himadri/Greater:** 6,000m+. Peaks: Mt Everest 8848m, Kanchenjunga 8586m, Nanga Parbat 8126m.',
        '   - **Himachal/Lesser:** 3,700-4,500m. Hill stations: Shimla, Mussoorie, Nainital.',
        '   - **Shiwalik/Outer:** 900-1,100m. Youngest. Dun valleys: Dehradun, Kotli.',
        '**B. Northern Plains:** 2,400 km length, 240-320 km width. Formed by Indus-Ganga-Brahmaputra.',
        '   - **Bhabar:** 8-16 km pebble belt. Rivers disappear.',
        '   - **Terai:** Marshy, malarial. Rice cultivation.',
        '   - **Bhangar:** Old alluvium. Kankar nodules.',
        '   - **Khadar:** New alluvium. Floodplains. Fertile.',
        '**C. Peninsular Plateau:** Oldest landmass. Gondwana land part. 16 lakh sq km.',
        '   - **Deccan Plateau:** Triangular. Black soil. Lava origin.',
        '   - **Malwa Plateau:** NW. Chambal ravines.',
        '   - **Chotanagpur:** Mineral rich. Jharkhand.',
        '**D. Indian Desert:** Thar Desert. Rajasthan. 2 lakh sq km. Luni river.',
        '**E. Coastal Plains:** East 1,100 km, West 1,500 km. East: Deltas. West: Estuaries.',
        '**F. Islands:** Andaman-Nicobar 572 islands. Lakshadweep 36 coral islands.',
        '',
        '**3. Drainage System**',
        '**Himalayan Rivers:** Perennial. Snow-fed.',
        '   - **Indus:** 2,900 km. Origin: Tibet Mansarovar. Tributaries: Jhelum, Chenab, Ravi, Beas, Sutlej.',
        '   - **Ganga:** 2,525 km. Origin: Gangotri. Tributaries: Yamuna, Ghaghara, Gandak, Kosi.',
        '   - **Brahmaputra:** 2,900 km. Origin: Tibet. Name: Tsangpo, Siang, Dihang.',
        '**Peninsular Rivers:** Seasonal. Rain-fed.',
        '   - **East Flowing:** Mahanadi 851km, Godavari 1465km (Dakshin Ganga), Krishna 1400km, Kaveri 800km.',
        '   - **West Flowing:** Narmada 1312km, Tapi 724km. Estuary. Rift valley.',
        '**MPSC Point:** Indus Water Treaty 1960 - India 20%, Pakistan 80%.',
        '',
        '**4. Climate**',
        '**Monsoon:** June-Sept. SW Monsoon. 75% rainfall.',
        '   - **Arabian Sea Branch:** Hits Kerala June 1. Heavy rain Western Ghats.',
        '   - **Bay of Bengal Branch:** Hits NE June 5. Mawsynram 11,872mm highest.',
        '**Seasons:** Winter Dec-Feb, Summer Mar-May, Monsoon June-Sept, Retreating Oct-Nov.',
        '**Jet Streams:** Westerly jet winter. Easterly jet summer. Monsoon control.',
        '**El Nino:** Pacific warm. Indian monsoon weak. Drought.',
        '**La Nina:** Pacific cool. Indian monsoon strong. Flood.',
        '',
        '**5. Soils of India**',
        '**Alluvial:** 43%. Northern Plains. NPK rich. Wheat, rice, sugarcane.',
        '**Black/Regur:** 15%. Deccan. Cotton soil. Maharashtra, Gujarat, MP.',
        '**Red:** 18%. TN, Karnataka, AP. Iron oxide. Poor fertility.',
        '**Laterite:** 3%. Western Ghats. Tea, coffee, cashew.',
        '**Desert:** Rajasthan. Sandy. Bajra.',
        '**Mountain:** J&K, HP, UK. Forest soil.',
        '',
        '**6. Natural Vegetation**',
        '**Tropical Evergreen:** 200cm+ rainfall. Western Ghats, NE. Mahogany, rosewood.',
        '**Tropical Deciduous:** 100-200cm. Monsoon forests. Sal, teak. 70% forests.',
        '**Thorn:** <50cm. Rajasthan, Gujarat. Kikar, babul.',
        '**Mangrove:** Deltas. Sundarbans largest. Royal Bengal Tiger.',
        '**Montane:** Himalayas. Pine, deodar, oak.'
      ]
    }
  },
   {
    id: 'geo-2',
    title: {
      mizo: 'World Geography: Physical',
      english: 'World Geography: Physical'
    },
    notes: {
      mizo: [
        '**1. Earth Structure**',
        '**Crust:** 5-70 km. Sial + Sima. Oceanic thinner 5-10km.',
        '**Mantle:** 2,900 km. Asthenosphere 100-400km. Magma. Convection currents.',
        '**Core:** 3,500 km. Outer liquid Fe-Ni. Inner solid 1,250km. Temp 5,000°C.',
        '**Mohorovicic Discontinuity:** Crust-Mantle boundary.',
        '**Gutenberg Discontinuity:** Mantle-Core boundary.',
        '',
        '**2. Plate Tectonics**',
        '**Theory:** Lithosphere 7 major + 20 minor plates. Float on asthenosphere.',
        '**Major Plates:** Pacific, North American, Eurasian, African, Indo-Australian, Antarctic, South American.',
        '**Boundaries:**',
        '   - **Divergent:** Mid-Atlantic Ridge. Sea-floor spreading. New crust.',
        '   - **Convergent:** Himalayas. Subduction. Fold mountains, volcanoes.',
        '   - **Transform:** San Andreas Fault. Earthquakes. No crust creation/destruction.',
        '**MPSC Point:** Indian Plate moving 5cm/year north. Himalayas rising 1cm/year.',
        '',
        '**3. Landforms**',
        '**Mountains:** Fold: Himalayas, Alps, Rockies. Block: Vosges, Black Forest. Volcanic: Fuji, Kilimanjaro.',
        '**Plateaus:** Deccan, Tibetan (highest), Colorado, Brazilian.',
        '**Plains:** Indo-Gangetic, Mississippi, Amazon, Nile Delta.',
        '**Deserts:** Hot: Sahara largest, Thar. Cold: Gobi, Ladakh. Coastal: Atacama driest.',
        '',
        '**4. Atmosphere**',
        '**Layers:**',
        '   - **Troposphere:** 0-18km. Weather. Temp decreases 6.5°C/km.',
        '   - **Stratosphere:** 18-50km. Ozone layer. UV absorption. Jet planes.',
        '   - **Mesosphere:** 50-80km. Coldest -90°C. Meteors burn.',
        '   - **Thermosphere:** 80-700km. Ionosphere. Aurora. ISS.',
        '   - **Exosphere:** 700km+. Satellites.',
        '**Composition:** N2 78%, O2 21%, Ar 0.93%, CO2 0.04%.',
        '',
        '**5. Oceanography**',
        '**Pacific:** Largest 168 mn sq km. Mariana Trench 11,034m deepest. Ring of Fire 75% volcanoes.',
        '**Atlantic:** S-shaped. Mid-Atlantic Ridge. Titanic sank.',
        '**Indian:** Warmest. Monsoon influence. 90°E Ridge.',
        '**Arctic:** Smallest. Ice-covered. North Pole.',
        '**Southern:** Antarctic circumpolar current.',
        '**Currents:** Gulf Stream warm, Labrador cold. El Nino warm, La Nina cold.',
        '**Tides:** Spring tide new/full moon. Neap tide quarter moon.',
        '',
        '**6. Climate Zones**',
        '**Tropical:** 0-23.5°. Hot, wet. Amazon, Congo, Indonesia.',
        '**Subtropical:** 23.5-35°. Hot summers. Mediterranean climate.',
        '**Temperate:** 35-66.5°. 4 seasons. Europe, USA.',
        '**Polar:** 66.5-90°. Ice caps. Tundra.',
        '**Koppen Classification:** A-Tropical, B-Dry, C-Temperate, D-Continental, E-Polar.',
        '',
        '**7. Natural Hazards**',
        '**Earthquake:** Richter Scale. Focus hypocenter. Epicenter surface. Japan, Indonesia, Chile high risk.',
        '**Volcano:** Ring of Fire Pacific. Types: Shield Hawaii, Composite Fuji, Cinder cone.',
        '**Tsunami:** Japan 2011, Indonesia 2004. 9.1 magnitude.',
        '**Cyclone:** Hurricane Atlantic, Typhoon Pacific, Cyclone Indian Ocean.'
      ],
      english: [
        '**1. Earth Structure**',
        '**Crust:** 5-70 km. Sial + Sima. Oceanic thinner 5-10km.',
        '**Mantle:** 2,900 km. Asthenosphere 100-400km. Magma. Convection currents.',
        '**Core:** 3,500 km. Outer liquid Fe-Ni. Inner solid 1,250km. Temp 5,000°C.',
        '**Mohorovicic Discontinuity:** Crust-Mantle boundary.',
        '**Gutenberg Discontinuity:** Mantle-Core boundary.',
        '',
        '**2. Plate Tectonics**',
        '**Theory:** Lithosphere 7 major + 20 minor plates. Float on asthenosphere.',
        '**Major Plates:** Pacific, North American, Eurasian, African, Indo-Australian, Antarctic, South American.',
        '**Boundaries:**',
        '   - **Divergent:** Mid-Atlantic Ridge. Sea-floor spreading. New crust.',
        '   - **Convergent:** Himalayas. Subduction. Fold mountains, volcanoes.',
        '   - **Transform:** San Andreas Fault. Earthquakes. No crust creation/destruction.',
        '**MPSC Point:** Indian Plate moving 5cm/year north. Himalayas rising 1cm/year.',
        '',
        '**3. Landforms**',
        '**Mountains:** Fold: Himalayas, Alps, Rockies. Block: Vosges, Black Forest. Volcanic: Fuji, Kilimanjaro.',
        '**Plateaus:** Deccan, Tibetan (highest), Colorado, Brazilian.',
        '**Plains:** Indo-Gangetic, Mississippi, Amazon, Nile Delta.',
        '**Deserts:** Hot: Sahara largest, Thar. Cold: Gobi, Ladakh. Coastal: Atacama driest.',
        '',
        '**4. Atmosphere**',
        '**Layers:**',
        '   - **Troposphere:** 0-18km. Weather. Temp decreases 6.5°C/km.',
        '   - **Stratosphere:** 18-50km. Ozone layer. UV absorption. Jet planes.',
        '   - **Mesosphere:** 50-80km. Coldest -90°C. Meteors burn.',
        '   - **Thermosphere:** 80-700km. Ionosphere. Aurora. ISS.',
        '   - **Exosphere:** 700km+. Satellites.',
        '**Composition:** N2 78%, O2 21%, Ar 0.93%, CO2 0.04%.',
        '',
        '**5. Oceanography**',
        '**Pacific:** Largest 168 mn sq km. Mariana Trench 11,034m deepest. Ring of Fire 75% volcanoes.',
        '**Atlantic:** S-shaped. Mid-Atlantic Ridge. Titanic sank.',
        '**Indian:** Warmest. Monsoon influence. 90°E Ridge.',
        '**Arctic:** Smallest. Ice-covered. North Pole.',
        '**Southern:** Antarctic circumpolar current.',
        '**Currents:** Gulf Stream warm, Labrador cold. El Nino warm, La Nina cold.',
        '**Tides:** Spring tide new/full moon. Neap tide quarter moon.',
        '',
        '**6. Climate Zones**',
        '**Tropical:** 0-23.5°. Hot, wet. Amazon, Congo, Indonesia.',
        '**Subtropical:** 23.5-35°. Hot summers. Mediterranean climate.',
        '**Temperate:** 35-66.5°. 4 seasons. Europe, USA.',
        '**Polar:** 66.5-90°. Ice caps. Tundra.',
        '**Koppen Classification:** A-Tropical, B-Dry, C-Temperate, D-Continental, E-Polar.',
        '',
        '**7. Natural Hazards**',
        '**Earthquake:** Richter Scale. Focus hypocenter. Epicenter surface. Japan, Indonesia, Chile high risk.',
        '**Volcano:** Ring of Fire Pacific. Types: Shield Hawaii, Composite Fuji, Cinder cone.',
        '**Tsunami:** Japan 2011, Indonesia 2004. 9.1 magnitude.',
        '**Cyclone:** Hurricane Atlantic, Typhoon Pacific, Cyclone Indian Ocean.'
      ]
    }
  },
   {
    id: 'geo-3',
    title: {
      mizo: 'Social Geography: India & World',
      english: 'Social Geography: India & World'
    },
    notes: {
      mizo: [
        '**1. Population India 2026**',
        '**Total:** 143 crore estimate. World largest. China lehpelh 2023.',
        '**Density:** 464 per sq km. Bihar highest 1106, Arunachal lowest 17.',
        '**Sex Ratio:** 1020 females/1000 males NFHS-5. Kerala 1084 highest.',
        '**Literacy:** 77.7%. Male 84.7%, Female 70.3%. Mizoram 91.3% 3rd.',
        '**Decadal Growth:** 17.7% 2001-11. Declining trend.',
        '**Urbanization:** 35% 2026. 2036 ah 40% target.',
        '',
        '**2. Population World 2026**',
        '**Total:** 8.2 billion. Growth rate 0.9%.',
        '**Top 5:** India 143cr, China 142cr, USA 34cr, Indonesia 28cr, Pakistan 24cr.',
        '**Density:** Bangladesh highest 1,265/sq km. Mongolia lowest 2/sq km.',
        '**Urbanization:** 57% world. Developed 80%, Developing 50%.',
        '**Ageing:** Japan 29% 65+, Italy 24%, India 7%.',
        '',
        '**3. Migration**',
        '**Types:** Internal, International. Voluntary, Forced.',
        '**India Internal:** 45 crore migrants 2011. Rural-Urban main. UP-Bihar to Maharashtra, Delhi, Gujarat.',
        '**Push Factors:** Unemployment, poverty, natural disasters, conflict.',
        '**Pull Factors:** Jobs, education, health, marriage.',
        '**International:** India diaspora 32 million largest. USA 4.5mn, UAE 3.5mn.',
        '**Refugees:** 38,059 Mizoram. Myanmar 31,722, Bangladesh 1,769, Manipur IDP 4,568.',
        '',
        '**4. Human Development**',
        '**HDI:** Life Expectancy + Education + Per Capita Income. UNDP.',
        '**India HDI 2025:** 0.685. Rank 132/193. Medium category.',
        '**Top:** Switzerland 0.962, Norway 0.961, Iceland 0.959.',
        '**Bottom:** South Sudan 0.385, Chad 0.394, Niger 0.400.',
        '**Gender Inequality Index:** India 0.490, Rank 108/193.',
        '**MPI India:** 11.28%. 13.5 crore escaped poverty 2016-21.',
        '',
        '**5. Settlements**',
        '**Rural:** 65% India. Villages 6.4 lakh. Dispersed, nucleated, linear patterns.',
        '**Urban:** 35% India. Cities 4,000+. Classification:',
        '   - **Class I:** 1 lakh+. 468 cities. 70% urban population.',
        '   - **Metropolitan:** 10 lakh+. 53 cities. Mumbai 2cr, Delhi 1.8cr.',
        '   - **Megacities:** 1 crore+. Mumbai, Delhi, Kolkata.',
        '**Urban Problems:** Slums 17%, traffic, pollution, water shortage.',
        '**Smart Cities:** 100 cities. Rs 48,000 cr. Surat, Indore top.',
        '',
        '**6. Tribes India**',
        '**ST Population:** 10.4 crore 8.6%. 705 tribes.',
        '**Major:** Gond 1.3cr, Bhil 1.2cr, Santhal 65L, Munda, Khasi.',
        '**PVTGs:** 75 groups. Sentinelese, Jarawa Andaman. Onge, Shompen.',
        '**Mizoram:** Mizo 94%. Hmar, Mara, Lai, Chakma. Sixth Schedule.',
        '**Constitutional Safeguards:** Article 244, 275, 330, 332, 338A.'
      ],
      english: [
        '**1. Population India 2026**',
        '**Total:** 143 crore estimate. World largest. Overtakes China 2023.',
        '**Density:** 464 per sq km. Bihar highest 1106, Arunachal lowest 17.',
        '**Sex Ratio:** 1020 females/1000 males NFHS-5. Kerala 1084 highest.',
        '**Literacy:** 77.7%. Male 84.7%, Female 70.3%. Mizoram 91.3% 3rd.',
        '**Decadal Growth:** 17.7% 2001-11. Declining trend.',
        '**Urbanization:** 35% 2026. 40% target by 2036.',
        '',
        '**2. Population World 2026**',
        '**Total:** 8.2 billion. Growth rate 0.9%.',
        '**Top 5:** India 143cr, China 142cr, USA 34cr, Indonesia 28cr, Pakistan 24cr.',
        '**Density:** Bangladesh highest 1,265/sq km. Mongolia lowest 2/sq km.',
        '**Urbanization:** 57% world. Developed 80%, Developing 50%.',
        '**Ageing:** Japan 29% 65+, Italy 24%, India 7%.',
        '',
        '**3. Migration**',
        '**Types:** Internal, International. Voluntary, Forced.',
        '**India Internal:** 45 crore migrants 2011. Rural-Urban main. UP-Bihar to Maharashtra, Delhi, Gujarat.',
        '**Push Factors:** Unemployment, poverty, natural disasters, conflict.',
        '**Pull Factors:** Jobs, education, health, marriage.',
        '**International:** India diaspora 32 million largest. USA 4.5mn, UAE 3.5mn.',
        '**Refugees:** 38,059 Mizoram. Myanmar 31,722, Bangladesh 1,769, Manipur IDP 4,568.',
        '',
        '**4. Human Development**',
        '**HDI:** Life Expectancy + Education + Per Capita Income. UNDP.',
        '**India HDI 2025:** 0.685. Rank 132/193. Medium category.',
        '**Top:** Switzerland 0.962, Norway 0.961, Iceland 0.959.',
        '**Bottom:** South Sudan 0.385, Chad 0.394, Niger 0.400.',
        '**Gender Inequality Index:** India 0.490, Rank 108/193.',
        '**MPI India:** 11.28%. 13.5 crore escaped poverty 2016-21.',
        '',
        '**5. Settlements**',
        '**Rural:** 65% India. Villages 6.4 lakh. Dispersed, nucleated, linear patterns.',
        '**Urban:** 35% India. Cities 4,000+. Classification:',
        '   - **Class I:** 1 lakh+. 468 cities. 70% urban population.',
        '   - **Metropolitan:** 10 lakh+. 53 cities. Mumbai 2cr, Delhi 1.8cr.',
        '   - **Megacities:** 1 crore+. Mumbai, Delhi, Kolkata.',
        '**Urban Problems:** Slums 17%, traffic, pollution, water shortage.',
        '**Smart Cities:** 100 cities. Rs 48,000 cr. Surat, Indore top.',
        '',
        '**6. Tribes India**',
        '**ST Population:** 10.4 crore 8.6%. 705 tribes.',
        '**Major:** Gond 1.3cr, Bhil 1.2cr, Santhal 65L, Munda, Khasi.',
        '**PVTGs:** 75 groups. Sentinelese, Jarawa Andaman. Onge, Shompen.',
        '**Mizoram:** Mizo 94%. Hmar, Mara, Lai, Chakma. Sixth Schedule.',
        '**Constitutional Safeguards:** Article 244, 275, 330, 332, 338A.'
      ]
    }
  },
     {
    id: 'geo-4',
    title: {
      mizo: 'Economic Geography: India & World',
      english: 'Economic Geography: India & World'
    },
    notes: {
      mizo: [
        '**1. Agriculture India**',
        '**Contribution:** 15% GDP, 42% employment. 86% marginal farmers <2 hectare.',
        '**Cropping Pattern:** Kharif June-Oct rice, cotton. Rabi Oct-Mar wheat, mustard. Zaid Mar-June watermelon.',
        '**Green Revolution:** 1966. HYV seeds, fertilizer, irrigation. Punjab, Haryana, UP. Wheat, rice.',
        '**Major Crops:**',
        '   - **Rice:** WB, UP, Punjab. 45% area. 120 MT. Kharif.',
        '   - **Wheat:** UP, Punjab, MP. 110 MT. Rabi. Green Revolution crop.',
        '   - **Sugarcane:** UP, Maharashtra. 400 MT. Tropical crop.',
        '   - **Cotton:** Gujarat, Maharashtra. Black soil. Kharif.',
        '   - **Tea:** Assam, WB. Slopes. 200cm rainfall.',
        '   - **Coffee:** Karnataka 70%. Western Ghats.',
        '**Irrigation:** 70% area. Canal 40%, Tube well 35%, Tank 10%.',
        '**Mizoram:** Jhum cultivation. Rice, maize, vegetables. Rubber 4.5 lakh saplings.',
        '',
        '**2. Minerals & Energy**',
        '**Iron Ore:** Odisha 50%, Jharkhand, Chhattisgarh, Karnataka. Hematite, magnetite.',
        '**Coal:** Jharkhand 30%, Odisha, Chhattisgarh. 319 billion tons. Gondwana coal.',
        '**Petroleum:** Mumbai High 60%, Assam, Gujarat. 4.5 billion tons. 30% domestic.',
        '**Natural Gas:** KG Basin, Assam. 1.3 trillion cubic m.',
        '**Bauxite:** Odisha 50%. Aluminium. Panchpatmali.',
        '**Mica:** Jharkhand 60%. Koderma. Insulator.',
        '**Nuclear:** Uranium Jharkhand, Meghalaya. Thorium Kerala, TN. 22 reactors 6,780 MW.',
        '**Renewable:** Solar 70 GW, Wind 45 GW, Hydro 46 GW. Target 500 GW 2030.',
        '',
        '**3. Industries**',
        '**Textile:** Mumbai, Ahmedabad, Coimbatore. Cotton. 2nd largest after China.',
        '**Iron & Steel:** Jamshedpur 1907, Bhilai, Rourkela, Durgapur. SAIL, Tata Steel.',
        '**Automobile:** Chennai Detroit of India, Pune, Gurgaon. 4th largest.',
        '**IT:** Bangalore Silicon Valley, Hyderabad, Pune. $200 bn export.',
        '**Pharma:** Hyderabad, Ahmedabad. 3rd largest volume. Generic drugs 20%.',
        '**Cement:** MP, Rajasthan, AP. 2nd largest after China.',
        '**Mizoram:** Handloom, bamboo, food processing. No major industry.',
        '',
        '**4. Transport**',
        '**Roads:** 63 lakh km 2nd largest. NH 1.4 lakh km. Golden Quadrilateral 5,846 km.',
        '**Railways:** 68,000 km 4th largest. 23 million passengers/day. 100% electrification 2024.',
        '   - **Mizoram:** Bairabi-Sairang 51.38 km. Rs 9,000 cr. Sept 2025 open. Rajdhani Express Delhi-Sairang June 2026.',
        '**Airways:** 137 airports. Delhi, Mumbai busiest. UDAN scheme.',
        '**Waterways:** 14,500 km. NW-1 Ganga 1,620 km. Sagar Mala project.',
        '**Ports:** 13 major. Kandla tidal, Mumbai largest, Chennai oldest.',
        '',
        '**5. World Agriculture**',
        '**Wheat:** China, India, Russia. Temperate grasslands. Prairies, Steppes, Pampas.',
        '**Rice:** China, India, Indonesia. Monsoon Asia. Paddy fields.',
        '**Maize:** USA, China, Brazil. Corn belt USA.',
        '**Cotton:** China, India, USA. Black soil, 210 frost-free days.',
        '**Coffee:** Brazil 40%, Vietnam, Colombia. Tropical highlands.',
        '**Tea:** China, India, Kenya. Slopes, 200cm rainfall.',
        '',
        '**6. World Minerals**',
        '**Iron:** Australia, Brazil, China. Pilbara, Carajas.',
        '**Coal:** China, USA, India. Appalachian, Ruhr.',
        '**Petroleum:** USA, Saudi, Russia. Middle East 60%. OPEC.',
        '**Gold:** China, Australia, Russia. Witwatersrand SA.',
        '**Diamond:** Russia, Botswana, Congo. Kimberley SA.',
        '**Copper:** Chile, Peru, China. Chuquicamata Chile largest.',
        '',
        '**7. World Industries**',
        '**Iron & Steel:** China 50%, India 2nd, Japan. Pittsburgh USA, Ruhr Germany.',
        '**Textile:** China, India, Bangladesh. Manchester UK historic.',
        '**Automobile:** China, USA, Japan, Germany. Detroit USA.',
        '**IT:** USA Silicon Valley, India Bangalore, China Shenzhen.',
        '**Shipbuilding:** Korea, China, Japan. Hyundai Korea largest.',
        '',
        '**8. World Transport**',
        '**Panama Canal:** Atlantic-Pacific. 82 km. USA built 1914.',
        '**Suez Canal:** Mediterranean-Red Sea. 193 km. Egypt 1869.',
        '**Trans-Siberian Railway:** Moscow-Vladivostok. 9,289 km longest.',
        '**Channel Tunnel:** UK-France. 50 km underwater.',
        '**Air Routes:** London-New York busiest. 1.2 mn passengers/year.'
      ],
      english: [
        '**1. Agriculture India**',
        '**Contribution:** 15% GDP, 42% employment. 86% marginal farmers <2 hectare.',
        '**Cropping Pattern:** Kharif June-Oct rice, cotton. Rabi Oct-Mar wheat, mustard. Zaid Mar-June watermelon.',
        '**Green Revolution:** 1966. HYV seeds, fertilizer, irrigation. Punjab, Haryana, UP. Wheat, rice.',
        '**Major Crops:**',
        '   - **Rice:** WB, UP, Punjab. 45% area. 120 MT. Kharif.',
        '   - **Wheat:** UP, Punjab, MP. 110 MT. Rabi. Green Revolution crop.',
        '   - **Sugarcane:** UP, Maharashtra. 400 MT. Tropical crop.',
        '   - **Cotton:** Gujarat, Maharashtra. Black soil. Kharif.',
        '   - **Tea:** Assam, WB. Slopes. 200cm rainfall.',
        '   - **Coffee:** Karnataka 70%. Western Ghats.',
        '**Irrigation:** 70% area. Canal 40%, Tube well 35%, Tank 10%.',
        '**Mizoram:** Jhum cultivation. Rice, maize, vegetables. Rubber 4.5 lakh saplings.',
        '',
        '**2. Minerals & Energy**',
        '**Iron Ore:** Odisha 50%, Jharkhand, Chhattisgarh, Karnataka. Hematite, magnetite.',
        '**Coal:** Jharkhand 30%, Odisha, Chhattisgarh. 319 billion tons. Gondwana coal.',
        '**Petroleum:** Mumbai High 60%, Assam, Gujarat. 4.5 billion tons. 30% domestic.',
        '**Natural Gas:** KG Basin, Assam. 1.3 trillion cubic m.',
        '**Bauxite:** Odisha 50%. Aluminium. Panchpatmali.',
        '**Mica:** Jharkhand 60%. Koderma. Insulator.',
        '**Nuclear:** Uranium Jharkhand, Meghalaya. Thorium Kerala, TN. 22 reactors 6,780 MW.',
        '**Renewable:** Solar 70 GW, Wind 45 GW, Hydro 46 GW. Target 500 GW 2030.',
        '',
        '**3. Industries**',
        '**Textile:** Mumbai, Ahmedabad, Coimbatore. Cotton. 2nd largest after China.',
        '**Iron & Steel:** Jamshedpur 1907, Bhilai, Rourkela, Durgapur. SAIL, Tata Steel.',
        '**Automobile:** Chennai Detroit of India, Pune, Gurgaon. 4th largest.',
        '**IT:** Bangalore Silicon Valley, Hyderabad, Pune. $200 bn export.',
        '**Pharma:** Hyderabad, Ahmedabad. 3rd largest volume. Generic drugs 20%.',
        '**Cement:** MP, Rajasthan, AP. 2nd largest after China.',
        '**Mizoram:** Handloom, bamboo, food processing. No major industry.',
        '',
        '**4. Transport**',
        '**Roads:** 63 lakh km 2nd largest. NH 1.4 lakh km. Golden Quadrilateral 5,846 km.',
        '**Railways:** 68,000 km 4th largest. 23 million passengers/day. 100% electrification 2024.',
        '   - **Mizoram:** Bairabi-Sairang 51.38 km. Rs 9,000 cr. Sept 2025 open. Rajdhani Express Delhi-Sairang June 2026.',
        '**Airways:** 137 airports. Delhi, Mumbai busiest. UDAN scheme.',
        '**Waterways:** 14,500 km. NW-1 Ganga 1,620 km. Sagar Mala project.',
        '**Ports:** 13 major. Kandla tidal, Mumbai largest, Chennai oldest.',
        '',
        '**5. World Agriculture**',
        '**Wheat:** China, India, Russia. Temperate grasslands. Prairies, Steppes, Pampas.',
        '**Rice:** China, India, Indonesia. Monsoon Asia. Paddy fields.',
        '**Maize:** USA, China, Brazil. Corn belt USA.',
        '**Cotton:** China, India, USA. Black soil, 210 frost-free days.',
        '**Coffee:** Brazil 40%, Vietnam, Colombia. Tropical highlands.',
        '**Tea:** China, India, Kenya. Slopes, 200cm rainfall.',
        '',
        '**6. World Minerals**',
        '**Iron:** Australia, Brazil, China. Pilbara, Carajas.',
        '**Coal:** China, USA, India. Appalachian, Ruhr.',
        '**Petroleum:** USA, Saudi, Russia. Middle East 60%. OPEC.',
        '**Gold:** China, Australia, Russia. Witwatersrand SA.',
        '**Diamond:** Russia, Botswana, Congo. Kimberley SA.',
        '**Copper:** Chile, Peru, China. Chuquicamata Chile largest.',
        '',
        '**7. World Industries**',
        '**Iron & Steel:** China 50%, India 2nd, Japan. Pittsburgh USA, Ruhr Germany.',
        '**Textile:** China, India, Bangladesh. Manchester UK historic.',
        '**Automobile:** China, USA, Japan, Germany. Detroit USA.',
        '**IT:** USA Silicon Valley, India Bangalore, China Shenzhen.',
        '**Shipbuilding:** Korea, China, Japan. Hyundai Korea largest.',
        '',
        '**8. World Transport**',
        '**Panama Canal:** Atlantic-Pacific. 82 km. USA built 1914.',
        '**Suez Canal:** Mediterranean-Red Sea. 193 km. Egypt 1869.',
        '**Trans-Siberian Railway:** Moscow-Vladivostok. 9,289 km longest.',
        '**Channel Tunnel:** UK-France. 50 km underwater.',
        '**Air Routes:** London-New York busiest. 1.2 mn passengers/year.'
      ]
    }
  }
]

export default function GeographyPage() {
  return (
    <SubjectPage 
      subjectName={{
        mizo: 'Geography',
        english: 'Geography'
      }}
      chapters={geographyChapters}
      slug="geography"
     
      backLink="/"
      testLink="/geography/test"
      testTitle="Geography Mock Test"
      testDesc="MPSC Geography Chapter 1-4 atanga zawhna 50"
    />
  )
} 