'use client'
import SubjectPage from '../components/SubjectPage'

const polityChapters = [
  {
    id: 'pol-1',
    title: {
      mizo: 'Chapter 1: Constitutional Background - Acts & Viceroys',
      english: 'Chapter 1: Constitutional Background - Acts & Viceroys'
    },
    notes: {
      mizo: [
        '**1. Regulating Act 1773 - Warren Hastings**',
        '**Governor-General Bengal:** Warren Hastings 1st. Council 4 members.',
        '**Supreme Court Calcutta 1774:** 1 Chief Justice + 3 judges. Sir Elijah Impey 1st CJ.',
        '**Court of Directors:** Company affairs report British Govt.',
        '**Defects:** No veto power Governor-General. No control Bombay/Madras.',
        '**MPSC Point:** 1st step constitutional development. Company political.',
        '',
        '**2. Pitt\'s India Act 1784 - Lord Cornwallis**',
        '**Dual Control:** Company = Commercial. Board of Control = Political 6 members.',
        '**Governor-General Council:** Reduced 4 to 3. Bombay/Madras subordinate.',
        '**MPSC Point:** Company Political affairs Govt control.',
        '',
        '**3. Charter Acts**',
        '**1793 Cornwallis:** Company trade monopoly 20 years extended.',
        '**1813 Lord Minto:** Trade monopoly ended except tea & China. Christian missionaries allowed. Rs 1 lakh education.',
        '**1833 Lord William Bentinck:** Governor-General of India. Bengal → India. Law member Macaulay. Slavery abolished 1843. Company commercial body ended. Govt body.',
        '**1853 Lord Dalhousie:** Legislative & Executive separated. 6 Legislative Councillors. Open competition Civil Service. Local representation added.',
        '',
        '**4. Govt of India Act 1858 - Lord Canning 1st Viceroy**',
        '**After 1857 Revolt:** Company rule ended. Crown direct rule.',
        '**Viceroy:** Lord Canning Governor-General + Viceroy Crown representative.',
        '**Secretary of State India:** British Cabinet member. India Council 15 members advisory.',
        '**Board of Control & Court Directors:** Abolished.',
        '',
        '**5. Indian Councils Acts**',
        '**1861 Lord Canning:** Portfolio system. Legislative Councils Bombay/Madras 1862. Non-official members nomination. Ordinance power Viceroy.',
        '**1892 Lord Lansdowne:** Indirect election introduced. Budget discussion allowed. Questions asked.',
        '**1909 Morley-Minto Lord Minto:** Separate Electorate Muslims. Communalism legal. Satyendra Sinha 1st Indian Viceroy Council.',
        '',
        '**6. Govt of India Act 1919 - Lord Chelmsford**',
        '**Montagu-Chelmsford Reforms:** Secretary State Montagu. Responsible Govt gradual.',
        '**Dyarchy Provinces:** Reserved - Governor. Transferred - Indian Ministers. Subjects divided.',
        '**Bicameral Centre:** Council of State + Legislative Assembly. Direct election.',
        '**Communal Electorate:** Sikhs, Indian Christians, Anglo-Indians, Europeans extended.',
        '**Defects:** Dyarchy failed. Finance reserved. Governor veto.',
        '',
        '**7. Govt of India Act 1935 - Lord Willingdon**',
        '**All-India Federation:** Provinces + Princely States. Never came. Princes no join.',
        '**Provincial Autonomy:** Dyarchy abolished provinces. Ministers responsible Legislature.',
        '**Dyarchy Centre:** Federal List, Provincial List, Concurrent List. Introduced but not worked.',
        '**Bicameral Provinces:** 6 provinces - Bengal, Bombay, Madras, Bihar, Assam, UP.',
        '**Federal Court 1937:** Delhi. 1 CJ + 2 judges. Disputes federal.',
        '**RBI 1935:** Reserve Bank established. Burma separated 1937.',
        '**Public Service Commission:** Federal PSC + Provincial PSC.',
        '**Emergency:** Governor-General special powers.',
        '**MPSC Point:** Longest Act 321 sections + 10 schedules. Blueprint Indian Constitution 60%.',
        '',
        '**8. Indian Independence Act 1947 - Lord Mountbatten**',
        '**20 Feb 1947:** Attlee announcement. Power transfer June 1948.',
        '**3 June Plan:** Mountbatten Plan. Partition India-Pakistan.',
        '**Act 18 July 1947:** 15 Aug 1947 Independence. 2 Dominions - India, Pakistan.',
        '**Provisions:** Crown rule end. Constituent Assembly sovereign. Governor-General each Dominion. Till Constitution 1950 Govt of India Act 1935 worked.',
        '**Radcliffe Line:** Boundary Commission. Punjab + Bengal partition.',
        '',
        '**9. Important Viceroys MPSC**',
        '**Lord Canning 1856-62:** 1857 Revolt. 1st Viceroy 1858. Universities Calcutta, Bombay, Madras 1857.',
        '**Lord Lytton 1876-80:** Royal Titles Act 1876. Delhi Durbar 1877 Queen Empress. Vernacular Press Act 1878. Arms Act 1878. 2nd Afghan War.',
        '**Lord Ripon 1880-84:** Liberal. Repeal Vernacular Press 1882. Local Self Govt 1882. 1st Factory Act 1881. Ilbert Bill controversy.',
        '**Lord Curzon 1899-1905:** Partition Bengal 1905. Ancient Monuments Act 1904. Police Commission. Universities Act 1904. Delhi Durbar 1903.',
        '**Lord Hardinge 1910-16:** Delhi Capital 1911. Partition Bengal annulled 1911. Bomb attack 1912.',
        '**Lord Chelmsford 1916-21:** 1919 Act. Rowlatt Act 1919. Jallianwala 1919. Khilafat NCM 1920.',
        '**Lord Irwin 1926-31:** Simon Commission 1927. Dandi March 1930. Gandhi-Irwin Pact 1931. 1st RTC 1930.',
        '**Lord Willingdon 1931-36:** 2nd RTC 1931. Communal Award 1932. Poona Pact 1932. 3rd RTC 1932.',
        '**Lord Linlithgow 1936-44:** Longest 8 years. 1935 Act. WWII 1939. Quit India 1942. Cripps Mission 1942.',
        '**Lord Wavell 1944-47:** Shimla Conference 1945. Cabinet Mission 1946. Interim Govt 1946. Direct Action Day 16 Aug 1946.',
        '**Lord Mountbatten 1947-48:** Last Viceroy. Partition. 1st Governor-General Independent India till June 1948.'
      ],
      english: [
        '**1. Regulating Act 1773 - Warren Hastings**',
        '**Governor-General Bengal:** Warren Hastings 1st. Council 4 members.',
        '**Supreme Court Calcutta 1774:** 1 Chief Justice + 3 judges. Sir Elijah Impey 1st CJ.',
        '**Court of Directors:** Company affairs report British Govt.',
        '**Defects:** No veto power Governor-General. No control Bombay/Madras.',
        '**MPSC Point:** 1st step constitutional development. Company political.',
        '',
        '**2. Pitt\'s India Act 1784 - Lord Cornwallis**',
        '**Dual Control:** Company = Commercial. Board of Control = Political 6 members.',
        '**Governor-General Council:** Reduced 4 to 3. Bombay/Madras subordinate.',
        '**MPSC Point:** Company Political affairs Govt control.',
        '',
        '**3. Charter Acts**',
        '**1793 Cornwallis:** Company trade monopoly 20 years extended.',
        '**1813 Lord Minto:** Trade monopoly ended except tea & China. Christian missionaries allowed. Rs 1 lakh education.',
        '**1833 Lord William Bentinck:** Governor-General of India. Bengal → India. Law member Macaulay. Slavery abolished 1843. Company commercial body ended. Govt body.',
        '**1853 Lord Dalhousie:** Legislative & Executive separated. 6 Legislative Councillors. Open competition Civil Service. Local representation added.',
        '',
        '**4. Govt of India Act 1858 - Lord Canning 1st Viceroy**',
        '**After 1857 Revolt:** Company rule ended. Crown direct rule.',
        '**Viceroy:** Lord Canning Governor-General + Viceroy Crown representative.',
        '**Secretary of State India:** British Cabinet member. India Council 15 members advisory.',
        '**Board of Control & Court Directors:** Abolished.',
        '',
        '**5. Indian Councils Acts**',
        '**1861 Lord Canning:** Portfolio system. Legislative Councils Bombay/Madras 1862. Non-official members nomination. Ordinance power Viceroy.',
        '**1892 Lord Lansdowne:** Indirect election introduced. Budget discussion allowed. Questions asked.',
        '**1909 Morley-Minto Lord Minto:** Separate Electorate Muslims. Communalism legal. Satyendra Sinha 1st Indian Viceroy Council.',
        '',
        '**6. Govt of India Act 1919 - Lord Chelmsford**',
        '**Montagu-Chelmsford Reforms:** Secretary State Montagu. Responsible Govt gradual.',
        '**Dyarchy Provinces:** Reserved - Governor. Transferred - Indian Ministers. Subjects divided.',
        '**Bicameral Centre:** Council of State + Legislative Assembly. Direct election.',
        '**Communal Electorate:** Sikhs, Indian Christians, Anglo-Indians, Europeans extended.',
        '**Defects:** Dyarchy failed. Finance reserved. Governor veto.',
        '',
        '**7. Govt of India Act 1935 - Lord Willingdon**',
        '**All-India Federation:** Provinces + Princely States. Never came. Princes no join.',
        '**Provincial Autonomy:** Dyarchy abolished provinces. Ministers responsible Legislature.',
        '**Dyarchy Centre:** Federal List, Provincial List, Concurrent List. Introduced but not worked.',
        '**Bicameral Provinces:** 6 provinces - Bengal, Bombay, Madras, Bihar, Assam, UP.',
        '**Federal Court 1937:** Delhi. 1 CJ + 2 judges. Disputes federal.',
        '**RBI 1935:** Reserve Bank established. Burma separated 1937.',
        '**Public Service Commission:** Federal PSC + Provincial PSC.',
        '**Emergency:** Governor-General special powers.',
        '**MPSC Point:** Longest Act 321 sections + 10 schedules. Blueprint Indian Constitution 60%.',
        '',
        '**8. Indian Independence Act 1947 - Lord Mountbatten**',
        '**20 Feb 1947:** Attlee announcement. Power transfer June 1948.',
        '**3 June Plan:** Mountbatten Plan. Partition India-Pakistan.',
        '**Act 18 July 1947:** 15 Aug 1947 Independence. 2 Dominions - India, Pakistan.',
        '**Provisions:** Crown rule end. Constituent Assembly sovereign. Governor-General each Dominion. Till Constitution 1950 Govt of India Act 1935 worked.',
        '**Radcliffe Line:** Boundary Commission. Punjab + Bengal partition.',
        '',
        '**9. Important Viceroys MPSC**',
        '**Lord Canning 1856-62:** 1857 Revolt. 1st Viceroy 1858. Universities Calcutta, Bombay, Madras 1857.',
        '**Lord Lytton 1876-80:** Royal Titles Act 1876. Delhi Durbar 1877 Queen Empress. Vernacular Press Act 1878. Arms Act 1878. 2nd Afghan War.',
        '**Lord Ripon 1880-84:** Liberal. Repeal Vernacular Press 1882. Local Self Govt 1882. 1st Factory Act 1881. Ilbert Bill controversy.',
        '**Lord Curzon 1899-1905:** Partition Bengal 1905. Ancient Monuments Act 1904. Police Commission. Universities Act 1904. Delhi Durbar 1903.',
        '**Lord Hardinge 1910-16:** Delhi Capital 1911. Partition Bengal annulled 1911. Bomb attack 1912.',
        '**Lord Chelmsford 1916-21:** 1919 Act. Rowlatt Act 1919. Jallianwala 1919. Khilafat NCM 1920.',
        '**Lord Irwin 1926-31:** Simon Commission 1927. Dandi March 1930. Gandhi-Irwin Pact 1931. 1st RTC 1930.',
        '**Lord Willingdon 1931-36:** 2nd RTC 1931. Communal Award 1932. Poona Pact 1932. 3rd RTC 1932.',
        '**Lord Linlithgow 1936-44:** Longest 8 years. 1935 Act. WWII 1939. Quit India 1942. Cripps Mission 1942.',
        '**Lord Wavell 1944-47:** Shimla Conference 1945. Cabinet Mission 1946. Interim Govt 1946. Direct Action Day 16 Aug 1946.',
        '**Lord Mountbatten 1947-48:** Last Viceroy. Partition. 1st Governor-General Independent India till June 1948.'
      ]
    }
  },
   {
    id: 'pol-2',
    title: {
      mizo: 'Chapter 2: Constitution Making',
      english: 'Chapter 2: Constitution Making'
    },
    notes: {
      mizo: [
        '**1. Demand & Formation**',
        '**M.N. Roy 1934:** 1st demand Constituent Assembly. Communist leader.',
        '**INC Lucknow 1935:** Official demand. Jawaharlal Nehru.',
        '**August Offer 1940:** Linlithgow. Dominion status post-war. Expansion Viceroy Council. Rejected.',
        '**Cripps Mission 1942:** Stafford Cripps. Dominion status + Constituent Assembly post-war. Congress rejected - no immediate power. Muslim League rejected - no Pakistan.',
        '**Cabinet Mission 1946:** Pethick Lawrence, Stafford Cripps, A.V. Alexander. 16 May 1946.',
        '   - **Rejected Pakistan:** But grouping allowed. Weak centre. Provinces strong.',
        '   - **Constituent Assembly:** 389 members. 296 British India, 93 Princely States.',
        '',
        '**2. Constituent Assembly**',
        '**Election July-Aug 1946:** Indirect. Provincial Assemblies elected. 1 per 10 lakh population.',
        '**Seats:** Congress 208, Muslim League 73, Others 15. Princely 93 no join initially.',
        '**First Meeting 9 Dec 1946:** Sachchidananda Sinha temporary President. Boycott Muslim League.',
        '**11 Dec 1946:** Dr Rajendra Prasad President. H.C. Mukherjee Vice-President.',
        '**13 Dec 1946:** Objective Resolution Nehru. Preamble basis.',
        '**22 July 1947:** National Flag adopted. 24 Jan 1950 National Anthem + Song.',
        '**Partition Effect:** 299 members left. 229 provinces, 70 princely.',
        '',
        '**3. Committees**',
        '**Drafting Committee 29 Aug 1947:** Chairman Dr B.R. Ambedkar. Father Indian Constitution.',
        '   - **Members:** N. Gopalaswami Ayyangar, Alladi Krishnaswami Ayyar, K.M. Munshi, Syed Mohammad Saadullah, N. Madhava Rau, T.T. Krishnamachari replaced D.P. Khaitan died.',
        '**Union Powers:** Jawaharlal Nehru. **Union Constitution:** Nehru.',
        '**Provincial Constitution:** Sardar Patel. **States:** Patel.',
        '**Fundamental Rights:** J.B. Kripalani. **Minorities:** H.C. Mukherjee.',
        '**Rules of Procedure:** Rajendra Prasad. **Steering:** Prasad.',
        '',
        '**4. Enactment Timeline**',
        '**Constitutional Advisor:** B.N. Rau. Prepared draft Oct 1947. Visited USA, Canada, Ireland, UK.',
        '**Draft 1:** Feb 1948 published. 8 months public discussion.',
        '**Draft 2:** Oct 1948. Drafting Committee revised.',
        '**3 Readings:** 1st Nov 1948 general, 2nd Nov 1948-17 Oct 1949 clause by clause, 3rd Nov 1949 final.',
        '**Total Time:** 2 years 11 months 18 days. 11 sessions. 165 sitting days. 114 days Constitution draft.',
        '**Cost:** Rs 64 lakh. **Pages:** 251 parchment. **Articles:** 395 original. Now 470.',
        '**Calligraphy:** Prem Behari Narain Raizada. Italics. 6 months. No fee, wrote name end.',
        '**Decoration:** Nandalal Bose Shantiniketan. 22 parts illustrated. Borders Vedic to Modern.',
        '**Hindi Translation:** Vasant Krishan Vaidya. Calligraphed Vasant Vaidya.',
        '',
        '**5. Enforcement**',
        '**26 Nov 1949:** Adoption. Some provisions immediate - Citizenship, Elections, Provisional Parliament.',
        '**26 Jan 1950:** Full enforcement. Chosen Purna Swaraj Day 1930 Lahore.',
        '**26 Jan:** Republic Day. Dr Rajendra Prasad 1st President. Govt of India Act 1935 repealed.',
        '**MPSC Point:** Ambedkar Chairman Drafting. B.N. Rau Constitutional Advisor. 26 Nov Constitution Day. 26 Jan Republic Day.'
      ],
      english: [
        '**1. Demand & Formation**',
        '**M.N. Roy 1934:** 1st demand Constituent Assembly. Communist leader.',
        '**INC Lucknow 1935:** Official demand. Jawaharlal Nehru.',
        '**August Offer 1940:** Linlithgow. Dominion status post-war. Expansion Viceroy Council. Rejected.',
        '**Cripps Mission 1942:** Stafford Cripps. Dominion status + Constituent Assembly post-war. Congress rejected - no immediate power. Muslim League rejected - no Pakistan.',
        '**Cabinet Mission 1946:** Pethick Lawrence, Stafford Cripps, A.V. Alexander. 16 May 1946.',
        '   - **Rejected Pakistan:** But grouping allowed. Weak centre. Provinces strong.',
        '   - **Constituent Assembly:** 389 members. 296 British India, 93 Princely States.',
        '',
        '**2. Constituent Assembly**',
        '**Election July-Aug 1946:** Indirect. Provincial Assemblies elected. 1 per 10 lakh population.',
        '**Seats:** Congress 208, Muslim League 73, Others 15. Princely 93 no join initially.',
        '**First Meeting 9 Dec 1946:** Sachchidananda Sinha temporary President. Boycott Muslim League.',
        '**11 Dec 1946:** Dr Rajendra Prasad President. H.C. Mukherjee Vice-President.',
        '**13 Dec 1946:** Objective Resolution Nehru. Preamble basis.',
        '**22 July 1947:** National Flag adopted. 24 Jan 1950 National Anthem + Song.',
        '**Partition Effect:** 299 members left. 229 provinces, 70 princely.',
        '',
        '**3. Committees**',
        '**Drafting Committee 29 Aug 1947:** Chairman Dr B.R. Ambedkar. Father Indian Constitution.',
        '   - **Members:** N. Gopalaswami Ayyangar, Alladi Krishnaswami Ayyar, K.M. Munshi, Syed Mohammad Saadullah, N. Madhava Rau, T.T. Krishnamachari replaced D.P. Khaitan died.',
        '**Union Powers:** Jawaharlal Nehru. **Union Constitution:** Nehru.',
        '**Provincial Constitution:** Sardar Patel. **States:** Patel.',
        '**Fundamental Rights:** J.B. Kripalani. **Minorities:** H.C. Mukherjee.',
        '**Rules of Procedure:** Rajendra Prasad. **Steering:** Prasad.',
        '',
        '**4. Enactment Timeline**',
        '**Constitutional Advisor:** B.N. Rau. Prepared draft Oct 1947. Visited USA, Canada, Ireland, UK.',
        '**Draft 1:** Feb 1948 published. 8 months public discussion.',
        '**Draft 2:** Oct 1948. Drafting Committee revised.',
        '**3 Readings:** 1st Nov 1948 general, 2nd Nov 1948-17 Oct 1949 clause by clause, 3rd Nov 1949 final.',
        '**Total Time:** 2 years 11 months 18 days. 11 sessions. 165 sitting days. 114 days Constitution draft.',
        '**Cost:** Rs 64 lakh. **Pages:** 251 parchment. **Articles:** 395 original. Now 470.',
        '**Calligraphy:** Prem Behari Narain Raizada. Italics. 6 months. No fee, wrote name end.',
        '**Decoration:** Nandalal Bose Shantiniketan. 22 parts illustrated. Borders Vedic to Modern.',
        '**Hindi Translation:** Vasant Krishan Vaidya. Calligraphed Vasant Vaidya.',
        '',
        '**5. Enforcement**',
        '**26 Nov 1949:** Adoption. Some provisions immediate - Citizenship, Elections, Provisional Parliament.',
        '**26 Jan 1950:** Full enforcement. Chosen Purna Swaraj Day 1930 Lahore.',
        '**26 Jan:** Republic Day. Dr Rajendra Prasad 1st President. Govt of India Act 1935 repealed.',
        '**MPSC Point:** Ambedkar Chairman Drafting. B.N. Rau Constitutional Advisor. 26 Nov Constitution Day. 26 Jan Republic Day.'
      ]
    }
  },
     {
    id: 'pol-3',
    title: {
      mizo: 'Chapter 3: Preamble',
      english: 'Chapter 3: Preamble'
    },
    notes: {
      mizo: [
        '**1. Text & Amendment**',
        '**Original 1949:** SOVEREIGN DEMOCRATIC REPUBLIC.',
        '**42nd Amendment 1976:** Added SOCIALIST SECULAR INTEGRITY. Indira Gandhi. Mini Constitution.',
        '**Present:** SOVEREIGN SOCIALIST SECULAR DEMOCRATIC REPUBLIC.',
        '',
        '**2. Key Words Meaning**',
        '**WE, THE PEOPLE:** Constitution from people. Not King/Parliament. Popular sovereignty.',
        '**Sovereign:** Internal + External independent. No authority above. UN member. Can acquire/cede territory.',
        '**Socialist:** Democratic socialism. Not Communist. Mixed economy. Public + Private. 42nd added.',
        '**Secular:** No state religion. Sarva Dharma Sambhava. Art 25-28. Positive secularism. 42nd added.',
        '**Democratic:** Govt by people. Direct + Indirect. Universal adult franchise Art 326. Parliamentary. Responsible Govt.',
        '**Republic:** Head elected. President indirect. No hereditary. 5 years term.',
        '',
        '**3. Objectives**',
        '**JUSTICE:** Social - no discrimination caste/religion. Economic - no wealth concentration Art 39. Political - equal vote Art 326.',
        '**LIBERTY:** Thought, Expression, Belief, Faith, Worship. Art 19-22. Not absolute. Reasonable restrictions.',
        '**EQUALITY:** Status + Opportunity. Art 14-18. Rule of law. No privilege. Protective discrimination allowed.',
        '**FRATERNITY:** Brotherhood. Dignity individual + Unity integrity Nation. Integrity added 42nd.',
        '',
        '**4. Nature & Status**',
        '**Berubari Union 1960:** Not part Constitution. SC.',
        '**Kesavananda Bharati 1973:** Part of Constitution. Basic Structure. Can amend but not basic features.',
        '**LIC of India 1995:** Integral part. Amendable subject to basic structure.',
        '**Objective Resolution:** Nehru 13 Dec 1946. Preamble based. India Independent Sovereign Republic. Justice, Equality, Liberty. Adequate safeguards minorities.',
        '**MPSC Point:** 42nd added 3 words. Kesavananda basic structure. Nehru Objective Resolution.'
      ],
      english: [
        '**1. Text & Amendment**',
        '**Original 1949:** SOVEREIGN DEMOCRATIC REPUBLIC.',
        '**42nd Amendment 1976:** Added SOCIALIST SECULAR INTEGRITY. Indira Gandhi. Mini Constitution.',
        '**Present:** SOVEREIGN SOCIALIST SECULAR DEMOCRATIC REPUBLIC.',
        '',
        '**2. Key Words Meaning**',
        '**WE, THE PEOPLE:** Constitution from people. Not King/Parliament. Popular sovereignty.',
        '**Sovereign:** Internal + External independent. No authority above. UN member. Can acquire/cede territory.',
        '**Socialist:** Democratic socialism. Not Communist. Mixed economy. Public + Private. 42nd added.',
        '**Secular:** No state religion. Sarva Dharma Sambhava. Art 25-28. Positive secularism. 42nd added.',
        '**Democratic:** Govt by people. Direct + Indirect. Universal adult franchise Art 326. Parliamentary. Responsible Govt.',
        '**Republic:** Head elected. President indirect. No hereditary. 5 years term.',
        '',
        '**3. Objectives**',
        '**JUSTICE:** Social - no discrimination caste/religion. Economic - no wealth concentration Art 39. Political - equal vote Art 326.',
        '**LIBERTY:** Thought, Expression, Belief, Faith, Worship. Art 19-22. Not absolute. Reasonable restrictions.',
        '**EQUALITY:** Status + Opportunity. Art 14-18. Rule of law. No privilege. Protective discrimination allowed.',
        '**FRATERNITY:** Brotherhood. Dignity individual + Unity integrity Nation. Integrity added 42nd.',
        '',
        '**4. Nature & Status**',
        '**Berubari Union 1960:** Not part Constitution. SC.',
        '**Kesavananda Bharati 1973:** Part of Constitution. Basic Structure. Can amend but not basic features.',
        '**LIC of India 1995:** Integral part. Amendable subject to basic structure.',
        '**Objective Resolution:** Nehru 13 Dec 1946. Preamble based. India Independent Sovereign Republic. Justice, Equality, Liberty. Adequate safeguards minorities.',
        '**MPSC Point:** 42nd added 3 words. Kesavananda basic structure. Nehru Objective Resolution.'
      ]
    }
  },
  {
    id: 'pol-4',
    title: {
      mizo: 'Chapter 4: Fundamental Rights Art 12-35',
      english: 'Chapter 4: Fundamental Rights Art 12-35'
    },
    notes: {
      mizo: [
        '**1. Art 12-13 Definition**',
        '**Art 12 State:** Govt + Parliament + State Leg + Local authority + Other authority. Ajay Hasia 1981 test - deep pervasive control.',
        '**Art 13 Laws Inconsistent:** Judicial Review. Pre-Constitution void. Post-Constitution void ab initio. Doctrine Eclipse, Severability, Waiver no.',
        '',
        '**2. Right to Equality Art 14-18**',
        '**Art 14:** Equality before law British - no privilege. Equal protection laws American - equals treated equal. Reasonable classification - intelligible differentia + rational nexus.',
        '**Art 15:** Prohibition discrimination religion, race, caste, sex, place birth. Art 15(3) women/children, 15(4) SEBC 1st 1951, 15(5) education 93rd 2005, 15(6) EWS 103rd 2019.',
        '**Art 16:** Equality public employment. Domicile no ground. Art 16(4) reservation SC/ST/OBC. 16(4A) promotion SC/ST 77th 1995. 16(4B) carry forward 81st 2000. 16(6) EWS 10% 103rd 2019.',
        '**Art 17:** Untouchability abolished. Civil Rights Act 1955. Punishable.',
        '**Art 18:** Titles abolished. Bharat Ratna, Padma not title Balaji 1996. Foreign titles need President consent.',
        '',
        '**3. Right to Freedom Art 19-22**',
        '**Art 19(1):** 6 freedoms - Speech Art 19(1)(a), Assembly (b) peaceful unarmed, Association (c), Movement (d) India, Residence (e), Profession (g). Art 19(1)(f) Property deleted 44th 1978 now Art 300A.',
        '**Restrictions Art 19(2-6):** Sovereignty integrity, Security state, Friendly relations foreign, Public order, Decency morality, Contempt court, Defamation, Incitement offence.',
        '**Art 20:** Ex-post facto - no higher punishment. Double jeopardy - no punish twice same offence. Self-incrimination - no compel witness against self.',
        '**Art 21:** Life & Personal Liberty. Gopalan 1950 procedure established law. Maneka 1978 due reasonable fair just. Expansive - Privacy Puttaswamy 2017, Livelihood, Shelter, Health, Education, Clean env, Speedy trial.',
        '**Art 21A:** RTE 6-14 years free compulsory. 86th 2002. RTE Act 2009. 25% private schools EWS.',
        '**Art 22:** Arrest protection. Informed grounds, Lawyer, Magistrate 24hrs, Not extended. Preventive Detention - 3 months max, Advisory Board, Communicate grounds.',
        '',
        '**4. Art 23-24 Exploitation**',
        '**Art 23:** Traffic human, Begar forced labour prohibited. Exception public purpose. Immoral Traffic Act 1956, Bonded Labour Act 1976.',
        '**Art 24:** Child labour <14 factories, mines, hazardous. Child Labour Amendment 2016 - all occupations except family.',
        '',
        '**5. Art 25-28 Religion**',
        '**Art 25:** Freedom conscience, profess, practice, propagate. Public order, morality, health, other FR. Sikhs kirpan allowed.',
        '**Art 26:** Denomination manage religious affairs, establish institutions, own property, administer.',
        '**Art 27:** No tax religious promotion. Fee allowed.',
        '**Art 28:** No religious instruction state institutions. Aided institutions no compel.',
        '',
        '**6. Art 29-30 Cultural**',
        '**Art 29:** Minority language script culture conserve. No discrimination admission state institutions.',
        '**Art 30:** Minorities establish administer educational institutions. TMA Pai 2002 - unaided no regulation admission except merit.',
        '',
        '**7. Art 32 Remedies**',
        '**Heart & Soul Ambedkar:** SC enforce FR. Writs 5 - Habeas Corpus produce body, Mandamus we command, Prohibition higher to lower stop, Certiorari quash, Quo Warranto what authority.',
        '**Art 226 HC:** Writs FR + legal rights. Wider than SC.',
        '**PIL:** Public Interest Litigation. Hussainara Khatoon 1979, S.P. Gupta 1981. Locus standi relaxed.',
        '**MPSC Point:** Art 21 most important. Art 32 heart soul. Art 19(1)(f) deleted 44th. EWS 103rd.'
      ],
      english: [
        '**1. Art 12-13 Definition**',
        '**Art 12 State:** Govt + Parliament + State Leg + Local authority + Other authority. Ajay Hasia 1981 test - deep pervasive control.',
        '**Art 13 Laws Inconsistent:** Judicial Review. Pre-Constitution void. Post-Constitution void ab initio. Doctrine Eclipse, Severability, Waiver no.',
        '',
        '**2. Right to Equality Art 14-18**',
        '**Art 14:** Equality before law British - no privilege. Equal protection laws American - equals treated equal. Reasonable classification - intelligible differentia + rational nexus.',
        '**Art 15:** Prohibition discrimination religion, race, caste, sex, place birth. Art 15(3) women/children, 15(4) SEBC 1st 1951, 15(5) education 93rd 2005, 15(6) EWS 103rd 2019.',
        '**Art 16:** Equality public employment. Domicile no ground. Art 16(4) reservation SC/ST/OBC. 16(4A) promotion SC/ST 77th 1995. 16(4B) carry forward 81st 2000. 16(6) EWS 10% 103rd 2019.',
        '**Art 17:** Untouchability abolished. Civil Rights Act 1955. Punishable.',
        '**Art 18:** Titles abolished. Bharat Ratna, Padma not title Balaji 1996. Foreign titles need President consent.',
        '',
        '**3. Right to Freedom Art 19-22**',
        '**Art 19(1):** 6 freedoms - Speech Art 19(1)(a), Assembly (b) peaceful unarmed, Association (c), Movement (d) India, Residence (e), Profession (g). Art 19(1)(f) Property deleted 44th 1978 now Art 300A.',
        '**Restrictions Art 19(2-6):** Sovereignty integrity, Security state, Friendly relations foreign, Public order, Decency morality, Contempt court, Defamation, Incitement offence.',
        '**Art 20:** Ex-post facto - no higher punishment. Double jeopardy - no punish twice same offence. Self-incrimination - no compel witness against self.',
        '**Art 21:** Life & Personal Liberty. Gopalan 1950 procedure established law. Maneka 1978 due reasonable fair just. Expansive - Privacy Puttaswamy 2017, Livelihood, Shelter, Health, Education, Clean env, Speedy trial.',
        '**Art 21A:** RTE 6-14 years free compulsory. 86th 2002. RTE Act 2009. 25% private schools EWS.',
        '**Art 22:** Arrest protection. Informed grounds, Lawyer, Magistrate 24hrs, Not extended. Preventive Detention - 3 months max, Advisory Board, Communicate grounds.',
        '',
        '**4. Art 23-24 Exploitation**',
        '**Art 23:** Traffic human, Begar forced labour prohibited. Exception public purpose. Immoral Traffic Act 1956, Bonded Labour Act 1976.',
        '**Art 24:** Child labour <14 factories, mines, hazardous. Child Labour Amendment 2016 - all occupations except family.',
        '',
        '**5. Art 25-28 Religion**',
        '**Art 25:** Freedom conscience, profess, practice, propagate. Public order, morality, health, other FR. Sikhs kirpan allowed.',
        '**Art 26:** Denomination manage religious affairs, establish institutions, own property, administer.',
        '**Art 27:** No tax religious promotion. Fee allowed.',
        '**Art 28:** No religious instruction state institutions. Aided institutions no compel.',
        '',
        '**6. Art 29-30 Cultural**',
        '**Art 29:** Minority language script culture conserve. No discrimination admission state institutions.',
        '**Art 30:** Minorities establish administer educational institutions. TMA Pai 2002 - unaided no regulation admission except merit.',
        '',
        '**7. Art 32 Remedies**',
        '**Heart & Soul Ambedkar:** SC enforce FR. Writs 5 - Habeas Corpus produce body, Mandamus we command, Prohibition higher to lower stop, Certiorari quash, Quo Warranto what authority.',
        '**Art 226 HC:** Writs FR + legal rights. Wider than SC.',
        '**PIL:** Public Interest Litigation. Hussainara Khatoon 1979, S.P. Gupta 1981. Locus standi relaxed.',
        '**MPSC Point:** Art 21 most important. Art 32 heart soul. Art 19(1)(f) deleted 44th. EWS 103rd.'
      ]
    }
  },
  {
    id: 'pol-5',
    title: {
      mizo: 'Chapter 5: Union & Its Territory Art 1-4',
      english: 'Chapter 5: Union & Its Territory Art 1-4'
    },
    notes: {
      mizo: [
        '**1. Art 1 Name & Territory**',
        '**Art 1(1):** India, that is Bharat, shall be Union of States.',
        '**Art 1(2):** States + Union Territories. **Art 1(3):** Territory = States + UTs + Acquired.',
        '**Union of States:** Indestructible Union of destructible States. Ambedkar. USA destructible Union indestructible States.',
        '**Present:** 28 States + 8 UTs = 36. J&K reorganised 31 Oct 2019. J&K UT + Ladakh UT.',
        '',
        '**2. Art 2 Admission New States**',
        '**Parliament power:** Admit new states. Sikkim 36th 26 Apr 1975 35th Amendment.',
        '**Art 3 Formation:** Parliament law form new state, alter area, boundaries, name.',
        '**Procedure:** President recommendation. State Legislature opinion refer - not binding. Simple majority Parliament.',
        '**New States:** Andhra 1953 1st linguistic, Gujarat/Maharashtra 1960, Nagaland 1963, Haryana 1966, Himachal 1971, Manipur/Tripura/Meghalaya 1972, Sikkim 1975, Mizoram/Arunachal 1987, Goa 1987, Chhattisgarh/Uttarakhand/Jharkhand 2000, Telangana 2014.',
        '',
        '**3. Art 4 Laws Amendment**',
        '**Art 4:** Laws Art 2-3 not amendment Art 368. Simple majority. No special majority needed.',
        '**Cession Territory:** Berubari Union 1960 SC. Cession need Constitutional Amendment. 9th Amendment 1960.',
        '**MPSC Point:** India Union not Federation. States no right secede. 28 States 8 UTs 2026.'
      ],
      english: [
        '**1. Art 1 Name & Territory**',
        '**Art 1(1):** India, that is Bharat, shall be Union of States.',
        '**Art 1(2):** States + Union Territories. **Art 1(3):** Territory = States + UTs + Acquired.',
        '**Union of States:** Indestructible Union of destructible States. Ambedkar. USA destructible Union indestructible States.',
        '**Present:** 28 States + 8 UTs = 36. J&K reorganised 31 Oct 2019. J&K UT + Ladakh UT.',
        '',
        '**2. Art 2 Admission New States**',
        '**Parliament power:** Admit new states. Sikkim 36th 26 Apr 1975 35th Amendment.',
        '**Art 3 Formation:** Parliament law form new state, alter area, boundaries, name.',
        '**Procedure:** President recommendation. State Legislature opinion refer - not binding. Simple majority Parliament.',
        '**New States:** Andhra 1953 1st linguistic, Gujarat/Maharashtra 1960, Nagaland 1963, Haryana 1966, Himachal 1971, Manipur/Tripura/Meghalaya 1972, Sikkim 1975, Mizoram/Arunachal 1987, Goa 1987, Chhattisgarh/Uttarakhand/Jharkhand 2000, Telangana 2014.',
        '',
        '**3. Art 4 Laws Amendment**',
        '**Art 4:** Laws Art 2-3 not amendment Art 368. Simple majority. No special majority needed.',
        '**Cession Territory:** Berubari Union 1960 SC. Cession need Constitutional Amendment. 9th Amendment 1960.',
        '**MPSC Point:** India Union not Federation. States no right secede. 28 States 8 UTs 2026.'
      ]
    }
  },
  {
    id: 'pol-6',
    title: {
      mizo: 'Chapter 6: The Union Executive & Parliament Art 52-122',
      english: 'Chapter 6: The Union Executive & Parliament Art 52-122'
    },
    notes: {
      mizo: [
        '**1. President Art 52-62**',
        '**Qualification:** Citizen, 35 years, Lok Sabha member qualification, No office profit.',
        '**Election:** Proportional representation single transferable vote. Secret. Value MLA = State Pop/1,000/Total MLAs. Value MP = Total MLA value/Total MPs.',
        '**Term:** 5 years. Resign Vice-President. Impeachment violation Constitution 2/3 both Houses.',
        '**Powers:** Executive Art 53, Legislative summon Art 85, Ordinance Art 123, Veto 3 types, Pardon Art 72, Emergency.',
        '**Veto:** Absolute - withhold, Suspensive - return once, Pocket - no time limit. Money Bill no suspensive.',
        '',
        '**2. Vice-President Art 63-71**',
        '**Ex-officio Chairman Rajya Sabha.** Election MPs both Houses. Term 5 years. Age 35.',
        '**Removal:** Rajya Sabha effective majority + Lok Sabha simple. No ground needed.',
        '**Acting President:** Vacancy/death/resignation/absence.',
        '',
        '**3. PM & Council Art 74-78**',
        '**Art 74:** CoM aid advise President. Binding 42nd 1976. Reconsider once 44th 1978.',
        '**Art 75:** PM appointed President. Others PM advice. Collective responsibility Lok Sabha. 15% limit 91st 2003.',
        '**PM Powers:** Leader Govt, Cabinet head, NITI Aayog, Inter-State Council, Appointments, Policy.',
        '',
        '**4. Parliament Art 79-122**',
        '**Lok Sabha:** 550 max. 530 States, 20 UTs. Present 543. Term 5 years. Age 25. Speaker Om Birla 2024.',
        '**Rajya Sabha:** 250 max. 238 States/UTs, 12 nominated Art, Lit, Science, Social Service. Present 245. Term 6 years. 1/3 retire 2 years. Chairman Jagdeep Dhankhar VP.',
        '**Sessions:** Budget, Monsoon, Winter. Max 6 months gap. Quorum 1/10.',
        '**Bill:** Ordinary both Houses, Money Lok Sabha only, Constitutional Art 368 special majority.',
        '**Joint Sitting Art 108:** Speaker presides. Deadlock ordinary bill. 3 times held.',
        '**Money Bill Art 110:** Speaker certifies. RS 14 days only recommend. President no veto.',
        '**Budget Art 112:** Annual Financial Statement. Charged Expenditure non-votable. Cut motions - Policy, Economy, Token.',
        '**Committees:** PAC, Estimates, Public Undertakings. PAC Chairman Opposition convention.',
        '**MPSC Point:** PM real head. President nominal. RS permanent. Money Bill LS only.'
      ],
      english: [
        '**1. President Art 52-62**',
        '**Qualification:** Citizen, 35 years, Lok Sabha member qualification, No office profit.',
        '**Election:** Proportional representation single transferable vote. Secret. Value MLA = State Pop/1,000/Total MLAs. Value MP = Total MLA value/Total MPs.',
        '**Term:** 5 years. Resign Vice-President. Impeachment violation Constitution 2/3 both Houses.',
        '**Powers:** Executive Art 53, Legislative summon Art 85, Ordinance Art 123, Veto 3 types, Pardon Art 72, Emergency.',
        '**Veto:** Absolute - withhold, Suspensive - return once, Pocket - no time limit. Money Bill no suspensive.',
        '',
        '**2. Vice-President Art 63-71**',
        '**Ex-officio Chairman Rajya Sabha.** Election MPs both Houses. Term 5 years. Age 35.',
        '**Removal:** Rajya Sabha effective majority + Lok Sabha simple. No ground needed.',
        '**Acting President:** Vacancy/death/resignation/absence.',
        '',
        '**3. PM & Council Art 74-78**',
        '**Art 74:** CoM aid advise President. Binding 42nd 1976. Reconsider once 44th 1978.',
        '**Art 75:** PM appointed President. Others PM advice. Collective responsibility Lok Sabha. 15% limit 91st 2003.',
        '**PM Powers:** Leader Govt, Cabinet head, NITI Aayog, Inter-State Council, Appointments, Policy.',
        '',
        '**4. Parliament Art 79-122**',
        '**Lok Sabha:** 550 max. 530 States, 20 UTs. Present 543. Term 5 years. Age 25. Speaker Om Birla 2024.',
        '**Rajya Sabha:** 250 max. 238 States/UTs, 12 nominated Art, Lit, Science, Social Service. Present 245. Term 6 years. 1/3 retire 2 years. Chairman Jagdeep Dhankhar VP.',
        '**Sessions:** Budget, Monsoon, Winter. Max 6 months gap. Quorum 1/10.',
        '**Bill:** Ordinary both Houses, Money Lok Sabha only, Constitutional Art 368 special majority.',
        '**Joint Sitting Art 108:** Speaker presides. Deadlock ordinary bill. 3 times held.',
        '**Money Bill Art 110:** Speaker certifies. RS 14 days only recommend. President no veto.',
        '**Budget Art 112:** Annual Financial Statement. Charged Expenditure non-votable. Cut motions - Policy, Economy, Token.',
        '**Committees:** PAC, Estimates, Public Undertakings. PAC Chairman Opposition convention.',
        '**MPSC Point:** PM real head. President nominal. RS permanent. Money Bill LS only.'
      ]
    }
  },
  {
    id: 'pol-7',
    title: {
      mizo: 'Chapter 7: State Executive, Judiciary & Local Govt',
      english: 'Chapter 7: State Executive, Judiciary & Local Govt'
    },
    notes: {
      mizo: [
        '**1. Governor Art 153-162**',
        '**Appointment:** President. 5 years. Age 35. Agent Centre. 7th 1956 same person 2+ states.',
        '**Powers:** Executive state. Appoint CM, Ministers, Advocate General, State EC. Summon/Dissolve Assembly. Ordinance Art 213. Pardon Art 161 except death. Report Art 356.',
        '**Discretion:** Reserve bill President Art 200. CM appointment hung assembly. 356 report.',
        '**Sarkaria 1983:** Governor apolitical. CM consultation. Tenure security.',
        '',
        '**2. CM & Council Art 163-164**',
        '**CM:** Real executive state. Majority leader Assembly. Appoint ministers Governor.',
        '**Council:** Collective responsibility Assembly. 15% limit 91st 2003. Individual Governor.',
        '',
        '**3. State Legislature Art 168-212**',
        '**Assembly:** 60-500. Term 5 years. Age 25. Speaker. Money Bill only.',
        '**Council:** 6 states only. 1/3 Assembly max 40 min. Term 6 years. 1/3 retire 2 years. Age 30.',
        '**Legislative Procedure:** Same Parliament. Governor assent/withhold/reserve/return once.',
        '',
        '**4. Judiciary Art 124-147 SC, 214-237 HC**',
        '**SC:** CJI + 33 judges 2019. Appointed President Collegium. Age 65. Removal President + Parliament special majority.',
        '**Jurisdiction:** Original Centre-State Art 131, Writ Art 32, Appellate, Advisory Art 143, Review Art 137.',
        '**HC:** Every state Art 214. CJ + others. Age 62. Writ Art 226 wider SC. Superintendence subordinate.',
        '**Judicial Review:** Art 13, 32, 226. Basic Structure Kesavananda 1973. Collegium 2nd Judges 1993, 3rd 1998.',
        '**Subordinate:** District Judge, Sessions Judge. Appointment Governor consultation HC.',
        '',
        '**5. Local Govt 73rd & 74th 1992**',
        '**73rd Panchayati Raj Art 243-243O:** 11th Schedule 29 subjects. 3-tier Gram Panchayat, Panchayat Samiti, Zila Parishad. Direct election 5 years. Reservation SC/ST proportion, Women 1/3. State EC conduct. State FC 5 years. Gram Sabha.',
        '**Mizoram Exception:** 6th Schedule ADCs. Village Councils not Panchayat. Traditional.',
        '**74th Municipalities Art 243P-243ZG:** 12th Schedule 18 subjects. 3 types - Nagar Panchayat transitional, Municipal Council smaller, Municipal Corporation larger. Ward Committees. Reservation same. District Planning Committee. Metropolitan Planning Committee.',
        '**Aizawl Municipal Corporation 2010:** 19 wards. Mayor. State EC election.',
        '**MPSC Point:** Governor agent. SC 34 judges. 73rd 11th Schedule 29 subjects. 74th 12th Schedule 18. Mizoram VC not Panchayat.'
      ],
      english: [
        '**1. Governor Art 153-162**',
        '**Appointment:** President. 5 years. Age 35. Agent Centre. 7th 1956 same person 2+ states.',
        '**Powers:** Executive state. Appoint CM, Ministers, Advocate General, State EC. Summon/Dissolve Assembly. Ordinance Art 213. Pardon Art 161 except death. Report Art 356.',
        '**Discretion:** Reserve bill President Art 200. CM appointment hung assembly. 356 report.',
        '**Sarkaria 1983:** Governor apolitical. CM consultation. Tenure security.',
        '',
        '**2. CM & Council Art 163-164**',
        '**CM:** Real executive state. Majority leader Assembly. Appoint ministers Governor.',
        '**Council:** Collective responsibility Assembly. 15% limit 91st 2003. Individual Governor.',
        '',
        '**3. State Legislature Art 168-212**',
        '**Assembly:** 60-500. Term 5 years. Age 25. Speaker. Money Bill only.',
        '**Council:** 6 states only. 1/3 Assembly max 40 min. Term 6 years. 1/3 retire 2 years. Age 30.',
        '**Legislative Procedure:** Same Parliament. Governor assent/withhold/reserve/return once.',
        '',
        '**4. Judiciary Art 124-147 SC, 214-237 HC**',
        '**SC:** CJI + 33 judges 2019. Appointed President Collegium. Age 65. Removal President + Parliament special majority.',
        '**Jurisdiction:** Original Centre-State Art 131, Writ Art 32, Appellate, Advisory Art 143, Review Art 137.',
        '**HC:** Every state Art 214. CJ + others. Age 62. Writ Art 226 wider SC. Superintendence subordinate.',
        '**Judicial Review:** Art 13, 32, 226. Basic Structure Kesavananda 1973. Collegium 2nd Judges 1993, 3rd 1998.',
        '**Subordinate:** District Judge, Sessions Judge. Appointment Governor consultation HC.',
        '',
        '**5. Local Govt 73rd & 74th 1992**',
        '**73rd Panchayati Raj Art 243-243O:** 11th Schedule 29 subjects. 3-tier Gram Panchayat, Panchayat Samiti, Zila Parishad. Direct election 5 years. Reservation SC/ST proportion, Women 1/3. State EC conduct. State FC 5 years. Gram Sabha.',
        '**Mizoram Exception:** 6th Schedule ADCs. Village Councils not Panchayat. Traditional.',
        '**74th Municipalities Art 243P-243ZG:** 12th Schedule 18 subjects. 3 types - Nagar Panchayat transitional, Municipal Council smaller, Municipal Corporation larger. Ward Committees. Reservation same. District Planning Committee. Metropolitan Planning Committee.',
        '**Aizawl Municipal Corporation 2010:** 19 wards. Mayor. State EC election.',
        '**MPSC Point:** Governor agent. SC 34 judges. 73rd 11th Schedule 29 subjects. 74th 12th Schedule 18. Mizoram VC not Panchayat.'
      ]
    }
  },
  {
    id: 'pol-8',
    title: {
      mizo: 'Chapter 8: Emergency, Elections & Commissions',
      english: 'Chapter 8: Emergency, Elections & Commissions'
    },
    notes: {
      mizo: [
        '**1. Emergency Part XVIII Art 352-360**',
        '**Art 352 National:** War/External Aggression/Armed Rebellion. President proclamation. Cabinet written advice 44th 1978. Parliament 1 month approve special majority. 6 months max. Lok Sabha approve. Effects - Federal Unitary, LS extend 1yr, Art 358 Art 19 suspend, Art 359 FR suspend President order except 20-21. Used 1962 China, 1971 Pak, 1975-77 Internal.',
        '**Art 356 State/President Rule:** Constitutional machinery failure. Governor report or otherwise. Parliament 2 months approve. 6 months max. Total 3 years with conditions. Assembly suspend/dissolve. Parliament legislate state. S.R. Bommai 1994 - judicial review, floor test, no dissolve before Parliament approve. Used 130+ times. Punjab, J&K max.',
        '**Art 360 Financial:** Financial stability threatened. Never used. President direction. Salary reduce SC/HC judges. Money Bill reserve.',
        '',
        '**2. Election Commission Art 324**',
        '**Art 324:** Superintendence, direction, control elections Parliament, State Leg, President, VP. CEC + 2 ECs. Appointed President 6yrs/65. Removal same SC judge.',
        '**Powers:** Electoral rolls, Schedule, Model Code Conduct, Party symbols, Recognise parties, De-register, EVM/VVPAT, Disqualify Art 102/191.',
        '**CEC:** Rajiv Kumar 2022-2025. T.N. Seshan reforms 1990-96. EPIC, MCC strict.',
        '**State EC Art 243K/243ZA:** Panchayat/Municipality elections. Appointed Governor. Independent.',
        '',
        '**3. Constitutional Bodies**',
        '**UPSC Art 315-323:** Chairman + members 6yrs/65. Manoj Soni 2022. IAS, IPS, Central Services exam. Advise Govt disciplinary matters.',
        '**Finance Commission Art 280:** 5 years. 15th N.K. Singh 2021-26. 41% tax states. Grants-in-aid Art 275. Chairman + 4 members.',
        '**CAG Art 148:** Guardian public purse. Girish Murmu 2020. Audit Union, State, PSU. Report President/Governor → Parliament/Assembly PAC. 6yrs/65.',
        '**AG Art 76:** Attorney General India. R. Venkataramani 2022. Highest law officer. Right audience all courts. No vote. Advise Govt.',
        '**NCSC Art 338:** SC Commission. 89th 2003 bifurcate NCST. Vijay Sampla. Investigate safeguards SC. Report President.',
        '**NCST Art 338A:** ST Commission. 89th 2003. Harsh Chouhan. Mizoram 94% ST. Powers civil court.',
        '**NCBC Art 338B:** Backward Classes. 102nd 2018 constitutional. Hansraj Ahir. Investigate OBC. 127th 2021 State list OBC.',
        '**Special Officer Linguistic Minorities Art 350B:** 7th 1956. Santosh Kumar. Report President.',
        '',
        '**4. Statutory Bodies**',
        '**NITI Aayog 2015:** Replaced Planning Commission. PM Chairman. CEO B.V.R. Subrahmanyam. Think tank. Cooperative federalism. No fund allocation.',
        '**NHRC 1993:** Protection Human Rights Act. Chairman retired CJI. Justice Arun Mishra 2021. Inquire violation, jail visit, recommend compensation.',
        '**CIC 2005:** RTI Act. Chief Information Commissioner Heeralal Samariya. Appeal RTI. Penalty PIO.',
        '**CVC 1964:** Santhanam Committee. Central Vigilance Commission. Statutory 2003. P.K. Srivastava 2022. Probity public life. CBI superintendence.',
        '**Lokpal 2013:** Lokpal & Lokayuktas Act. Justice A.M. Khanwilkar 2024. Chairperson + 8 members. Corruption PM, Ministers, MPs, Group A-D officers. Lokayukta states.',
        '**NDMA 2005:** Disaster Management Act. PM Chairman. Disaster response.',
        '',
        '**5. Amendments Art 368 Important List**',
        '**1st 1951:** 9th Schedule land reforms. Art 15(4) SEBC. Art 31A, 31B. Zamindari abolition.',
        '**7th 1956:** States Reorganisation. 14 States 6 UTs. HC common 2+ states. Art 350A, 350B.',
        '**24th 1971:** Parliament amend FR. Art 13, 368. Golaknath overturned.',
        '**25th 1971:** Art 31C DPSP 39(b)(c) over FR 14,19,31. Property compensation not challenge.',
        '**42nd 1976:** Mini Constitution. Preamble Socialist Secular Integrity. FD added. Art 31C expanded. Duration LS 6yrs. 368 unlimited. 39 amendments.',
        '**44th 1978:** Restore 42nd damage. Art 19(1)(f) Property deleted → 300A legal right. 352 Armed Rebellion. 6yrs→5yrs LS. Judicial Review restore.',
        '**52nd 1985:** Anti-Defection 10th Schedule. Rajiv Gandhi. Disqualify defect.',
        '**61st 1989:** Voting age 21→18 Art 326.',
        '**73rd 1992:** Panchayati Raj Part IX. 11th Schedule 29 subjects.',
        '**74th 1992:** Municipalities Part IXA. 12th Schedule 18 subjects.',
        '**86th 2002:** RTE Art 21A. FD 51A(k) parent duty. DPSP 45 change.',
        '**91st 2003:** Council Ministers 15% limit. Defector no minister. 75(1A), 164(1A).',
        '**97th 2011:** Cooperatives Part IXB. Art 19(1)(c), 43B.',
        '**99th 2014:** NJAC. Struck down SC 2015. Collegium continue.',
        '**101st 2016:** GST. Art 246A, 269A, 279A. 6th July 2017 implement.',
        '**102nd 2018:** NCBC constitutional Art 338B.',
        '**103rd 2019:** EWS 10% Art 15(6), 16(6). 124th Bill.',
        '**104th 2020:** SC/ST LS/Assembly reservation extend 10yrs till 2030. Anglo-Indian nomination end.',
        '**105th 2021:** State power OBC list restore. 127th Bill.',
        '**106th 2023:** Women Reservation 33% LS/Assembly. Nari Shakti Vandan. After delimitation 2029 likely.',
        '**MPSC Point:** 42nd mini, 44th restore, 73rd/74th local, 101st GST, 103rd EWS, 106th Women.'
      ],
      english: [
        '**1. Emergency Part XVIII Art 352-360**',
        '**Art 352 National:** War/External Aggression/Armed Rebellion. President proclamation. Cabinet written advice 44th 1978. Parliament 1 month approve special majority. 6 months max. Lok Sabha approve. Effects - Federal Unitary, LS extend 1yr, Art 358 Art 19 suspend, Art 359 FR suspend President order except 20-21. Used 1962 China, 1971 Pak, 1975-77 Internal.',
        '**Art 356 State/President Rule:** Constitutional machinery failure. Governor report or otherwise. Parliament 2 months approve. 6 months max. Total 3 years with conditions. Assembly suspend/dissolve. Parliament legislate state. S.R. Bommai 1994 - judicial review, floor test, no dissolve before Parliament approve. Used 130+ times. Punjab, J&K max.',
        '**Art 360 Financial:** Financial stability threatened. Never used. President direction. Salary reduce SC/HC judges. Money Bill reserve.',
        '',
        '**2. Election Commission Art 324**',
        '**Art 324:** Superintendence, direction, control elections Parliament, State Leg, President, VP. CEC + 2 ECs. Appointed President 6yrs/65. Removal same SC judge.',
        '**Powers:** Electoral rolls, Schedule, Model Code Conduct, Party symbols, Recognise parties, De-register, EVM/VVPAT, Disqualify Art 102/191.',
        '**CEC:** Rajiv Kumar 2022-2025. T.N. Seshan reforms 1990-96. EPIC, MCC strict.',
        '**State EC Art 243K/243ZA:** Panchayat/Municipality elections. Appointed Governor. Independent.',
        '',
        '**3. Constitutional Bodies**',
        '**UPSC Art 315-323:** Chairman + members 6yrs/65. Manoj Soni 2022. IAS, IPS, Central Services exam. Advise Govt disciplinary matters.',
        '**Finance Commission Art 280:** 5 years. 15th N.K. Singh 2021-26. 41% tax states. Grants-in-aid Art 275. Chairman + 4 members.',
        '**CAG Art 148:** Guardian public purse. Girish Murmu 2020. Audit Union, State, PSU. Report President/Governor → Parliament/Assembly PAC. 6yrs/65.',
        '**AG Art 76:** Attorney General India. R. Venkataramani 2022. Highest law officer. Right audience all courts. No vote. Advise Govt.',
        '**NCSC Art 338:** SC Commission. 89th 2003 bifurcate NCST. Vijay Sampla. Investigate safeguards SC. Report President.',
        '**NCST Art 338A:** ST Commission. 89th 2003. Harsh Chouhan. Mizoram 94% ST. Powers civil court.',
        '**NCBC Art 338B:** Backward Classes. 102nd 2018 constitutional. Hansraj Ahir. Investigate OBC. 127th 2021 State list OBC.',
        '**Special Officer Linguistic Minorities Art 350B:** 7th 1956. Santosh Kumar. Report President.',
        '',
        '**4. Statutory Bodies**',
        '**NITI Aayog 2015:** Replaced Planning Commission. PM Chairman. CEO B.V.R. Subrahmanyam. Think tank. Cooperative federalism. No fund allocation.',
        '**NHRC 1993:** Protection Human Rights Act. Chairman retired CJI. Justice Arun Mishra 2021. Inquire violation, jail visit, recommend compensation.',
        '**CIC 2005:** RTI Act. Chief Information Commissioner Heeralal Samariya. Appeal RTI. Penalty PIO.',
        '**CVC 1964:** Santhanam Committee. Central Vigilance Commission. Statutory 2003. P.K. Srivastava 2022. Probity public life. CBI superintendence.',
        '**Lokpal 2013:** Lokpal & Lokayuktas Act. Justice A.M. Khanwilkar 2024. Chairperson + 8 members. Corruption PM, Ministers, MPs, Group A-D officers. Lokayukta states.',
        '**NDMA 2005:** Disaster Management Act. PM Chairman. Disaster response.',
        '',
        '**5. Amendments Art 368 Important List**',
        '**1st 1951:** 9th Schedule land reforms. Art 15(4) SEBC. Art 31A, 31B. Zamindari abolition.',
        '**7th 1956:** States Reorganisation. 14 States 6 UTs. HC common 2+ states. Art 350A, 350B.',
        '**24th 1971:** Parliament amend FR. Art 13, 368. Golaknath overturned.',
        '**25th 1971:** Art 31C DPSP 39(b)(c) over FR 14,19,31. Property compensation not challenge.',
        '**42nd 1976:** Mini Constitution. Preamble Socialist Secular Integrity. FD added. Art 31C expanded. Duration LS 6yrs. 368 unlimited. 39 amendments.',
        '**44th 1978:** Restore 42nd damage. Art 19(1)(f) Property deleted → 300A legal right. 352 Armed Rebellion. 6yrs→5yrs LS. Judicial Review restore.',
        '**52nd 1985:** Anti-Defection 10th Schedule. Rajiv Gandhi. Disqualify defect.',
        '**61st 1989:** Voting age 21→18 Art 326.',
        '**73rd 1992:** Panchayati Raj Part IX. 11th Schedule 29 subjects.',
        '**74th 1992:** Municipalities Part IXA. 12th Schedule 18 subjects.',
        '**86th 2002:** RTE Art 21A. FD 51A(k) parent duty. DPSP 45 change.',
        '**91st 2003:** Council Ministers 15% limit. Defector no minister. 75(1A), 164(1A).',
        '**97th 2011:** Cooperatives Part IXB. Art 19(1)(c), 43B.',
        '**99th 2014:** NJAC. Struck down SC 2015. Collegium continue.',
        '**101st 2016:** GST. Art 246A, 269A, 279A. 6th July 2017 implement.',
        '**102nd 2018:** NCBC constitutional Art 338B.',
        '**103rd 2019:** EWS 10% Art 15(6), 16(6). 124th Bill.',
        '**104th 2020:** SC/ST LS/Assembly reservation extend 10yrs till 2030. Anglo-Indian nomination end.',
        '**105th 2021:** State power OBC list restore. 127th Bill.',
        '**106th 2023:** Women Reservation 33% LS/Assembly. Nari Shakti Vandan. After delimitation 2029 likely.',
        '**MPSC Point:** 42nd mini, 44th restore, 73rd/74th local, 101st GST, 103rd EWS, 106th Women.'
      ]
    }
  }
]

export default function PolityPage() { 
  return (
    <SubjectPage 
      subjectName={{
        mizo: 'Polity',
        english: 'Polity'
      }}
      chapters={polityChapters}
      slug="polity"
    
      backLink="/"
      testLink="/polity/test"
      testTitle="Polity Mock Test"
      testDesc="MPSC Polity Chapter 1-8 atanga zawhna 50"
    />
  )
}
